### ISSUE TITLE
 Crash the server through Chunk Destroyer

### ISSUE THREAD

**Issue by Fortleyz** [Kotori316/QuarryPlus#100]
**I have a crashed server and no longer enters through the Chunk Destroyer**

**To Reproduce
[crash-2020-08-17_22.22.55-server.txt](https://github.com/Kotori316/QuarryPlus/files/5088413/crash-2020-08-17_22.22.55-server.txt)
**
1. 
2. 
3. 

**Version 12.4.4**
* Minecraft: [1.12.2]
* Single Player or Multi Player?: [Single Player]
* Forge: [forge-1.12.2-14.23.5.2847]
* This mod (QuarryPlus)

**Comment by Kotori316** [comment]
Create new file, `(profile)\config\quarryplus\blacklist.json`.
The content of `blacklist.json` should be
```json
[
]
```

OR use [v12.4.5](https://www.curseforge.com/minecraft/mc-mods/additional-enchanted-miner/files/3035717)

**Comment by Fortleyz** [comment]
Thank you, the second option helped me
