### ISSUE TITLE
Quarry not giving me blocks when mining

### ISSUE THREAD

**Issue by keeper317** [Kotori316/QuarryPlus#101]
**Describe the bug**
_What happened to you?_
The quarry will fail to place blocks in the chest attached to the quarry despite breaking block and does so over 50% of the time.

**To Reproduce**
1. Make a world
2. Place a Solid Fuel Quarry near spawn
3. Power it with coal blocks

**Version**
* Minecraft: [1.15.2]
* Single Player or Multi Player?: [Single Player]
* Forge: [31.2.37]
* This mod (QuarryPlus): [15.3.3]
* Other mods: []

**Comment by Kotori316** [comment]
In my dev world, the quarry inserts items into the chest correctly.

**Comment by keeper317** [comment]
Oddly enough, mine is now too. I tried to redo it and record it to show you but now it works correctly.

**Comment by PCakes1** [comment]
I am having this issue with the solid fuel quarry with chests both directly to the side and with quark item cables. I am on the latest version, as part of the modpack all the mods 6.
