### ISSUE TITLE
No power being delivered to any machines

### ISSUE THREAD

**Issue by chaseyrt** [Kotori316/QuarryPlus#102]
**Describe the bug**
_What happened to you?_

No power being delivered using FluxPlug/Point or Mekanism Universal Cables

**To Reproduce**
1. Place FluxPlug or Mekanism Universal Cables
2. 
3. 

**Version**
* Minecraft: 1.15.2
* Single Player or Multi Player?: MP
* Forge: 31.2.45
* This mod (QuarryPlus): 1.15.2-15.3.3
* Other mods: Mekanism, Flux Networks

**Comment by chaseyrt** [comment]
I'm Guessing it's a mod incompatibility, so what mods work for supplying power. I also found a dupe bug with inventory sorting.

**Comment by Kotori316** [comment]
In my environment, the Flux Point is connected to quarry and worked fine.
If you can't use any sources, use Fuel Module stacked with 64 items.

EDIT: Tested in Single Player world.
