### ISSUE TITLE
Quarry brakes ores from AlltheModium but doesnt drop the ore.

### ISSUE THREAD

**Issue by TheBlacksmith1232** [Kotori316/QuarryPlus#103]
Describe the bug
when using a quarry from quarry plus it will mine Allthemodium, vibranium and unobtainium ores but wont pick them up they are being outright deleted

To Reproduce

1.setup quarry as you wound normally
2.place some of the offending ore in its path and watch as it mines them
3.check chest to find a lack of the corresponding ores

Additional comment
The Quarry is not suppose to brake the ore the they are programed for the player to brake them only apparently so your mod doesn't check to see if it minable, this is according to the issue thread for the all the mods 6 issue page

**Version**
* Minecraft: [1.16.3]
* Single Player or Multi Player?: [both]
* Forge: [forge-34.1.24]
* This mod (QuarryPlus): [v16.1.0]
* Other mods: [AlltheModium 1.1.15-1.16.3-34.1.0]

**Comment by Kotori316** [comment]
I wrote wrong code, when breaking block event is canceled.

**Comment by Kotori316** [comment]
Fixed in [v16.1.1](https://www.curseforge.com/minecraft/mc-mods/additional-enchanted-miner/files/3089499)
