### ISSUE TITLE
Quarry not working with ftb chunks

### ISSUE THREAD

**Issue by JumpinJac1** [Kotori316/QuarryPlus#104]
**Describe the bug**
_What happened to you?_

**To Reproduce**
1. Claim chunks around working quarry with FTB chunks
2. Blocks will break but drops will not be added
3. 

**Version**
* Minecraft: [1.16.3]
* Single Player or Multi Player?: [multiplayer]
* Forge: [34.1.42]
* This mod (QuarryPlus): []
* Other mods: [FTB Chunks https://www.curseforge.com/minecraft/mc-mods/ftb-chunks]

**Comment by Kotori316** [comment]
Use the latest version.
