### ISSUE TITLE
ChunkDestroyer can`t work

### ISSUE THREAD

**Issue by HomoUrsus** [Kotori316/QuarryPlus#108]
The problem is that when I try to install the chunk destroyer, it tells me that it is disabled. Also, when I am in survival, I cannot craft it, it does not show crafting in the JEI.

Maybe I should change some configs?

1. Place ChunkDestroyer 
2. Look over hotbar
3. "ChunkDestroyer is disable"

1.15.2
multiplayer
31.2.45
QuarryPlus - 15.3.3 
Other mods - [https://imgur.com/6wGaAil](url)

**Comment by Kotori316** [comment]
Yes, you should change config saved in config/quarryplus-common.toml
You'll find "common.machines" section (near line 120) and "ChunkDestroyer" entry, then change to false.
