### ISSUE TITLE
Solid Fuel Quarry Abusable

### ISSUE THREAD

**Issue by dkjednf** [Kotori316/QuarryPlus#112]
Hi all,

while using a Solid Fuel Quarry it is very easy to "abuse" it's fuel consume and block breaking method.
Specially when you are using block which required high RF like obsidian.
When the SFQ is breaking a block, the "internal RF counter" is going negative. It will reset to zero when you mine the SFQ block and place it again. Afterwards you are allowed to break another block, because the internal RF counter is set to zero again.
To prevent something like that, the following sequence would be better:
- SFQ is placed and start to mine
- SFQ "finds" a block, check it and calculate the required RF to mine it
- SFQ checks the internal RF counter and start mining only if there is more RF stored than the block would require to be mined

I did not check the other Quarries for now, because the SFQ is a low tier item in our modpack.

**To Reproduce**
1. Use a water bucket on a lava lake to create a plain obsidian surface.
2. Dig a small hole, place a Solid Fuel Quarry on the same layer like the obsidian surface and let it create the "frame".
3. While digging holes for the frame it will hit obsidian blocks and the internal RF counter turn to -XXk RF (was -20k for me).
4. Now break the Solid Fuel Quarry and replace it to the same position, it will mine another block and go to -20k RF again.
5. Repeat till you have enough obsidian mined.
 

**Version**
* Minecraft: 1.16.4
* Single Player or Multi Player?: MP
* Forge: 35.1.11
* This mod (QuarryPlus): AdditionalEnchantedMiner-1.16.4-16.1.4
* Other mods: many :)

**Comment by Kotori316** [comment]
This can be simply fixed, as you stated, but I forgot why I allowed minus energy. At the first, of course, quarry works when enough energy is stored, then I got some issues about energy duplication or something and I changed the behavior... But I can't remember the example or situation. Though I think it doesn't affect the work of SFQ, I need more search and check the effect of bugfix.
