### ISSUE TITLE
Possible display bug with Solid Fuel Quarry

### ISSUE THREAD

**Issue by Golrith** [Kotori316/QuarryPlus#115]
Minecraft 1.12.2

I've modified the config to limit the power of the SFQ as in my modpack it's an early game option and I want players to move onto the powered version, and then other mining options.

I've resulted in these values for the config:

        quarry {

            breakblock {
                D:BaseMaxRecieve=90.0
                D:BaseMaxStored=90.0
                D:BasePower=90.0
                D:EfficiencyCoefficient=1.3
                D:FortuneCoefficient=1.3
                D:SilktouchCoefficient=2.0
                D:UnbreakingCoefficient=1.0

                movehead {
                    D:BasePower=90.0
                    D:UnbreakingCoefficient=1.0
                }

            }

            makeframe {
                D:BaseMaxRecieve=45.0
                D:BaseMaxStored=90.0
                D:BasePower=10.0
                D:EfficiencyCoefficient=1.3
                D:UnbreakingCoefficient=1.0
            }

But I find that the tooltip with show 0/900 power, but the drill will keep mining for a while. I'm assuming that with the config values I've chosen it can't display the real power level, any ideas how I can get around this? Not quite sure how it results in 900 power.

Also, is there a way to increase the cost for the terrain clearing mode, or add a config option to either void those resources it clears, or require the area to be clear before the frame can be built? This is very powerful and fast way to obtain resources at next to no resource cost.

**Comment by Kotori316** [comment]
The tooltip shows the internal power[RF] in Solid Fuel Quarry. The Unit of config value is [MJ], that has 10 RF = 1 MJ relationship. So the number, 900 RF is equal to D:BaseMaxStored=90 [MJ].
The SFQ has 2 important values, Energy[RF] and Fuel Count[Tick]. The tooltip of Waila/TOP shows energy, and in most cases it shows 0. SFQ generates 40 RF/t, using the fuel, and it consumes energy soon to break blocks or moving head. See GUI of SFQ and find "FuelCount" at the right upper. When the count goes to 0, quarry stops. One more way, when fuel count > 0, the texture  of SFQ changes: the top turns to blue. I'm not planning to modify the tooltip because it cause more display bugs(removing the content of tooltip may no be not supported officially).

What's the terrain clearing mode? The mode which removes blocks inside the yellow lines? (I know quarry breaks Grass or Torch (blocks whose hardness = 0) with no cost, but it requires energy to break solid blocks (blocks whose hardness != 0).)

**Comment by Golrith** [comment]
Ah, MJ. I'll have to adjust the config values. Needs to be running at 90 RF/t, although it doesn't feel like it's running at 900RF/t (for the powered version)
The quarry is showing no fuel value, but still running. Might be because of the small energy buffer I've given it compared to how fast it makes power. It does eventually stop.

Yep, the removal of the blocks inside the yellow lines. The quarry will break those blocks insanely fast, 2 pieces of coal will clear the area (at default size), giving you 2-3 stacks of resources. The same coal when mining will give you about 32 blocks.
Does this use the Make Frame config settings? For that the Base Power is currently 10, so wondering if that's something to do with it?

Some more experimenting to do!

**Comment by Kotori316** [comment]
The energy to break blocks is calculated by this equation, `BasePower * Hardness * etc`. For SFQ, etc is 1 so we can ignore it. BasePower is the value in config. Hardness is the block hardness, stone=1.5, cobblestone=2, etc. Quarry also requires energy to move its head. The energy is in proportion to move distance.

I'll make config to disable removing block inside of yellow line , OR make it slow.

**Comment by Golrith** [comment]
That would be amazing, I've been playing around with the config settings and cannot get a good balance. I'd like the frame to build fast but clear that area slowly.

Not quite sure what I've done, but now the SFQ now clears the area in the yellow as soon as the block is placed and no fuel added. I took a long break at that point :D

Feature request, would it be possible to also add 2 config options for TickDelayAfterMining, one for both quarries? The SFQ can be quite speedy at mining, and I haven't been able to slow it down from the energy values in the config.

**Comment by Kotori316** [comment]
Quarries soon break Grass or Torch as they requires 0 RF to break(hardness
is 0).

I can force quarry to delay after mining, but why should I separate config
of SFQ and normal one? Yes, it's possible, just my question.

**Comment by Golrith** [comment]
Yep, aware about the 0 hardness issue. This was a surface outcrop of vanilla iron ore that got cleared instantly.

Reason for the separate configs is that I'm working on a progression pack, and the SFQ is your starter way to obtain resources, but it can mine much faster than the player can make use of the resources at that point. The normal quarry would be a faster upgrade and players will have infrastructure in place to handle the resources.

But, I'll work with whatever you do.

**Comment by Kotori316** [comment]
Released 12.4.6
* Added tick delay to config
* Added "DisableFillerMode" to disallow to remove blocks inside of yellow line.
