### ISSUE TITLE
Speed upgrades

### ISSUE THREAD

**Issue by ThatTonybo** [Kotori316/QuarryPlus#116]
How do you make the quarry faster? It's very slow compared to Buildcraft's old quarry

**Comment by Kotori316** [comment]
Add Efficiency to quarry using [EnchantMover](https://github.com/Kotori316/QuarryPlus/wiki/EnchantMover).  With high energy supply, the enchanted machine works faster.

**Comment by ThatTonybo** [comment]
I already have the quarry placed, if I break it will it remember it's progress?

**Comment by Kotori316** [comment]
If you didn't place anything in the quarry area, yes. Quarry will skip air.

**Comment by ThatTonybo** [comment]
Alright, thank you :)
