### ISSUE TITLE
[1.16.5] Placing / Using the Quarry crashes the server. (FTB Chunks related?)

### ISSUE THREAD

**Issue by Gbergz** [Kotori316/QuarryPlus#119]
**Describe the bug**
Using Quarry crashe the server. (FTB Chunks related?)

**To Reproduce**
1. Place a quarryplus quarry down.
2. Server crashes.
3. Profit.

**Version**
* Minecraft: 1.16.5
* Single Player or Multi Player?: Multiplayer, might happen in SP too.
* Forge: 36.1.31
* This mod (QuarryPlus): 16.1.7
* Other mods: Modlist scroll down: (but I think its a cross integration issue with ftb chunks newer updates.)
https://www.curseforge.com/minecraft/modpacks/tnp-limitless-3/files/3367807

EDIT: Crash report: https://gist.github.com/Gbergz/c155050c19773a5cb1df1430c985520d

**Comment by Kotori316** [comment]
Change `SendNotificationOfChunkProtection` in config to `false` to prevent crashes.
I'll fix it, but you can use this option as temporally solution.

**Comment by Kotori316** [comment]
Fixed in [v16.1.8](https://www.curseforge.com/minecraft/mc-mods/additional-enchanted-miner/files/3376350)
