### ISSUE TITLE
Issues with liquid source blocks

### ISSUE THREAD

**Issue by kreezxil** [Kotori316/QuarryPlus#12]
The quarry when equipped with a pump does get the source blocks. It still treats the disintegrating non-source blocks as if they were source blocks and tries to pick them up even tho it can't. In order to make drill bit advance beyond them you have to place a block on them to help the liquid decay faster.

**Comment by NickelodeonKing** [comment]
Yea I have a fully upgraded quarry with a pump and storage for it... but as the fluid was disintegrating when the flowing fluids flatten out on the last phase the quarry treats the flat surfaced fluids as source blocks even though they aren't. So the quarry stayed there for hours till I got back on to the game in the morning and fixed it by putting a block on them.
