### ISSUE TITLE
Cannot work out the raplacerModule 

### ISSUE THREAD

**Issue by FallenRecruit** [Kotori316/QuarryPlus#120]
Cannot work out how to set the block the replacer module uses

**Version**
* Minecraft: 1.16.4
* Single Player or Multi Player?: Both
* Forge: 35.1.36
* This mod (QuarryPlus): 16.1.4

**Comment by Kotori316** [comment]
I didn't provide the way to set block for Replacer Module so I added it in [v16.1.9](https://www.curseforge.com/minecraft/mc-mods/additional-enchanted-miner/files/3387240).
I the version, just right click a block with Replacer Module, then the item is set in the module. See tooltip and chat massage.
