### ISSUE TITLE
Minecraft 1.17 alpha version Crash on launch

### ISSUE THREAD

**Issue by ArrowFX** [Kotori316/QuarryPlus#122]
**Describe the bug**
_What happened to you?_
After launching the game from the Minecraft launcher the game loads for about 5 seconds and then crashes.

**To Reproduce**
1. Download and install the mod and its required mods
2.  Launch the game
3.  Crash... Can't really explain more.

Log: https://pastebin.com/pMjKk0Ee

**Version**
* Minecraft: [1.17]
* Single Player or Multi Player?: [None]
* Forge: [No, Fabric]
* This mod (QuarryPlus): [Yes]
* Other mods: [
*      - antighost@1.17-fabric0.34.9-1.1.4
	- appleskin@mc1.17-2.0.0
	- architectury@2.2.21
	- atlantis@2021.7.10-1.17-1.8.0-fabric
	- attributefix@1.0.1
	- autoconfig1u@3.3.1
	- automated_crafting@1.3.23+MC1.17
	- beenfo@1.17-fabric0.34.9-1.3.2
	- better_wandering_trader@1.7.0
	- betterbiomeblend@1.17.0-1.1.8-fabric
	- bettermineshafts@1.17-1.0.0
	- betternether@5.1.3
	- betterstrongholds@1.17-1.1
	- betterthanmending@1.3.0
	- betterthirdperson@1.5.0
	- bigbeacons@1.2.2
	- biome_locator@1.1.3
	- blue_endless_jankson@1.2.1
	- blur@2.1.0
	- bowinfinityfix@rv10
	- breakprogress@1.0.1
	- caelus@0.0.16-1.17
	- cardinal-components@3.0.0
	- cardinal-components-base@3.0.0
	- cardinal-components-block@3.0.0
	- cardinal-components-chunk@3.0.0
	- cardinal-components-entity@3.0.0
	- cardinal-components-item@3.0.0
	- cardinal-components-level@3.0.0
	- cardinal-components-scoreboard@3.0.0
	- cardinal-components-util@3.0.0
	- cardinal-components-world@3.0.0
	- castle_dungeons@2.6-1.17-fabric
	- charm@3.2.2
	- cleancut@1.17-4.0-fabric
	- cloth-api@2.0.54
	- cloth-basic-math@0.5.1
	- cloth-client-events-v0@2.0.54
	- cloth-common-events-v1@2.0.54
	- cloth-config2@5.0.34
	- cloth-datagen-api-v1@2.0.54
	- cloth-scissors-api-v1@2.0.54
	- cloth-utils-v1@2.0.54
	- clumps@fabric-1.17-7.0.0.2
	- colytra@2.0.0-1.17
	- com_electronwill_night-config_core@3.6.2
	- com_electronwill_night-config_toml@3.6.2
	- com_moandjiezana_toml_toml4j@0.7.2
	- consistency_plus@0.4.0-RC1-build.283
	- controlling@1.1.2
	- crowdin-translate@1.3+1.17
	- customportalapi@0.0.1-beta37-1.17
	- disable_custom_worlds_advice@1.3
	- durabilityviewer@1.17-fabric0.34.9-1.10
	- dynamicfps@2.0.4
	- easiervillagertrading@1.17-fabric0.34.9-1.5.4
	- easybreeding@7.0.0
	- enchantmentdescriptions@3.0.11
	- entityculling@1.3.3
	- expandedstorage@7.0.0-alpha.31
	- fabric@0.36.0+1.17
	- fabric-api-base@0.3.0+8d89ed5432
	- fabric-api-lookup-api-v1@1.2.0+2b5c62d03d
	- fabric-biome-api-v1@3.1.11+c345aea83d
	- fabric-blockrenderlayer-v1@1.1.5+a02b44633d
	- fabric-command-api-v1@1.1.1+a02b44633d
	- fabric-commands-v0@0.2.2+92519afa3d
	- fabric-containers-v0@0.1.12+a02b44633d
	- fabric-content-registries-v0@0.2.2+a02b44633d
	- fabric-crash-report-info-v1@0.1.5+be9da3103d
	- fabric-dimensions-v1@2.0.10+a02b44633d
	- fabric-entity-events-v1@1.1.0+a02b44633d
	- fabric-events-interaction-v0@0.4.9+a722d8c03d
	- fabric-events-lifecycle-v0@0.2.1+92519afa3d
	- fabric-game-rule-api-v1@1.0.6+a02b44633d
	- fabric-item-api-v1@1.2.4+a02b44633d
	- fabric-item-groups-v0@0.2.10+b7ab61213d
	- fabric-key-binding-api-v1@1.0.4+a02b44633d
	- fabric-keybindings-v0@0.2.2+36b77c3e3d
	- fabric-language-kotlin@1.6.1+kotlin.1.5.10
	- fabric-language-scala@1.0.0
	- fabric-lifecycle-events-v1@1.4.4+a02b4463d5
	- fabric-loot-tables-v1@1.0.4+a02b44633d
	- fabric-mining-levels-v0@0.1.3+92519afa3d
	- fabric-models-v0@0.3.0+a02b44633d
	- fabric-networking-api-v1@1.0.11+b7ab6121d5
	- fabric-networking-blockentity-v0@0.2.11+a02b44633d
	- fabric-networking-v0@0.3.2+92519afad5
	- fabric-object-builder-api-v1@1.10.9+b7ab61213d
	- fabric-object-builders-v0@0.7.3+a02b44633d
	- fabric-particles-v1@0.2.4+a02b44633d
	- fabric-registry-sync-v0@0.7.10+e2961fee3d
	- fabric-renderer-api-v1@0.4.3+676f40fa3d
	- fabric-renderer-indigo@0.4.8+a02b44633d
	- fabric-renderer-registries-v1@3.2.0+a02b44633d
	- fabric-rendering-data-attachment-v1@0.1.5+a02b44633d
	- fabric-rendering-fluids-v1@0.1.13+a02b44633d
	- fabric-rendering-v0@1.1.2+92519afa3d
	- fabric-rendering-v1@1.6.0+a02b44633d
	- fabric-resource-loader-v0@0.4.7+b7ab6121d5
	- fabric-screen-api-v1@1.0.4+198a96213d
	- fabric-screen-handler-api-v1@1.1.8+a02b44633d
	- fabric-structure-api-v1@1.1.11+e36969833d
	- fabric-tag-extensions-v0@1.1.4+a02b446313
	- fabric-textures-v0@1.0.6+a02b44633d
	- fabric-tool-attribute-api-v1@1.2.12+b7ab61213d
	- fabricasmtools@0.4.0
	- fabricloader@0.11.6
	- fallingtree@2.11.5
	- ferritecore@3.0.0
	- flytre_lib@0.2.21
	- fourinchknife-trueinfinity@1.2.0
	- gbfabrictools@1.3.4+1.17
	- geckolib3@3.0.8
	- horseinfo@0.3.0-1.17
	- infinitevillagertrading@1.17-fabric0.34.9-1.1
	- inventoryhud@3.3.2
	- inventorysorter@1.7.9-1.17
	- jankson@3.0.1+j1.2.0
	- java@16
	- jumpoverfences@1.16-0.0.3
	- kubejs@1605.3.10-build.9999
	- kyrptconfig@1.1.10-1.17
	- libcd@3.0.3+1.16.3
	- libgui@4.0.0+1.17
	- libninepatch@1.1.0
	- lightoverlay@6.0.0
	- limitless@1.3.2
	- magna@1.5.5-1.17-pre4
	- maybe-data@1.0.1-1.17
	- minecraft@1.17
	- mining_dims@1.1.8
	- mm@2.3
	- modmenu@2.0.2
	- morevillagers-fabric@2.0.3-SNAPSHOT
	- mostructures@1.2.1-1.17
	- net_gudenau_lib_unsafe@1.4.3
	- omega-config@1.0.8
	- openworlds@1.0.3
	- optifabric@1.11.17
	- org_jetbrains_kotlin_kotlin-reflect@1.5.10
	- org_jetbrains_kotlin_kotlin-stdlib@1.5.10
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7@1.5.10
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8@1.5.10
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm@1.5.0
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8@1.5.0
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm@1.2.1
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm@1.2.1
	- pehkui@2.2.1+1.14.4-1.17
	- playerabilitylib@1.3.0-nightly.1.17-rc1
	- quarryplus@17.0.0-fabric_322
	- quickshulker@1.1.14-1.17
	- repurposed_structures@2.1.1+1.17.1
	- rhino@1605.1.1-build.23
	- roughlyenoughitems@6.0.264-alpha
	- satin@1.6.0-nightly.1.17-pre3
	- shulkerboxtooltip@3.0.0-alpha.4+1.17
	- shulkerutils@1.0.1-1.17
	- spawnermod@1.1.1
	- static-content@1.0.1-1.16.2
	- staticdata@1.1.2
	- toolstats@2.0.1
	- tooltipfix@1.0.3-1.16
	- torohealth@1.17-fabric-5
	- upgradedshulkers@1.0.1-1.17
	- user11681_reflect@2.0.0
	- user11681_shortcode@0.4.0
	- vanilla-hammers@3.1.2-1.17
	- vanillaexcavators@1.1.0
	- villagers-follow-emeralds@1.1.0
	- waystones@2.0.1
	- whereisit@1.12.8
	- worldedit@7.2.6-beta-01+1415e6f
	- wthit@3.7.0
	- xaerominimap@21.13.0
	- xaeroworldmap@1.14.6.1
	- yungsapi@1.17-Fabric-13
* ]

**Comment by Kotori316** [comment]
Fixed in the latest version. Thank you for reporting.
