### ISSUE TITLE
Make the quarry keep working even if the y-axis is under 0 (1.18-exp1 Compatibility)

### ISSUE THREAD

**Issue by Flamarine** [Kotori316/QuarryPlus#123]
Using Fabric Loader 0.11.6 and Fabric API 0.37.2-1.18_exp1.
Tested in 1.18-exp1 (Yeah it's compatible with 1.18-exp1).
You can make a temporary release for 1.18 as the mod is fully compatible with 1.18-exp1 and pretty stable.

**Comment by Kotori316** [comment]
I don't support any pre-release or snapshot version until it become release candidate or release version.

For this issue, I remove the hardcode part of the bottom of the world (before 0), but I didn't make sure it works in the snapshot or modified world. c7294d49679944ad54b8a0fb03f566305f011904
Also I added an item called Y-Setter, which can change the bottom of quarry area. You can set under 0.
