### ISSUE TITLE
The Quarry crashes the entire server

### ISSUE THREAD

**Issue by PrincessMiku210** [Kotori316/QuarryPlus#124]
The Quarry+ quarry crashes my entire server when placed down

Simply placing it down anywhere will crash things 

## Versions

* Minecraft version: 1.16.5
* Single Player or Multi Player?: Multiplayer
* Forge version: 36.1.31
* QuarryPlus version: 16.1.7
* Other mods: This is in the modpack "TNP Limitless 3" version 1.10.6

**Comment by Kotori316** [comment]
Give me the crash report. I can't work without it.
