### ISSUE TITLE
[compatibility] simple pipe

### ISSUE THREAD

**Issue by quentfr21** [Kotori316/QuarryPlus#128]
hello

i would like to know if you can make quarry able to put in simple pipe mod
https://www.curseforge.com/minecraft/mc-mods/simplepipes

thanks in advance

**Comment by Kotori316** [comment]
Added in the latest version. See this picture to get how to use pipe. 

![2021-08-29_14 36 26_2](https://user-images.githubusercontent.com/28705167/131240012-e9b64908-67c6-4111-ac75-95b822864797.png)

**Comment by quentfr21** [comment]
thanks a lot you are the best :)
