### ISSUE TITLE
I have the mod and the add-ons but the content of the mod does not appear in the game

### ISSUE THREAD

**Issue by TheFroggeKing** [Kotori316/QuarryPlus#129]
## Describe the bug

_What happened to you?: mod elements do not appear

## Versions

* Minecraft version: [1.17.10]
* Single Player or Multi Player?: [single]
* Forge version: []
* QuarryPlus version: [fabric 1.17.10]
* Other mods: []

## Crash report or logs

If your Minecraft has crashed, please attach the crash report. Please use pastebin or just paste the report.

**Comment by Kotori316** [comment]
Give me more detail, please. What's the addon? (I don't release any addons for this mod)

* Did you download fabric version of mod? Is the file for fabric, not forge?
* Is the mod loaded correctly? Is it shown in mods list?
* Do you have debug.log?

In my environment, all elements appear as I intend.

**Comment by TheFroggeKing** [comment]
already solved
some files of my minecraft were corrupt
sorry for the inconvenience
