### ISSUE TITLE
Fabric 1.17 doesnt seem to be taking energy from Reborn Core

### ISSUE THREAD

**Issue by campbebj** [Kotori316/QuarryPlus#131]
## Describe the bug

quarry doesnt seem to be taking energy from Reborn Core

## To Reproduce

1. Place a quarry
2. place a creative tech reborn/ reborn core solar generator next to it (creative infinite power for testing)
3. try alternative by placing generator 1 block away and attempting to connect with cables (tech reborn cables wont connect to quarry)

## Versions

* Minecraft version: 1.17
* Single Player or Multi Player?: server
* Forge version: Fabric loader 0.11.6 / api 0.40.1
* QuarryPlus version: 17.0.347
* Other mods: Tons.

## Crash report or logs
No crash

**Comment by Kotori316** [comment]
Please do not omit the version of other mods. In fact, I don't need version of REI, some pipe mod, storage mod, etc., but you are talking about compatibility of this mod and Tech Reborn. So you should add the version of Tech Reborn, Reborn Core, and other energy mods.

In my environment with old version(fabric 0.37.0, TR 5.0.3, RC 5.0.0, FastTransferLib 0.5.6), things are working. I heard TR has update of its energy system, so your problem may come from the changes. I'll update my environment.

**Comment by campbebj** [comment]
apologies, i forgot to mention im using the latest of TR and RC. 5.0.8 (needed them other compatabilities)

**Comment by Kotori316** [comment]
Updated to TR and RC 5.0.8 and rewrote code of energy API.
16 E in TR = 1 FE in QuarryPlus.
Quarry Plus with Efficiency 5, Unbreaking 3, Silktouch consumes 2.65 FE/t to remove Stones so it requires about 48 E/t
