### ISSUE TITLE
It crashs whlie I was starting the game

### ISSUE THREAD

**Issue by tankyap** [Kotori316/QuarryPlus#135]
When I was loaded with this mod, The game just crash when it even didnt start it.and I tested with just fabric api,cloth api and the mod and it still same.

the exit code and crash report:
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'quarryplus'!
Exit Code：-1
[crash report.txt](https://github.com/Kotori316/QuarryPlus/files/7235166/crash.report.txt)

cloth API ver:5.0.38
fabric loader ver:fabric loader 0.11.6-1.17.1
fabric API ver: 0.40.1
Game version:1.17.1
Additional Enchant Miner mod ver:latest version(1.17-fabric-17.0.376)

latest log file:[latest.log](https://github.com/Kotori316/QuarryPlus/files/7235233/latest.log)

**Comment by Kotori316** [comment]
It seems that your config file(`config/quarryplus.toml`) was broken. It contains something wrong character at the first line. Remove the config file and run Minecraft again. If the problem is not fixed, please give me the config file.
