### ISSUE TITLE
Possible bug in the nether and maybe the other dimensions

### ISSUE THREAD

**Issue by ArrowFX** [Kotori316/QuarryPlus#138]
## Describe the bug

_What happened to you?_

## To Reproduce

1.  Place a quarry of size 254 width and length at the roof of the nether
2. Wait for the quarry to form and start mining
3. at about y level 80 the quarry will stop working and if you move the quarry down to y level 80 and start it there it will only mine the blocks of level 80 and level 79 before stopping.

If your server/client has crashed, please give me the crash report.

## Versions

* Minecraft version: [1.16.5]
* Single Player or Multi Player?: [Single player]
* Forge version: [forge-1.16.5-36.2.8]
* QuarryPlus version: [AdditionalEnchantedMiner-1.16.5-16.1.9.jar]
* Other mods: [
abnormals_core-1.16.5-3.3.0.jar
AdditionalEnchantedMiner-1.16.5-16.1.9.jar
AI-Improvements-1.16.2-0.3.0.jar
AkashicTome-1.4-16.jar
Apotheosis-1.16.5-4.8.0.jar
appleskin-forge-mc1.16.x-2.1.0.jar
AppleTreesRev-Forge-1.16.5-v2.4.jar
appliedenergistics2-8.4.1.jar
Aquaculture-1.16.5-2.1.21.jar
architectury-1.23.33-forge.jar
astralsorcery-1.16-1.16.5-1.13.12.jar
AttributeFix-1.16.5-10.1.3.jar
Atum-1.16.5-2.2.8.jar
AutoRegLib-1.6-49.jar
balancedenchanting-1.0.jar
BetterAdvancements-1.16.5-0.1.0.108.jar
betterbiomeblend-1.16.4-1.2.9-forge.jar
BetterCaves-Forge-1.16.4-1.1.2.jar
BetterDungeons-1.16.4-1.2.jar
BetterMineshafts-Forge-1.16.4-2.0.4.jar
BetterStrongholds-1.16.4-1.2.1.jar
BiomesOPlenty-1.16.5-13.1.0.477-universal.jar
BloodMagic-1.16.4-3.1.3-18.jar
Bookshelf-Forge-1.16.5-10.3.29.jar
Botania-1.16.5-419.jar
BotanyPots-1.16.5-7.1.26.jar
Bountiful-1.16.4-3.3.1.jar
BrandonsCore-1.16.5-3.0.10.237-universal.jar
buildinggadgets-1.16.5-3.8.0.jar
bwncr-1.16.5-3.10.16.jar
byg-1.3.4.jar
caelus-forge-1.16.5-2.1.3.1.jar
cagedmobs-1.16.5-1.3.8.jar
carryon-1.16.5-1.15.5.15.jar
catalogue-1.3.0-1.16.5.jar
cfm-7.0.0pre22-1.16.3.jar
charginggadgets-1.3.0.jar
ChickenChunks-1.16.5-2.8.0.86-universal.jar
Chisel-MC1.16.5-2.0.1-alpha.4.jar
chiselsandbits-0.3.4-RELEASE.jar
chocolate-1.3.0-1.16.4.jar
citadel-1.8.1-1.16.5.jar
ClientTweaks_1.16.3-5.3.0.jar
cloth-config-4.11.26-forge.jar
Clumps-6.0.0.27.jar
CodeChickenLib-1.16.5-4.0.3.434-universal.jar
cofh_core-1.16.5-1.3.1.jar
collective-1.16.5-2.64.jar
comforts-forge-1.16.5-4.0.1.3.jar
CommonCapabilities-1.16.5-2.8.0.jar
configured-1.2.0-1.16.3.jar
Controlling-7.0.0.26.jar
CraftTweaker-1.16.5-7.1.2.451.jar
create-mc1.16.5_v0.3.2d.jar
CTM-MC1.16.1-1.1.2.6.jar
Cucumber-1.16.4-4.1.10.jar
curios-forge-1.16.5-4.0.5.3.jar
CuriosQuarkOBP-1.16.5-1.0.2.jar
curiouselytra-forge-1.16.5-4.0.2.3.jar
Cyclic-1.16.5-1.5.2.jar
yclopsCore-1.16.5-1.11.10.jar
DarkUtilities-1.16.5-8.0.10.jar
Draconic-Evolution-1.16.5-3.0.15.415-universal.jar
DungeonCrawl-1.16.5-2.3.2.jar
dungeons_plus-1.16.5-1.1.5.jar
durabilityviewer-1.16.4-forge35.0.7-1.10.1.jar
DynamicSurroundings-1.16.4-4.0.4.2.jar
DynamicTrees-1.16.5-0.10.0-Beta25.jar
easy_villagers-1.16.5-1.0.11.jar
elevatorid-1.16.5-1.7.13.jar
EnchantmentDescriptions-1.16.5-7.0.16.jar
extraboats-1.16.5-2.1.0.jar
ExtremeReactors2-1.16.5-2.0.27.jar
FastLeafDecay-v25.jar
FeederHelmet-1.11.2.jar
ferritecore-2.1.0-forge.jar
findme-1.16.3-2.2.0.0.jar
flywheel-1.16-0.2.4.jar
fortunate-2.10.1-MC-1.16.4.jar
ftb-backups-2.1.1.6.jar
ftb-library-forge-1605.3.3-build.71.jar
geckolib-forge-1.16.5-3.0.46.jar
ImmersiveEngineering-1.16.5-5.0.3-138.jar
incontrol-1.16-5.2.1.jar
industrial-foregoing-1.16.5-3.2.14.6-14.jar
infinitetrading_1.16.5-1.9.jar
invtweaks-1.16.4-1.0.1.jar
ironchest-1.16.5-11.2.13.jar
ironshulkerboxes-1.16.4-5.1.11.jar
item-filters-forge-1605.2.5-build.9.jar
Jade-1.16.4-2.8.0.jar
jei-1.16.5-7.7.1.121.jar
jei-professions-1.0.0-1.16.4.jar
JEIEnchantmentInfo-1.16.4-1.2.1.jar
jeiintegration_1.16.5-7.0.1.15.jar
JEITweaker-1.16.5-1.0.1.35.jar
JustEnoughResources-1.16.5-0.12.1.128.jar
kotlinforforge-1.15.1-obf.jar
kubejs-forge-1605.3.18-build.129.jar
lazydfu-0.1.3.jar
Mantle-1.16.5-1.6.123.jar
mcjtylib-1.16-5.0.22.jar
mcw-bridges-1.0.6-mc1.16.5.jar
Mekanism-1.16.5-10.0.21.448.jar
MekanismAdditions-1.16.5-10.0.21.448.jar
MekanismGenerators-1.16.5-10.0.21.448.jar
MekanismTools-1.16.5-10.0.21.448.jar
minecolonies-1.0.0-RELEASE-universal.jar
mining_dimension-1.16.5-1.0.6.jar
modnametooltip_1.16.2-1.15.0.jar
moreoverlays-1.18.15-mc1.16.5.jar
morevillagers-FORGE-1.16.5-1.5.5.jar
Morph-o-Tool-1.4-27.jar
MouseTweaks-2.14-mc1.16.2.jar
mowziesmobs-1.5.19.jar
MysticalAgradditions-1.16.5-4.2.1.jar
MysticalAgriculture-1.16.5-4.2.3.jar
MysticalCustomization-1.16.4-2.1.5.jar
NaturesCompass-1.16.5-1.9.1-forge.jar
Neat+1.7-27.jar
observerlib-1.16.5-1.5.3.jar
OreExcavation-1.8.157.jar
Patchouli-1.16.4-53.2.jar
Placebo-1.16.5-4.6.0.jar
polymorph-forge-1.16.5-0.25.jar
Quark-r2.4-316.jar
QuarkOddities-1.16.3.jar
randompatches-2.4.4-forge.jar
repurposed_structures_forge-3.2.5+1.16.5.jar
rftoolsbase-1.16-2.0.11.jar
rftoolspower-1.16-3.0.9.jar
rhino-forge-1605.1.4-build.63.jar
Runelic-1.16.5-7.0.2.jar
ScalableCatsForce-2.13.5-build-2-with-library.jar
SimpleStorageNetwork-1.16.5-1.4.3.jar
SoL-Carrot-1.16.5-1.10.1.jar
SolarFluxReborn-1.16.3-16.2.5.jar
SpartanShields-1.16.5-2.1.2.jar
SpawnerFix-1.16.2-1.0.0.2.jar
speedyhoppers-1.16.4-1.jar
StorageDrawers-1.16.3-8.3.0.jar
structure_gel-1.16.5-1.7.7.jar
structurize-0.13.219-ALPHA-universal.jar
swingthroughgrass-1.16.4-1.5.3.jar
TbscClick-v2.3.1-mc1.16.jar
TConstruct-1.16.5-3.1.2.265.jar
theoneprobe-1.16-3.1.4.jar
thermal_cultivation-1.16.5-1.3.0.jar
thermal_expansion-1.16.5-1.3.0.jar
thermal_foundation-1.16.5-1.3.2.jar
thermal_innovation-1.16.5-1.3.0.jar
thermal_locomotion-1.16.5-1.3.0.jar
titanium-1.16.5-3.2.8.4-10.jar
tombstone-1.16.5-6.5.3.jar
torchmaster-2.3.8.jar
TrashSlot_1.16.3-12.2.1.jar
twilightforest-1.16.5-4.0.546-universal.jar
upgrade_aquatic-1.16.5-3.1.0.jar
Uppers-0.3.2.jar
upsizer-mc1.16.4-6.1.1.jar
useful_backpacks-1.16.5-1.12.1.90.jar
u_team_core-1.16.5-3.2.1.196.jar
valhelsia_core-16.0.10.jar
valhelsia_structures-1.16.5-0.1.5.jar
VanillaTweaks-1.16.5-1.5.45.jar
Waystones_1.16.5-7.6.3.jar
XaerosWorldMap_1.17.1_Forge_1.16.5.jar
Xaeros_Minimap_21.17.2_Forge_1.16.5.jar
YungsApi-1.16.4-Forge-12.jar
YungsExtras-Forge-1.16.4-1.0.jar
ZeroCore2-1.16.5-2.1.4.jar
]

## Crash report or logs

No Crashes nor any error in logs

If you need any more information then feel free to ask!

If your Minecraft has crashed, please attach the crash report. Please use pastebin or just paste the report.

**Comment by Kotori316** [comment]
As I tried in my world, this kind of error didn't happen.
The `debug.log` may contain the detail of quarry work, but it may not exist if you use mod pack.
If `debug` in quarryplus config is true, it outputs energy consumption detail and tells when quarry stopped working (INFO level in latest.log).
