### ISSUE TITLE
[1.12.2][Bug][Urgent] There is no way to extract liquid from chunk destroyer

### ISSUE THREAD

**Issue by sferatime** [Kotori316/QuarryPlus#143]
Chunk destroyer doesn't push the liquid. I also can not pump it out.

1.  Put chunk destroyer, supply it with power.
2.  Start it 
3.  Use Hwyla to check amount of liquit inside
4.  Try to take liquid out

(https://user-images.githubusercontent.com/59023962/138172500-278fbfcf-a983-4020-a965-a45b3ecc9a2a.png)

* Minecraft version: [1.12.2]
* Single Player or Multi Player?: [Multi]
* Forge version: [14.23.5.2847]
* QuarryPlus version: [12.5.5]

**Comment by Kotori316** [comment]
See this thread in CurseForge.
https://www.curseforge.com/minecraft/mc-mods/additional-enchanted-miner?comment=199
