### ISSUE TITLE
Crashes game when combined with energy api

### ISSUE THREAD

**Issue by Kasax007** [Kotori316/QuarryPlus#146]
Sadly my game always crashes when your mod is combined with a mod that uses the Tech Reborn Energy API. Unfortunately, there are quite a few mods that do so. 
Energy API: https://github.com/TechReborn/Energy
[log of crash.txt](https://github.com/Kotori316/QuarryPlus/files/7497740/log.of.crash.txt)

I just thought I'd let you know of this issue so maybe in the future, I can combine your quarry mod with more tech mods in my mod pack.
 
Best regards
Kasax

**Comment by Kotori316** [comment]
Does this crash happen only when my quarry mod is added?
The log file said there was an exception of NBT tag(line: 1545), but I
don't come up with any ideas related with NBT tag.
In these days, I'm working to add new features to fabric version, so new
machines may create such a big NBT.

I want you to use other version of QuarryPlus. If 17.0.390(
https://www.curseforge.com/minecraft/mc-mods/additional-enchanted-miner/files/3478634)
works, something I added causes such crashes. If old version doesn't work,
I'll use debuggers to know why the crash happens.

2021年11月8日(月) 23:36 Kasax007 ***@***.***>:

**Comment by Kasax007** [comment]
I will try that out tomorrow! Thank you for the response. And yeah it only crashed when I tried to load into the world with QuarryPlus added. 
I will let you know if the older version works for me :D

**Comment by Kasax007** [comment]
Hey, 
I tried a bunch of the older versions of your mod but unfortunately none work. Don't know what else I could try.

**Comment by Kotori316** [comment]
Is it possible to remove ***@***.***?
This page(https://github.com/paulevsGitch/BetterNether/issues/411) has the
same issue and it seems removing the chipped, which adds so many blocks, is
a solution for this crash.

My mod says it conflicts with tech reborn energy , but it was my mistake,
so don't worry about it.

2021年11月10日(水) 21:19 Kasax007 ***@***.***>:

**Comment by Kotori316** [comment]
Opps. GitHub treated mod name + version as e-mail address and hide from my comment.
Try to remove chipped@1.1.1 (https://www.curseforge.com/minecraft/mc-mods/chipped).
I don't know the detail of the mod, but it may add lots of blocks and caused sync trouble.

**Comment by Kotori316** [comment]
Also, I want to ask you, which mod pack do you use?

**Comment by Kasax007** [comment]
It's my own custom mod pack which I release just a couple of days ago called "Dreamcraft" if you're curious or want to check out the mod list. 
Okay so I removed chipped from my test build and that allowed me to add ALL OF THE TECH MODS I WISHED BUT COULLDNT BEFORE!!! 
Thank you soo much. 
So finally I can add all the tech mods like your Quarry mod, Applied Energistics, Iron furnaces, Enhanced Quarries, Industrial Revolution and more. 
All just because of one mod "Chipped".
Actually insane that it doesn't show up properly in the logs.

Thanks a lot for your help. You solved all my tech problems :)
