### ISSUE TITLE
Quarry requires no energy

### ISSUE THREAD

**Issue by Myridium** [Kotori316/QuarryPlus#148]
The Quarry Plus does not stop mining even when it has no more energy connected.

Fabric 1.17.1

Edit:

After a couple of minutes it stopped. Looks like it consumes basically no energy (mod is OP) and it has a large internal buffer. When I hover over the item, the WTHIT tooltip at the top says it has 0 / infinity E. I see I can edit the energy requirement in the config if need be, thanks for including that.

**Comment by Kotori316** [comment]
The WTHIT tooltip is wrong. The machine has finite energy capacity, not infinity. It seems WTHIT gets information in wrong way. In recent version, I added own energy info to the tooltip.
As you noticed, you can edit the energy conversion rate from Tech Reborn Energy to Quarry energy.

But, I won't add config option to modify capacity and consumption of each machines in the future.

**Comment by Myridium** [comment]
@Kotori316 you pretty much _have_ to include configuration options for capacity and consumption if you want your mod to be included in balanced modpacks.

**Comment by Kotori316** [comment]
The energy configuration is now available in the latest release.

https://github.com/Kotori316/QuarryPlus/blob/7db80ca3c3c975145880189ed0f4bc36c5b7deeb/src/main/scala/com/yogpc/qp/QuarryConfig.java
