### ISSUE TITLE
Quarry doesnt mine below y=0

### ISSUE THREAD

**Issue by Kasax007** [Kotori316/QuarryPlus#149]
Hey,
While I was playtesting your mod I found out that some of the quarries like the enhanced one or the chunk buster don't mine below y=0 when using a mod that adds the 1.18 world generation. For some reason, the normal one does at least. 
Also, another question, are you supposed to be able to craft the chunk buster, or is that a creative only thing? 

Best regards,
Kasax007

**Comment by Kotori316** [comment]
The recipe for Chunk Destroyer is added in recent build. Try the latest
build.
Some months ago, I added code to dig under 0, but it doesn't seem working.
Can you use Y-Setter and select under 0?

Hey,

**Comment by Kasax007** [comment]
On the normal one which already goes below y=0 I could but I mean it already goes far enough down. And when I try and use it on the chunk buster it just opens the normal chunk buster interface and not the y setter. And when shift clicking to prevent the opening of the chunk buster interface it doesn't open the y setter interface. So you might have to disable to the opening of the chunk buster interface when the player is holding the y setter gadget.

**Comment by Kotori316** [comment]
Recent update for 1.17-fabric fixed this issue.
The Chunk Destroyer automatically detect the bottom of the world and Y Setter now works fine.
I uploaded 1.18 version of the mod (using almost same code as 1.17) and the quarries remove block under y=0.
