### ISSUE TITLE
Quarry Plus Ignores Waterlogged Blocks

### ISSUE THREAD

**Issue by JartanFTW** [Kotori316/QuarryPlus#150]
## Describe the bug

The quarry from Quarry Plus seems to ignore some blocks. I'm sure there are more, but a few of these that I have found include:
Prismarine Stairs
Prismarine Slabs
Stone Stairs
Stone Slabs

Also made a bug report on the modpack I am playing, see here: https://github.com/SmashingModsTogether/SMT-Issues/issues/16

## To Reproduce

1. Startup a Quarry Plus in an area with any of the above listed blocks.
2.  The quarry will ignore the listed blocks and not mine them.

## Versions

* Minecraft version: 1.16.5
* Single Player or Multi Player?: Multiplayer
* Forge version: 36.2.8
* QuarryPlus version: 16.1.9
* Other mods: See mods included in this modpack: https://www.curseforge.com/minecraft/modpacks/smashing-mods-together

## Crash report or logs

N/A

**Comment by Dark-Arcana** [comment]
So far as I can tell, there are no configuration options to determine which blocks will and won't be picked by the quarry. So that means I have no ability to fix this on the modpack side of things.

**Comment by Kotori316** [comment]
Thank you for reporting. This is a bug in my mod where quarry doesn't remove [waterlogged blocks](https://minecraft.fandom.com/wiki/Waterlogging) if they're in water. So it seems quarry ignores stairs.

**Comment by Dark-Arcana** [comment]
Oh interesting. My modpack is using a mod called Subterranean Wilderness that adds various decorative blocks to cave systems such as stairs, slabs, and others to make the caves look more interesting. There are also underwater cave systems added by another mod. So working together, they would create a variety of waterlogged blocks.

**Comment by Kotori316** [comment]
Released [v16.1.10](https://www.curseforge.com/minecraft/mc-mods/additional-enchanted-miner/files/3530250).
Please try it.

**Comment by Dark-Arcana** [comment]
Thanks for the fix. I will try it in the next update of my pack (next week).

**Comment by JartanFTW** [comment]
This fixed the issue, sorry for delay.
