### ISSUE TITLE
Crash with the newest Version

### ISSUE THREAD

**Issue by Kasax007** [Kotori316/QuarryPlus#151]
## Describe the bug

_What happened to you?_

When I updated the mod to the newest version to fix previous issues my game doesn't start anymore and just crashes instead. I, unfortunately, don't know how to read the crash logs perfectly so I can't figure out if it isn't compatible with another mod or if it's another issue. 

## Versions

* Minecraft version: [1.17.1 Fabric]
* Single Player or Multi Player?: [-]
* Forge version: [-]
* QuarryPlus version: [17.0.424]
* Other mods: [too many [Dreamcraft modpack]]

## Crash report or logs
https://pastebin.com/LgEEDA0s
If your Minecraft has crashed, please attach the crash report. Please use pastebin or just paste the report.

**Comment by Kotori316** [comment]
You're using old version of Fabric Loader.
I added some code that depends on new version of loader, so it crashed.

I removed new API call and released new version.

**Comment by Kasax007** [comment]
Thank you! I am sorry for all the bug reports and stuff :D
