### ISSUE TITLE
[1.18] Quarry Plus does not use energy

### ISSUE THREAD

**Issue by Khytwel** [Kotori316/QuarryPlus#154]
* Minecraft version: [1.18]
* Single Player or Multi Player?: [Both]
* QuarryPlus version: [v18.0.444]
* Other mods: [Tech Reborn, WTHIT]

Everything is said in the title, the quarry uses no energy and can therefore mine infinitely.

**Comment by Kotori316** [comment]
Fixed in the latest version. Thank you for reporting.
