### ISSUE TITLE
Game crashes after placing a MarkerPlus.

### ISSUE THREAD

**Issue by DanHCraft** [Kotori316/QuarryPlus#16]
I want to place down a MarkerPlus on a Sand and then the Game crashes with following Crash Report: https://gist.github.com/DanHCraft/7267acfca15d4513faf824ff9abb5d36#file-crash-2018-03-29_19-18-06-client-txt

**Comment by DanHCraft** [comment]
Sorry I found the problem by myself:
Sponge have not to be installed on the client.

**Comment by Kotori316** [comment]
Thank you for the crash report.
I found a problem that marker called ForgeChunkManager#requestTicket even in client world. [Code](https://github.com/Kotori316/QuarryPlus/blob/54d2616a3cf46a9fa971eea3cd971f6fc4236c66/src/main/scala/com/yogpc/qp/block/BlockMarker.java#L189)
Other machine don't call the method on client world. [Example](https://github.com/Kotori316/QuarryPlus/blob/54d2616a3cf46a9fa971eea3cd971f6fc4236c66/src/main/scala/com/yogpc/qp/block/BlockAdvPump.java#L95)

I inserted if(!world.isRemote) to check if server world or not in BlockMarker.java.

Do other block work fine without crash?
