### ISSUE TITLE
No enchantment with Anvil

### ISSUE THREAD

**Issue by AlexandrusConstantus** [Kotori316/QuarryPlus#162]
Minecraft: 1.18.1
Fabric: 0.12.12
QuarryPlus: AdditionalEnchantedMiner-1.18-fabric-18.1.0

Ingredients: Silk Touch Book, Anvil, Quarry, Enough Experience (Botte of enchant or whatever)
This does work in creative, but it does not work once one switched to survive or plays survive.
In Survival the anvil gives no feedback whatsoever. Experience is >20 levels.

**Comment by Kotori316** [comment]
Fixed in the latest version.

Note:
You can only move enchantments from Enchantment Book to machines. You CAN'T move enchantments in a machine to other one.

**Comment by AlexandrusConstantus** [comment]
This i saw, but it was really just the book case. Thanks a lot:-)

**Comment by WolfTM** [comment]
Minecraft: 1.21.1
Fabric: 0.16.9
QuarryPlus: AdditionalEnchantedMiner-1.21.1-fabric-21.1.115

This issue has re-appeared in 1.21.1 Fabric.
Works in creative, but in survival mode the anvil gives nothing.
