### ISSUE TITLE
chunk Destroyer voiding items

### ISSUE THREAD

**Issue by jaront2008** [Kotori316/QuarryPlus#163]
## Describe the bug

_What happened to you?_

I tried it with a chanted and non Enchanted chunk Destroyer it keeps voiding grass dirt, Stone a lot of common items. I don't know if this is a bug or feature if it's a feature can you make it so you can turn it off?

## Versions

* Minecraft version: 1.18.1
* Single Player 
* Forge version: 39.0.9
* QuarryPlus version:1.18.1

**Comment by Kotori316** [comment]
It's intended.

I'll create config option to avoid more complaints about this. #164
