### ISSUE TITLE
maxEnergy multiplied by ONE_FE twice

### ISSUE THREAD

**Issue by RogueLogix** [Kotori316/QuarryPlus#166]
when setting the max energy for a quarry, your config system multiplies by ONE_FE to translate it into your internal units, it is then multiplied by that again before setting the buffer size.
with the default config value of 1000, this results in a positive number after the rollover, however with other numbers such as 7000, you get a negative number after rollover

related, this causes the receiveEnergy function to return a number larger than the argument given to it, there should probably be a better bounds check on that

* Minecraft version: 1.18.1
* QuarryPlus version: 18.4

**Comment by Kotori316** [comment]
Fixed in v18.5
Thank you for reporting.
