### ISSUE TITLE
MarkerPlus disappearance

### ISSUE THREAD

**Issue by ItzCony** [Kotori316/QuarryPlus#169]
## Describe the bug

_What happened to you?_
When marker plus placed and activate with redstone torch or lever, he dissapear after few blocks and doesnt show blue line for size marking. 
## To Reproduce

1. 
2. 
3. 

If your server/client has crashed, please give me the crash report.

## Versions

* Minecraft version: [1.12.2]
* Single Player or Multi Player?: [Multiplayer]
* Forge version: [14.23.5.2860]
* QuarryPlus version: [12.5.5]
* Other mods: [https://imgur.com/a/i4kno3w]

## Crash report or logs

If your Minecraft has crashed, please attach the crash report. Please use pastebin or just paste the report.

**Comment by Kotori316** [comment]
Sorry, but it can't be fixed due to some technical issue.
Please update to v12.5.6 because I did some changes to re-generate laser if you get closer to Marker.
