### ISSUE TITLE
Can't insert into filler with hopper [Fabric]

### ISSUE THREAD

**Issue by blake-lowe** [Kotori316/QuarryPlus#175]
## Describe the bug

FABRIC QuarryPlus
I can insert items into a filler by hand but I am unable to insert items in the Filler with a hopper. I would expect to be able to provide the filler with items in an automated way.
I read in the changelogs that the QuarryPlus was fixed to not allow items to be inserted. Maybe this is related because the filler is a modified quarry? Just speculating. Thank you! 

## To Reproduce

1. Place a filler (doesn't matter if marker zone is set or not)
2. Place an adjacent hopper pointed to the filler
3. Place items in the hopper

## Versions

* Minecraft version: [1.18.2]
* Single Player or Multi Player?: [Single Player]
* Fabric Version: [0.13.3]
* QuarryPlus version: [AdditionalEnchantedMiner-1.18.2-18.8]
* Other mods: [Not relevant, but can provide]

**Comment by Kotori316** [comment]
I seems that I completely forgot registering Filler as a container.

I'll fix tonight.

**Comment by Kotori316** [comment]
I'm sorry I forgot commenting in this issue.
Fixed in the latest version.
