### ISSUE TITLE
Workbench Plus Bug 1.12.2

### ISSUE THREAD

**Issue by Ermen07** [Kotori316/QuarryPlus#18]
When i try to craft a quarry plus in a workbench it gives me a miningwell plus or when i try to craft something I want gives me something else and the loading bar is unsynced and sometimes disappear.
I'm playing in a server.

Version: AdditionalEnchantedMiner-1.12.2-0.8.8-universal

Screenshot: 
http://prntscr.com/jgnvct
http://prntscr.com/jgnw4g

**Comment by Kotori316** [comment]
Thank you for your report. I found some problems in WorkbenchPlus and packet system. This bug happens only in dedicated server.


I'm fixing this problem but it takes some days.

**Comment by Kotori316** [comment]
I uploaded new version 0.8.9.

I hope it fixes this problem but this fix may cause new bugs...
Vanilla packet can't send itemstack whose size is over 128. I changed my code not to use vanilla packet.

**Comment by Ermen07** [comment]
Thank you! I will try later.

**Comment by Ermen07** [comment]
I tried, it works but the progress bar is still bugged. The progress bar doesn't bug with marker plus.

**Comment by Kotori316** [comment]
I found the amount of energy is not sent to client and the data is overflowed.
I'll fix.

**Comment by Kotori316** [comment]
New version 0.9.0 is available.

I found that "NoEnergy" in config is very useful for debugging but it hides some problems.

Anyway, I fixed the bug of progress bar, but if your config file (in client) does not match one in server, the progress bar doesn't work. You can change config via Game Menu -> Mod Options -> (type q and find QuarryPlus) -> Config.

**Comment by Ermen07** [comment]
Perfect, thank you very much.
