### ISSUE TITLE
Latest Alpha Incompatible with Levelz

### ISSUE THREAD

**Issue by Loyal0713** [Kotori316/QuarryPlus#184]
## Describe the bug

Unable to successfully mine in-game with Levelz and Additional Enchanted Miner enabled

## To Reproduce

1. Install Valhelsia Enhanced Vanilla 1.2.0-pre3 (or plain install with just AEM and Levelz)
2. Update AEM to latest
3. Try to mine stone with 4+ levels in mining (Levelz)

If your server/client has crashed, please give me the crash report.

## Versions

* Minecraft version: 1.18.2
* Single Player or Multi Player?: Single
* QuarryPlus version: v18.3.549
* Other mods: Valhelsia modpack, Levelz in particular

## Crash report or logs

No crash/logs

**Comment by Kotori316** [comment]
Does this problem happen with old version? How about latest [beta](https://www.curseforge.com/minecraft/mc-mods/additional-enchanted-miner/files/3764562)?

**Comment by Kotori316** [comment]
OK, I got some hints for this bug. I did something wrong in setting the mining level.

**Comment by Kotori316** [comment]
I pushed to GitHub and a new alpha version will be available in some minutes.

**Comment by Loyal0713** [comment]
Thanks, I appreciate the quick work!

**Comment by Kotori316** [comment]
I published [new version](https://www.curseforge.com/minecraft/mc-mods/additional-enchanted-miner/files/3770297) as beta. Just a moment, please.

**Comment by Kotori316** [comment]
The new version works fine.
