### ISSUE TITLE
Workbench Plus automation

### ISSUE THREAD

**Issue by gamenTV** [Kotori316/QuarryPlus#186]
It would be nice if you could automate the Workebench Plus by setting a recipe.

**Comment by Kotori316** [comment]
See https://github.com/Kotori316/QuarryPlus/wiki/WorkbenchPlus#tips

I won't implement another way to automate crafting because I don't have any idea to set recipe without player interaction.

**Comment by SillyBits** [comment]
Sorry for re-opening this old issue, but what about just remembering last recipe which was double-clicked (gained a yellow marker instead of green)? Visualization could be done by simple rendering a ghost, a faded-out item icon sort-of
