### ISSUE TITLE
Quarries currently do not respect FTB claims

### ISSUE THREAD

**Issue by jpwanabe** [Kotori316/QuarryPlus#190]
## Describe the bug

The quarry currently does not respect FTB claimed chunks. Anyone can set a quarry up just out side a claim or surrounding it and mine someone's entire claimed area, or use the chunk deleter and remove everything.

## To Reproduce

1. Have a fellow player claim an area
2. Set up a quarry just out side the claim with the area to be dug inside the claim
3. Turn it on and watch the claim get mined out

If your server/client has crashed, please give me the crash report.
n/a
## Versions

* Minecraft version: 1.18.2
* Single Player or Multi Player?: Multi
* Forge version: 40.1.20
* QuarryPlus version: AdditionalEnchantedMiner-1.18.2-18.11
* Other mods: ATM7 mod pack version 0.4.3

## Crash report or logs
n/a

**Comment by Kotori316** [comment]
It's intended. Is there any mod that respect claimed chunks in quarry work?
But, I should have some options to respect such settings.

2022年5月25日(水) 22:58 jpwanabe ***@***.***>:

**Comment by jpwanabe** [comment]
I know that RFtools Builder respects claims as well as the Mekanism Digiminer. As for others, I am not sure. But the fact that this can be used to ERASE a base with a tiny bit of set up time, less then 5 min, is an issue that I really think should be addressed. 3 markers around a claim, 1 quarry and a solar panel and a base will get destroyed down to bedrock before the ower of the claim could find the block. With the power of that block, it really should respect claims.

**Comment by Kotori316** [comment]
OK. Give me more detail of mods you have installed. I want to know the exact version and file name of FTB mods. The have a lot of mods to support modded world, but I don't know which one presents the chunk protection.

**Comment by jpwanabe** [comment]
The full list of mods is too large to put here, but the FTB mods, with versions, are as follows.

ftbbackups2-forge-1.18.2-1.0.5.jar
ftb-chunks-forge-1802.3.6-build.145.jar
ftb-essentials-1802.1.7-build.42.jar
ftb-industrial-contraptions-1802.1.4-build.141.jar
ftb-library-forge-1802.3.6-build.119.jar
ftb-quests-forge-1802.3.8-build.101.jar
ftb-teams-forge-1802.2.6-build.51.jar
ftb-ranks-forge-1802.1.7-build.27.jar
ftb-ultimine-forge-1802.3.3-build.55.jar

The full list can be found here.
https://www.curseforge.com/minecraft/modpacks/all-the-mods-7/files/3802141

**Comment by Kotori316** [comment]
OK. Thank you. I'll start working for this issue.
