### ISSUE TITLE
[1.19 fabric] Some recipes are wrong, unable to craft

### ISSUE THREAD

**Issue by Kotori316** [Kotori316/QuarryPlus#194]
In 1.19, the recipe of Marker Plus is removed. So some recipes which use Marker Plus as ingredients are not working.

* Status Checker
* Y-Setter
* Bedrock Module
* Advanced Pump

These recipe should accept all types of Markers including Flexible Marker and Chunk Marker.

**Comment by Adzeiros** [comment]
JUST an FYI both the Flexible Marker and the Chunk Marker require the Marker Plus to craft... Thus those are impossible to craft as well.
