### ISSUE TITLE
[1.19-Forge] Crash viewing JEI integrated recipes.

### ISSUE THREAD

**Issue by Gbergz** [Kotori316/QuarryPlus#198]
## Describe the bug

Crash viewing quarryplus's JEI integrated recipes.

## To Reproduce

1. Look at a recipe from your mods in JEI. (workbench)
2. Crash
3. profit

If your server/client has crashed, please give me the crash report.

## Versions

* Minecraft version: 1.19
* Single Player or Multi Player?: Singleplayer
* Forge version: 41.0.35
* QuarryPlus version: 1.19-19.0.jar
* Other mods: Clean install and with mods

## Crash report or logs
https://gist.github.com/Gbergz/e2dc51ca612a4b6e4055cbbe1d96bc74

**Comment by Kotori316** [comment]
Wait. I'll release new version. I already have fixed the code.

https://www.curseforge.com/minecraft/mc-mods/additional-enchanted-miner/files/3836145
