### ISSUE TITLE
add liquid selector to chunk destroyer [enhancement]

### ISSUE THREAD

**Issue by quentfr21** [Kotori316/QuarryPlus#20]
hello

can you add the gui to the chunk destoyer like quarry with pump by using the bucket selector or a new button and add bucket selector to the recipe of chunk destroyer

thanks for the reborn and all new features

**Comment by Kotori316** [comment]
Added in 0.9.3.

Right click the machine to open GUI, then Add(From List) and choose fluid to extract.
The list has fluid only stored in the machine.
This setting is saved for each side.

**Comment by quentfr21** [comment]
thanks a lot
