### ISSUE TITLE
[1.12.2] The Workbench Plus interface third row cannot display ingredients if there are more than 18 ingredients.

### ISSUE THREAD

**Issue by ripley2459** [Kotori316/QuarryPlus#200]
## Describe the bug

The Workbench Plus interface third row cannot display ingredients if there are more than 18 ingredients.
Bug occur in the Workbench Plus interface and in JEI's recipe viewer interface.
The recipe need hidden ingredients to work so it's only a bug with the display.

![workbench-interface-working](https://user-images.githubusercontent.com/38365539/175820215-32249fba-467e-4c94-b17c-53df6cbd02aa.png)
![jei-recipe-viewer](https://user-images.githubusercontent.com/38365539/175820218-066f889d-ebcf-49d7-bec5-4784020e80be.png)
![ct-recipe](https://user-images.githubusercontent.com/38365539/175820216-3572e666-0c05-4024-a225-349dd16fe302.png)

json file in 'config/quarryplus/recipes" folder:
`{
  "id": "newelysium:transmutation_table_workbench",
  "type": "quarryplus:workbench_recipe",
  "ingredients": [
    {
      "item": "appliedenergistics2:condenser",
      "data": 0,
      "count": 1
    },
    {
      "item": "appliedenergistics2:controller",
      "data": 0,
      "count": 4
    },
    {
      "item": "appliedenergistics2:crafting_storage_64k",
      "data": 0,
      "count": 16
    },
    {
      "item": "appliedenergistics2:energy_acceptor",
      "data": 0,
      "count": 2
    },
    {
      "item": "appliedenergistics2:molecular_assembler",
      "data": 0,
      "count": 2
    },
    {
      "item": "appliedenergistics2:sky_stone_block",
      "data": 0,
      "count": 85
    },
    {
      "item": "avaritia:block_resource",
      "data": 2,
      "count": 12
    },
    {
      "item": "avaritia:block_resource",
      "data": 0,
      "count": 48
    },
    {
      "item": "contenttweaker:alchemical_core",
      "data": 0,
      "count": 24
    },
    {
      "item": "contenttweaker:cryogenized_myrmex_resine",
      "data": 0,
      "count": 24
    },
    {
      "item": "contenttweaker:matter_interface",
      "data": 0,
      "count": 1
    },
    {
      "item": "contenttweaker:me_covalence_cable",
      "data": 0,
      "count": 8
    },
    {
      "item": "draconicevolution:draconium_block",
      "data": 0,
      "count": 28
    },
    {
      "item": "draconicevolution:particle_generator",
      "data": 2,
      "count": 8
    },
    {
      "item": "fluxnetworks:fluxblock",
      "data": 0,
      "count": 64
    },
    {
      "item": "nuclearcraft:lithium_ion_battery_elite",
      "data": 0,
      "count": 16
    },
    {
      "item": "plustic:alumiteblock",
      "data": 0,
      "count": 12
    },
    {
      "item": "projecte:matter_block",
      "data": 0,
      "count": 132
    },
    {
      "item": "thermaldynamics:duct_0",
      "data": 5,
      "count": 8
    },
    {
      "item": "thermalfoundation:storage_alloy",
      "data": 7,
      "count": 12
    }
  ],
  "energy": 10000000.0,
  "showInJEI": true,
  "result": {
    "item": "projecte:transmutation_table",
    "data": 0,
    "count": 1
  }
}`

## To Reproduce

Create a recipe that have more than 18 ingredients. (Tested with CraftTweaker and the JSON in config folder.)

## Versions

* Minecraft version: [1.12.2]
* Single Player or Multi Player?: [singleplayer]
* Forge version: [14.23.5.2860]
* QuarryPlus version: [1.12.2-12.5.6]

**Comment by Kotori316** [comment]
Fixed in [v12.5.7](https://www.curseforge.com/minecraft/mc-mods/additional-enchanted-miner/files/3851282)

Thank you for your report.
