### ISSUE TITLE
Solid Fuel Quarry not mining Obsidian

### ISSUE THREAD

**Issue by Greg9711** [Kotori316/QuarryPlus#201]
1.18.2
AdditionalEnchantedMiner-1.18.2-18.12
Direwolf20 1.18 Modpack with this Mod added (and the Library Mod)

Like it says in the Title the Solid Fuel Quarry doesn´t mine Obsidian (Quarry Plus does)
If this is intendet so you can´t get a lot of Obsidian just from that, then it could just void it or ignore it and keep going, because it just stopps and i would have to move it (or mine it myself). It doesn´t say it on the Wiki that it can#t mine it, so i just wanted to ask/make sure.

**Comment by Kotori316** [comment]
It seems that the quarry requires more energy than its capacity (energy to remove Obsidian: 1250, capacity: 1000).
I'll fix in a few days.
