### ISSUE TITLE
Compat Issues with Tech Reborn

### ISSUE THREAD

**Issue by LukeC97** [Kotori316/QuarryPlus#203]
## Describe the bug

The internal server crashes when trying to place Tech Reborn machines, generators and storage units, using the Remote Placer block. Possibly due to all data tags tied to the block. 

## To Reproduce

1.  Place Remote Placer in world
2. Put Tech Reborn crude storage unit in the placer's GUI
3. Activate Placer with Redstone (i.e Lever)

If your server/client has crashed, please give me the crash report.

## Versions

* Minecraft version: 1.18.2
* Single Player or Multi Player?: Single Player
* Forge version: N/A
* Fabric Version: 0.13+
* QuarryPlus version: 18.4.573
* Other mods: Valhelsia Enhanced Vanilla modpack

## Crash report or logs

If your Minecraft has crashed, please attach the crash report. Please use pastebin or just paste the report.

<details>
<summary>Report</summary>
---- Minecraft Crash Report ----

// There are four lights!

Time: 7/22/22, 11:28 PM
Description: Exception ticking world

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1309.method_5735()" because "placer" is null
	at reborncore.common.blocks.BlockMachineBase.onPlaced(BlockMachineBase.java:123)
	at net.minecraft.item.BlockItem.place(BlockItem:90)
	at com.yogpc.qp.machines.placer.PlacerTile.isItemPlaceable(PlacerTile.java:164)
	at com.yogpc.qp.machines.placer.PlacerTile.lambda$placeBlock$2(PlacerTile.java:126)
	at com.yogpc.qp.machines.placer.PlacerTile.findEntryInternal(PlacerTile.java:148)
	at com.yogpc.qp.machines.placer.PlacerTile.findEntry(PlacerTile.java:143)
	at com.yogpc.qp.machines.placer.PlacerTile.placeBlock(PlacerTile.java:125)
	at com.yogpc.qp.machines.placer.RemotePlacerBlock.lambda$tick$3(RemotePlacerBlock.java:105)
	at java.util.Optional.ifPresent(Optional.java:178)
	at com.yogpc.qp.machines.placer.RemotePlacerBlock.scheduledTick(RemotePlacerBlock.java:103)
	at net.minecraft.block.AbstractBlock$AbstractBlockState.scheduledTick(AbstractBlock:919)
	at net.minecraft.server.world.ServerWorld.tickBlock(ServerWorld:691)
	at net.minecraft.world.tick.WorldTickScheduler.tick(WorldTickScheduler:215)
	at net.minecraft.world.tick.WorldTickScheduler.tick(WorldTickScheduler:98)
	at net.minecraft.server.world.ServerWorld.tick(ServerWorld:301)
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:907)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer:851)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer:97)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:273)
	at java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at reborncore.common.blocks.BlockMachineBase.method_9567(BlockMachineBase.java:123)
	at net.minecraft.class_1747.method_7712(class_1747.java:90)
	at com.yogpc.qp.machines.placer.PlacerTile.isItemPlaceable(PlacerTile.java:164)
	at com.yogpc.qp.machines.placer.PlacerTile.lambda$placeBlock$2(PlacerTile.java:126)
	at com.yogpc.qp.machines.placer.PlacerTile.findEntryInternal(PlacerTile.java:148)
	at com.yogpc.qp.machines.placer.PlacerTile.findEntry(PlacerTile.java:143)
	at com.yogpc.qp.machines.placer.PlacerTile.placeBlock(PlacerTile.java:125)
	at com.yogpc.qp.machines.placer.RemotePlacerBlock.lambda$tick$3(RemotePlacerBlock.java:105)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at com.yogpc.qp.machines.placer.RemotePlacerBlock.method_9588(RemotePlacerBlock.java:103)
	at net.minecraft.class_4970$class_4971.method_26192(class_4970.java:919)
	at net.minecraft.class_3218.method_14189(class_3218.java:691)
	at net.minecraft.class_6757.method_39390(class_6757.java:215)
	at net.minecraft.class_6757.method_39377(class_6757.java:98)
	at net.minecraft.class_3218.method_18765(class_3218.java:301)

-- Affected level --
Details:
	All players: 1 total; [class_3222['AMPBEAST66'/3877, l='ServerWorld minecraft:the_nether Creative World', x=-4.07, y=128.00, z=-6.97]]
	Chunk stats: 2401
	Level dimension: minecraft:the_nether
	Derived: true
	Level spawn location: World: (0,56,0), Section: (at 0,8,0 in 0,3,0; chunk contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 577634 game time, 1155 day time
	Level name: Creative World
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 1189 (now: true), thunder time: 54599 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:907)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:851)
	at net.minecraft.class_1132.method_3748(class_1132.java:97)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 3642294808 bytes (3473 MiB) / 8388608000 bytes (8000 MiB) up to 8388608000 bytes (8000 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 10
	Microarchitecture: unknown
	Frequency (GHz): 2.59
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: Intel(R) UHD Graphics 630
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x3e9b
	Graphics card #0 versionInfo: DriverVersion=27.20.100.8935
	Graphics card #1 name: NVIDIA GeForce GTX 1660 Ti with Max-Q Design
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 4095.00
	Graphics card #1 deviceId: 0x2191
	Graphics card #1 versionInfo: DriverVersion=31.0.15.1640
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 37442.02
	Virtual memory used (MB): 27714.74
	Swap memory total (MB): 4864.00
	Swap memory used (MB): 38.55
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8000m -Xms256m -Xms8000m
	Fabric Mods: 
		additionaladditions: Additional Additions 4.0.5
		advanced_runtime_resource_pack: Runtime Resource Pack 0.5.7
		advancementinfo: AdvancementInfo 1.18.2-fabric0.47.10-1.3.1
		advancementplaques: Advancement Plaques 1.4.5
		advancementscreenshot-fabric: Advancement Screenshot (Fabric) 3.2
		advdebug: Advancements Debug 2.3.0
		adventurez: AdventureZ 1.4.11
		ae2: Applied Energistics 2 11.1.4
			noindium: No Indium? 1.0.2+1.18.2
				omega-config: OmegaConfig 1.2.3-1.18.1
		ambientenvironment: Ambient Environment 7.0+19
		ambientsounds: Ambiend Sounds (Fabric) 5.0.16
		anchor: Anchor 1.1.0
		animal_feeding_trough: Animal Feeding Trough 1.0.3+1.18.2
		appleskin: AppleSkin 2.4.0+mc1.18.2
		arcanus: Arcanus 1.29
		architects_palette: Architect's Palette Fabric 2.2
		architectury: Architectury 4.5.76
		artifacts: Artifacts 7.0.3+fabric
			step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		attributefix: AttributeFix 14.0.2
		authme: Auth Me 3.1.0
		badpackets: Bad Packets 0.1.2
		balm-fabric: Balm 3.1.0+0
		bcc: BetterCompatibilityChecker fabric-1.0.5
		bclib: BCLib 1.4.7
		beaconoverhaul: Beacon Overhaul 1.6.0+1.18.2
			reach-entity-attributes: Reach Entity Attributes 2.1.1
		bedspreads: Bedspreads 1.6.0-1.18
		betterdungeons: YUNG's Better Dungeons 1.18.2-Fabric-2.1.0
		betterend: Better End 1.1.1
		betterf3: BetterF3 1.2.5
		betterfpsdist: Better FPS distance Mod 1.18-1.8
		bettermounthud: Better Mount HUD 1.1.4
		betterpingdisplay: Better Ping Display 1.1.1
		betterstrongholds: YUNG's Better Strongholds 1.18.2-Fabric-2.1.1
		bhmenu: BHMenu-Fabric 1.17.1-1.18.2-1.3
		blockus: Blockus 2.4.7+1.18.2
			terraform-wood-api-v1: Terraform Wood API (v1) 3.0.0
		blossom: Blossom 1.18.2-1.0.4
		bookshelf: Bookshelf 13.2.21
		capybara: Capybara 1.0.6
		carrier: Carrier 1.10.0
		ce: Cave Enhancements 1.1.5
		chalk: Chalk 2.0.1+1.18.2
		chat_heads: Chat Heads 0.6.0
		cherishedworlds: Cherished Worlds 2.0.2-1.18
		chiselsandbits: Chisels & Bits 1.2.113
		chunky: Chunky 1.2.164
		citresewn: CIT Resewn 1.1.1+1.18.2
			citresewn-defaults: CIT Resewn: Defaults 1.1.1+1.18.2
		cleancut: CleanCut 1.18.2-5.0-fabric
		cleardespawn: Clear Despawn 1.1.7
		clickadv: Clickable Advancements Mod 2.6
		cloth-api: Cloth API 3.2.64
			cloth-client-events-v0: Cloth Client Events v0 3.2.64
			cloth-common-events-v1: Cloth Common Events v1 3.2.64
			cloth-datagen-api-v1: Cloth Datagen v1 3.2.64
			cloth-scissors-api-v1: Cloth Scissors API v1 3.2.64
			cloth-utils-v1: Cloth Utils v1 3.2.64
		cloth-config: Cloth Config v6 6.2.62
			cloth-basic-math: cloth-basic-math 0.6.1
		collective-fabric: Collective (Fabric) 4.27
			fiber: fiber 0.23.0-2
		comforts: Comforts 1.1.2-1.18.2
			cardinal-components-base: Cardinal Components API (base) 4.1.4
			cardinal-components-entity: Cardinal Components API (entities) 4.1.4
		companion: Companion 2.0.1
		connectiblechains: Connectible Chains 2.1.1+1.18.2
		continuity: Continuity 2.0.0+1.18.2
		controlling: Controlling For Fabric 9.0+21
		copper_pipe: Simple Copper Pipes r1.9
		couplings: Couplings 1.8.0+1.18.2
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
		craftingtweaks: Crafting Tweaks 14.0.3
		crawl: Crawl 0.10.6
			mm: Manningham Mills 2.3
		create: Create mc1.18.2_v0.4.1+637
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			fake-player-api: Fake Player API 0.3.0
			flywheel: Flywheel 1.18-0.7.0.26
			forge_tags: Forge Tags 2.1
			milk: Milk Lib 0.3.2
				dripstone_fluid_lib: Dripstone Fluid Lib 1.2.0
			porting_lib: Porting Lib 1.1.317-beta+1.18.2-dev.7ad1f24
				com_github_llamalad7_mixinextras: MixinExtras 0.0.10
				serialization_hooks: Serialization Hooks 0.2.0+1.18.f5d4aa6
			registrate-fabric: Registrate for Fabric MC1.18.2-1.0.3
		creativecore: CreativeCore (Fabric) 2.6.12
		creeperoverhaul: Creeper Overhaul 1.3.1
		customstars: Custom Stars 1.1+1.18.2
		decorative_blocks: Decorative Blocks 2.1.0
		detailab: Detail Armor Bar 2.6.2+1.18-fabric
		dragonloot: DragonLoot 1.1.0
		dual_riders: Dual Riders 1.1.1
		dusk: Dusk Mod 1.18.2-2.1
		dyed: Dyed 1.0.2
		dynamicfps: Dynamic FPS 2.1.0
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		eatinganimationid: Eating Animation 1.8
		ecologics: Ecologics 1.7.4
		enchantedtooltips: Enchanted ToolTips 1.3.6-1.18
			kyrptconfig: Kyrpt Config 1.4.5-1.18
				blue_endless_jankson: jankson 1.2.1
		enderscape: Enderscape 0.3.4-1.18.2
		enhanced_mushrooms: Enhanced Mushrooms 4.0.1
		entityculling: EntityCulling-Fabric 1.5.1
		equipmentcompare: Equipment Compare 1.2.12
		expandability: ExpandAbility 6.0.0
		fabric: Fabric API 0.57.0+1.18.2
			fabric-api-base: Fabric API Base 0.4.4+d7c144a860
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.2+2373a54560
			fabric-biome-api-v1: Fabric Biome API (v1) 8.0.6+651bcc5960
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.12+3ac43d9560
			fabric-command-api-v1: Fabric Command API (v1) 1.1.9+d7c144a860
			fabric-commands-v0: Fabric Commands (v0) 0.2.8+b4f4f6cd60
			fabric-containers-v0: Fabric Containers (v0) 0.1.22+d7c144a860
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.1.1+c85f2e3860
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.1+474e4f7960
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.1+ee261a3e60
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 3.0.0+9fcb91d260
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.20+489d6f8260
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.8+d7c144a860
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.19+d7c144a860
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.18+d7c144a860
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.13+d7c144a860
			fabric-item-api-v1: Fabric Item API (v1) 1.5.1+6c4e5d0960
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.14+91896a4960
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.12+54e5b2ec60
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.10+b4f4f6cd60
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.0+cc71601c60
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.0+1997ad1260
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.2+e747827960
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.4+cc71601c60
			fabric-models-v0: Fabric Models (v0) 0.3.6+d7c144a860
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.22+e6b169eb60
			fabric-networking-v0: Fabric Networking (v0) 0.3.9+b4f4f6cd60
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.1.3+032c981d60
			fabric-particles-v1: Fabric Particles (v1) 0.2.12+526dc1ac60
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.9+0d9ab37260
			fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.13+d882b91560
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.5.2+d005b03a60
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.11+b4f4f6cd60
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.7+d7c144a860
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.2+54e5b2ec60
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.13+b4f4f6cd60
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.7+54e5b2ec60
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.3+91b7aa6660
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.2+446e059560
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.10+d882b91560
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.1+1f6558e860
			fabric-textures-v0: Fabric Textures (v0) 1.0.12+3ac43d9560
			fabric-transfer-api-v1: Fabric Transfer API (v1) 1.6.3+f4563ac860
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.0+e747827960
		fabric-language-kotlin: Fabric Language Kotlin 1.8.2+kotlin.1.7.10
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.10
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.2
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.3
		fabric-language-scala: Fabric Language Scala 1.1.0+scala.2.13.6
		fabricloader: Fabric Loader 0.14.8
		fallingleaves: Falling Leaves 1.11.1+1.18.2
		fallingtree: FallingTree 3.5.3
		fancymenu: FancyMenu 2.11.1
		farmersdelight: Farmer's Delight 1.18.2-0.2.1
		farsight: Farsight Mod 1.18-1.9
		fastbench: FastBench 1.18.1-3
		feature_nbt_deadlock_be_gone: Feature NBT Deadlock Be Gone - Fabric 2.0.0+1.18.2-rc1
		ferritecore: FerriteCore 4.2.1
		flytre_lib: FlytreLib 1.8.1
		forgeconfigapiport: Forge Config API Port 3.2.0
		friendlyfire: FriendlyFire 11.0.2
		geckolib3: Geckolib 3.0.51
			com_eliotlash_mclib_mclib: mclib 18
			com_eliotlash_molang_molang: molang 18
		goblintraders: Goblin Traders 1.5.1
		guardvillagers: Guard Villagers Fabric 1.18.2-1.0.14
		harvest_scythes: Harvest Scythes 2.5.1
		iceberg: Iceberg 1.0.38
		illuminations: Illuminations 1.10.4
		immersive_portals: Immersive Portals 1.4.8
			imm_ptl_core: Immersive Portals Core 1.4.8
			q_misc_util: QMiscUtil 1.4.8
		immersive_weathering: Immersive Weathering 2.5.6
		incantationem: Incantationem 1.1.3+1.18.2
		indium: Indium 1.0.6+mc1.18.2
		infusion_table: Infusion Table 1.1.0
		inventoryhud: Inventory HUD + 3.4.2
		iris: Iris 1.2.5
			org_anarres_jcpp: jcpp 1.4.14
		ironchests: Iron Chests 1.7.4
			libgui: LibGui 5.4.2+1.18.2
				jankson: Jankson 4.0.0+j1.2.0
				libninepatch: LibNinePatch 1.1.0
		java: OpenJDK 64-Bit Server VM 17
		kleeslabs: KleeSlabs 11.1.1
		konkrete: Konkrete 1.4.0
		krypton: Krypton 0.1.9
			com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		kubejs: KubeJS 1802.5.4-build.524
		lapisreserve: Lapis Reserve 1.0.8
		lazydfu: LazyDFU 0.1.2
		legendarytooltips: Legendary Tooltips 1.2.5
		levelz: LevelZ 1.3.3
		lithium: Lithium 0.7.10
		locksmith: Locksmith 1.0.3
		logprot: Logprot Mod 1.18-1.6
		lovely_snails: Lovely Snails 1.0.4+1.18
		mannequins: Mannequins 2.1.0
		megane: megane 7.8.0
			megane-api: megane-api 7.8.0
			megane-applied-energistics-2: megane-applied-energistics-2 7.8.0
			megane-create: megane-create 7.8.0
			megane-fabric-transfer: megane-fabric-transfer 7.8.0
			megane-reborn-core: megane-reborn-core 7.8.0
			megane-reborn-energy: megane-reborn-energy 7.8.0
			megane-runtime: megane-runtime 7.8.0
			megane-tech-reborn: megane-tech-reborn 7.8.0
			megane-vanilla: megane-vanilla 7.8.0
		minecraft: Minecraft 1.18.2
		mo_glass: Mo Glass 1.6.1-MC1.18.2
		mobscarecrow: Mob Scarecrow 2.1.1
		modmenu: Mod Menu 3.2.3
		mousetweaks: Mouse Tweaks 2.22
		mousewheelie: Mouse Wheelie 1.10.2+mc1.18.2
			amecsapi: Amecs API 1.3.6+mc22w06a
			coat: Coat 1.0.0-beta.18+mc1.18.2
			tweed4_annotated: tweed4_annotated 1.3.0+mc1.18.2
			tweed4_base: tweed4_base 1.5.0+mc1.18.2
			tweed4_data: tweed4_data 1.2.1+mc1.18.2
			tweed4_data_hjson: tweed4_data_hjson 1.1.0+mc1.18.2
			tweed4_tailor_coat: tweed4_tailor_coat 1.1.2+mc1.18.2
			tweed4_tailor_screen: tweed4_tailor_screen 1.1.1+mc1.18.2
		nears: Nears 1.1.8
		notenoughanimations: NotEnoughAnimations 1.6.0
		notenoughcrashes: Not Enough Crashes 4.1.6+1.18.2
		notes: Notes 1.0.10
		owo: oωo 0.7.2-no-cme+1.18
		oxidized: Oxidized 1.6.4
		paintings: Paintings++ 9.1.2.1
		patchouli: Patchouli 1.18.2-71.1-FABRIC
		pipe: Pipe 1.6.3
		pistorder: Pistorder 1.5.0
		pollen: Pollen 1.4.6
		polymorph: Polymorph 0.0.21-1.18.2
			cardinal-components-block: Cardinal Components API (blocks) 4.1.4
			cardinal-components-item: Cardinal Components API (items) 4.1.4
		presencefootsteps: Presence Footsteps 1.5.1
			kirin: Kirin UI 1.10.0
		publicguiannouncement: Public Gui Announcement 3.2.0.1
		pyrotastic: Pyrotastic 1.18.2+0.0.2
		quarryplus: QuarryPlus 18.4.573
		quartzelv: Quartz Elevator 2.1.2+1.18.2
		raised: Raised 1.1.2
		reborncore: Reborn Core 5.2.0
			team_reborn_energy: Energy 2.2.0
		reeses-sodium-options: Reese's Sodium Options 1.4.4+mc1.18.2-build.46
		replanter: Replanter 1.3
		rhino: Rhino 1802.1.14-build.204
		roughlyenoughitems: Roughly Enough Items 8.3.510
		rpgdifficulty: Rpg Difficulty 1.0.12
		seedfix: Seed Fix 1.0.1
		simple-rpc: Simple RPC 3.0.1
			me_hypherionmc_simple-rpc-common: simple-rpc-common 3.0.1
		sodium: Sodium 0.4.1+build.15
			org_joml_joml: joml 1.10.2
		sodium-extra: Sodium Extra 0.4.5+mc1.18.2-build.42
			caffeineconfig: CaffeineConfig 1.1.0
		someforgepatchesported: Some Forge Patches Ported 1.0.3
		spark: spark 1.9.11
			fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		sprout: Sprout 1.3.1
		spyglass-improvements: Spyglass Improvements 1.2+mc1.18.2+fabric
		starlight: Starlight 1.0.2+fabric.89b8d9f
		techreborn: Tech Reborn 5.2.0
		terrablender: TerraBlender 1.1.0.102
		thonkutil: ThonkUtil 2.14.1+1.18
			thonkutil-base: ThonkUtil Base 1.12.2+23c1dc2c60
			thonkutil-capes-v1: ThonkUtil Capes (v1) 1.3.2+9e23427060
			thonkutil-coords-v1: ThonkUtil Coords (v1) 1.0.19+9b80223760
			thonkutil-customization-v1: ThonkUtil Customization (v1) 1.0.14+9b80223760
			thonkutil-legacy: ThonkUtil Legacy 1.0.20+9b80223760
			thonkutil-modchecker-v1: ThonkUtil ModChecker (v1) 1.0.12+9b80223760
			thonkutil-potions-v0: ThonkUtil Potions (v0) 1.4.1+9b80223760
			thonkutil-titlescreen-v1: ThonkUtil TitleScreen (v1) 1.1.9+9b80223760
			thonkutil-trades-v1: ThonkUtil Trades (v1) 1.1.20+9b80223760
		timeoutout: TimeOut Out 1.0.1+1.18
		toolstats: ToolStats 9.0.3
		tooltipfix: ToolTip Fix 1.0.4-1.18
		trinketofundying: Trinket of Undying 2.0.2-1.18.2
		trinkets: Trinkets 3.3.1
		trinketshulkerboxes: Trinket Shulker Boxes 2.0.1-1.18.1
		twigs: Twigs 1.1.3-patch2+1.18.2
		valhelsia_core: Valhelsia Core 1.18.2-0.4.0
		valhelsia_tweaks: Valhelsia Tweaks 1.18.2-fabric-0.1.0
		visuality: Visuality 0.4.2
			goosik-config: goosik-config 0.2.0
			tlcosmetica: Cosmetica 0.4.0
		waystones: Waystones 10.1.0
		wilderworld: WilderWorld 2.2.2
			chord: Chord 1.8.0+1.18.2-fabric
		wolveswitharmor: Wolves With Armor 1.7.1-1.18.2
			maybe-data: Maybe data 1.2.1-1.18.2
			static-content: Static Content 1.0.1-1.16.2
				staticdata: Static Data 1.1.2
		wthit: wthit 4.11.0
		xaerominimap: Xaero's Minimap 22.12.0
		xaeroworldmap: Xaero's World Map 1.26.1
		yigd: You're in Grave Danger 1.3.7
		yosbr: YOSBR 0.1.1
		yungsapi: YUNG's API 1.18.2-Fabric-2.0.8
	Loaded Shaderpack: (off)
	Flywheel Backend: GL33 Instanced Arrays
	Server Running: true
	Player Count: 1 / 8; [class_3222['AMPBEAST66'/3877, l='ServerWorld minecraft:the_nether Creative World', x=-4.07, y=128.00, z=-6.97]]
	Data Packs: vanilla, Fabric Mods
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Client Crashes Since Restart: 0
	Integrated Server Crashes Since Restart: 16
	Suspected Mods: Minecraft (minecraft), QuarryPlus (quarryplus), Reborn Core (reborncore)
</details>

**Comment by Kotori316** [comment]
TechReborn should have responsibility of this issue because the `placer` is annotated as `@Nullable`. Methods shouldn't be called w/o null check to prevent any crashes.

**Comment by Kotori316** [comment]
I'm working and verifying the processes of Placer Plus and Filler, which place blocks with `null` user.

**Comment by Kotori316** [comment]
Fixed. But I don't recommend you to place/remove TR machines with Placer Plus.
