### ISSUE TITLE
Disable enchantment on quarry

### ISSUE THREAD

**Issue by Gaetann18** [Kotori316/QuarryPlus#209]
Minecraft-version = 1.18.2

Hello, currently it isn't possible to desactivate or modify the enchantments of the quarry.
Indeed i would like to be able to modify or remove the possibility of not applying an enchantment to the quarry via utilites like kubejs.
Unfortunately this isn't possible.
You shoul be able to modify this part of code : https://github.com/Kotori316/QuarryPlus/blob/39923b41e4ad7efd9bb108ad14d81ff431a59ca1/src/main/scala/com/yogpc/qp/machines/quarry/QuarryItem.java#L62

Thank in advance

**Comment by Kotori316** [comment]
Fixed in the latest version.

**Comment by Gaetann18** [comment]
Thank you for your responsiveness
