### ISSUE TITLE
Pass FakePlayer to canSilkHarvest

### ISSUE THREAD

**Issue by josephcsible** [Kotori316/QuarryPlus#21]
https://github.com/Kotori316/QuarryPlus/blob/7ff1e49be0bf7b11a8e1055c23465145a74f33e3/src/main/scala/com/yogpc/qp/tile/TileBasic.java#L137

Can you pass a FakePlayer to canSilkHarvest instead of `null`? This caused josephcsible/Oreberries#10 to occur. I worked around it via josephcsible/Oreberries@a842ed4, but I don't think I should have to do that.

**Comment by Kotori316** [comment]
Thank you for your report.

This is my mistake because `canSilkHarvest` doesn't have a parameter annotated `@Nullable`.
