### ISSUE TITLE
Quarry stuck on some Water/Pointed Dripstone Combination

### ISSUE THREAD

**Issue by Beleggrodion** [Kotori316/QuarryPlus#211]
## Describe the bug

I added a Quarry on an Area which had below in a cave some water and some pointed dripstone inside the water. The pointed dripstone and the water is also near the area border of the quarry. I had it now twice that the quarry stuck near the pointed dripstone in the water and don't work again. it consumes energy but no new items are farmed.

Each time i checked my quarry after some users told me that the server beginns to lag. So i checked today my quarry and see that their is again some pointed dripstone directly in the border inside of water. After i manually removed this pointed dropstone and placed some blocks behind it outside of the border to stop the waterflow, the quarry begins to work again as expected.

The power source for the quarry are solar panels from tech reborn.

Perhaps this is something that happens because since 1.17 the pointed dripstones can be waterlogged? So the quarry calculate something and is in an endless loop for a check to continue?

_What happened to you?_

## To Reproduce

1. Place 4 Markers to Set a Area for the Quarry
2. Place Quarry + 2 Solar Panels from Tech Reborn
3. Place Private EnderChest from Ender Chests to the Quarry Output
4. Mark Area "Force Loaded" in FTP Chunks
5. Wait some Time, Quarry Beginns to Start until below the Surface the Quarry Reach a Special Combination of Water and Dripstone.

If your server/client has crashed, please give me the crash report.

## Versions

* Minecraft version: 1.18.2
* Single Player or Multi Player?: MP
* Fabric Loader version: 0.14.8
* QuarryPlus version: 18.5.0
* Other mods: Very Big List, if need i can write the list manually down (because no crash report so no c&p list)

## Crash report or logs

No crash or log entries, only stopped quarry which don't breaks blocks.

**Comment by Kotori316** [comment]
This problem is very hard to reproduce. I'll continue to investigate the condition of this problem.
