### ISSUE TITLE
Enchantment Bug

### ISSUE THREAD

**Issue by xKean** [Kotori316/QuarryPlus#212]
## Describe the bug

_What happened to you?_
I was enchanting a chunk destroyer when I somehow got some Fortune IV on it. I got curious and investigated.

If you have some high'ish server latency + auto clicker you can easily get Fortune XCIV on it.
This one didn't work, anyways a Fortune 8 is working on it. I didn't test any further. Anyways it requires an enormous amount of energy. This can probably be handled with the same bug for unbreaking tho.

Edit: https://i.imgur.com/AXqOsvk.png <- this can mine a 10x10 Chunk in 4 Minutes

## To Reproduce

1. Place items(any enchantment level, 1 is enough) in the enchantment mover
2. Get some high ping
3. Autoclick the moving button with a 1ms delay
4. https://i.imgur.com/mszcK50.png <- Got this from an Efficiency 5, Unbreaking 3, Fortune 3 pickaxe in SINGLEPLAYER ( almost 0 latency)

## Versions

* Minecraft version: [1.18.2]
* Single Player or Multi Player?: [Multiplayer]
* Forge version: [40.1.68]
* QuarryPlus version: [18.14]
* Other mods: [ATM7 Modpack 0.4.29]

**Comment by Kotori316** [comment]
In my code, client sends a packet to server which moves the enchantment. The server should sync the enchantment soon, but client can send a new packet before the enchantment is synced. Also, the server doesn't check whether the enchantment can be moved.

I added code to check whether the enchantment can be moved in server side.
