### ISSUE TITLE
Minecraft crashes

### ISSUE THREAD

**Issue by Oskar87typ** [Kotori316/QuarryPlus#213]
QuarryPlus has class loading errors
java.lang.reflect.InvocationTargetException: null

Crash log: https://pastebin.com/y038DkzP
Latest log: https://pastebin.com/N7WsK5is

**Comment by Kotori316** [comment]
You have downloaded wrong version of mods. SLP of 2.13.10 is for Minecraft
1.19.2, but you are on 1.18

2022年10月15日(土) 20:28 Oskar87typ ***@***.***>:

**Comment by Oskar87typ** [comment]
Okay, thanks

**Comment by Oskar87typ** [comment]
Which one should I download then?

**Comment by Oskar87typ** [comment]
Okay, it is working now, tysm
