### ISSUE TITLE
Unable to craft or view recipes for the Remove Bedrock Module item.

### ISSUE THREAD

**Issue by Meolsei** [Kotori316/QuarryPlus#218]
## Describe the bug

Attempting to craft a Remove Bedrock Module item for a quarry will result in nothing happening, same for right or left clicking the item in JEI.

## To Reproduce

JEI:
1. Search for Remove Bedrock Module
2. Left/Right click item.

Workbench Plus:
1. Insert necessary items inside of the workbench.

## Versions

* Minecraft 1.18.2
* Multiplayer
* Forge 40.1.84
* QuarryPlus 18.16
* Mods: https://imgur.com/a/V5kqGj4

**Comment by Kotori316** [comment]
Check config file. The module seems to be disabled(default). Recipe isn't registered if the item is disabled.

**Comment by Meolsei** [comment]
> Check config file. The module seems to be disabled(default). Recipe isn't registered if the item is disabled.

Must I add*
Config for both the server and every player's client were changed.

**Comment by Kotori316** [comment]
I tested in my environment.

![2022-11-11_17 24 33](https://user-images.githubusercontent.com/28705167/201298163-779f6568-0f8a-4940-a1e5-16288ffdd5a3.png)

The item can be crafted if it is enabled in server config, regardless the client one. JEI also shows the recipe correctly.
