### ISSUE TITLE
How does the blacklist work? I have 500k snowballs.

### ISSUE THREAD

**Issue by spikespaz** [Kotori316/QuarryPlus#221]
I tried adding
```
  {
    "id": "minecraft:snow_layer"
  }
```

to the `blacklist.json`

because with Serene Seasons installed the quarry spends ALL of its time breaking the snow layers.

**Comment by Kotori316** [comment]
Which Minecraft version? Which machine are you using(Quarry Plus, Chunk Destroyer, Mini Quarry)?

The black list is not for this problem. It removes the drops of blocks. Then, I should add "ignore list" to machines.

**Comment by spikespaz** [comment]
This is Minecraft 1.12, and I'm using the new Quarry Plus.

**Comment by Kotori316** [comment]
I wrote an article of how to use black list in [Wiki](https://github.com/Kotori316/QuarryPlus/wiki/BlackList).

The article says you should add this to the `blacklist.json` in config dir.
```json
{
  "id": "quarryplus:blacklist_name",
  "name": "minecraft:snow_layer"
}
```
If you want to ignore the Snow block(not the layer), add this.
```json
{
  "id": "quarryplus:blacklist_name",
  "name": "minecraft:snow"
}
```

**Comment by spikespaz** [comment]
I appreciate this. Perhaps we should add all of the other "id"s to the Wiki too? It isn't exactly crystal clear what the `quarryplus:*` are identifying and the name `id` is ambiguous, I interpreted it as "block identifier".

**Comment by spikespaz** [comment]
Thank you for this!

**Comment by contestsauce** [comment]
Hi, how would this work for minecraft 1.19.2 (mod version: 1192.1.1)? Also, does the blacklist.json make the machine not break the block or not output the blacklisted block after breaking it?
