### ISSUE TITLE
Workbench Plus

### ISSUE THREAD

**Issue by xBlackPoison357x** [Kotori316/QuarryPlus#222]
## Describe the bug

Workbench plus will allow you to automatically dump stuff into the workbench using various pipes but will not allow you to extract them.

_What happened to you?_

Accidently had a workbench plus connected to my quarry system and over 1M blocks were put into the workbench plus, now I have no way to remove them except by hand or breaking the block which would drop 1M blocks onto the ground.

## To Reproduce
Use any pipe from other mods such as Refined storage, mekanism, modular routers and put stuff into the workbench. The workbench will allow you to put stuff inside it but not remove it.

1. Use a chest to auto put stuff into workbenchplus
2. try to auto remove stuff from workbenchplus
3. 

If your server/client has crashed, please give me the crash report.

## Versions

* Minecraft version: [] 1.19
* Single Player or Multi Player?: [] Both
* Forge version: [] 43.1.55
* QuarryPlus version: [] AdditionalEnchantedMiner-1.19.2-19.9.jar
* Other mods: [] All the mods 8

## Crash report or logs

If your Minecraft has crashed, please attach the crash report. Please use pastebin or just paste the report.

**Comment by Kotori316** [comment]
I didn't implement extracting from Workbench Plus because it isn't a storage. Workbench Plus can hold up to 2^31 items(stack count), so it may be a simple storage.

So, it should be configurable to extract items from Workbench. I'll add new config option to enable to extract items from Workbench.

**Comment by xBlackPoison357x** [comment]
Thanks! I appreciate it. Yeah it was never my attention to use it as a storage haha.

**Comment by Kotori316** [comment]
Uploaded as v19.10

https://www.curseforge.com/minecraft/mc-mods/additional-enchanted-miner/files/4141394
