### ISSUE TITLE
Marker Plus cannot be crafted legit

### ISSUE THREAD

**Issue by ahmadelafify** [Kotori316/QuarryPlus#224]
## Describe the bug
Marker Plus cannot be crafted. Me and my friends have been playing a legit only SMP on 1.19.2 and Marker Plus are essential but they cannot be crafted without spawning them in.

## To Reproduce
Try to craft one.

**Comment by Kotori316** [comment]
Intended. Use other markers such as Flexible Marker or Chunk Marker. See JEI to get how to craft them.

**Comment by IchigoGames** [comment]
??? you need the marker plus to craft the flexible marker or chunk marker

**Comment by IchigoGames** [comment]
so how can you make any of them without it ? jei does not show

**Comment by ahmadelafify** [comment]
You dont make Marker Plus. You make Flexible Markers in the Workbench Plus
