### ISSUE TITLE
Filler not working

### ISSUE THREAD

**Issue by NavedNoor** [Kotori316/QuarryPlus#225]
## Describe the bug

_What happened to you?_

## To Reproduce

1. Place flexible marker
2. Place Filler next to it
![2022-12-10_17 19 57](https://user-images.githubusercontent.com/47759894/206864958-24456fdc-0d92-4ae5-885d-86222653e26f.png)
4. Put Materials into Filler
5. Click on "Fill all"
![2022-12-10_17 20 05](https://user-images.githubusercontent.com/47759894/206865008-03066efb-1ba2-4198-b10a-43369bbe4546.png)
6. Marker drops as item on ground and no materials used
![2022-12-10_17 20 13](https://user-images.githubusercontent.com/47759894/206865031-b51f1eb3-011e-4982-a875-a3642e38f6d9.png)
![2022-12-10_17 20 16](https://user-images.githubusercontent.com/47759894/206865034-ef04d8e8-29e4-4f83-81d2-6a02c9b5ed4d.png)

If your server/client has crashed, please give me the crash report.

## Versions

* Minecraft version: [1.19.2]
* Single Player or Multi Player?: [Tried out on Multi and Single Player]
* Forge version: [43.1.43]
* QuarryPlus version: [19.8]
* Other mods: [Mekanism; IC2 Classic; FallingTree; Xaero's Minimap; Just Enough Items]

## Crash report or logs

If your Minecraft has crashed, please attach the crash report. Please use pastebin or just paste the report.

**Comment by Kotori316** [comment]
Please make sure that you're sending enough energy to the machine.
