### ISSUE TITLE
Chunk Destroyer Server Timeout

### ISSUE THREAD

**Issue by xBlackPoison357x** [Kotori316/QuarryPlus#226]
The chunk destroyer times the server out whenever it is checking for a protected area from FTB chunks and one is in its path. Attached is my spark profile.

Modpack: All the Mods 8 1.19.2

https://spark.lucko.me/hzNES662bV

**Comment by Kotori316** [comment]
OK, I understand how to read the log.
I don't know why this function causes lags but checking the protected area in every tick is not good.

**Comment by Kotori316** [comment]
Maybe fixed in 19.10.1
