### ISSUE TITLE
Edit recipes?

### ISSUE THREAD

**Issue by alexeik** [Kotori316/QuarryPlus#227]
Can i edit recipes?
Built-in recipes too much costs.
And removed marker plus push to build very expensive flex marker.

**Comment by Kotori316** [comment]
Use data pack.
You can add completely new recipes.

Don't ask me how to create it. There are a lot of information and example.

**Comment by alexeik** [comment]
@Kotori316 would be nice 
if you have this info in your wiki : 
https://github.com/TeamPneumatic/pnc-repressurized/wiki/Datapack-Overview#datapacks
