### ISSUE TITLE
Advanced Pump doesn't pump lava

### ISSUE THREAD

**Issue by SneakyDevil** [Kotori316/QuarryPlus#228]
## Describe the bug

Placing an advanced pump with power and tank next to it  over lava results in no fluid being pumped.

## To Reproduce

1. Place pump above lava

## Versions

* Minecraft version: 1.19.2
* Single Player or Multi Player?: sp
* Forge version: 43.1.55
* QuarryPlus version: AdditionalEnchantedMiner-1.19.2-19.10.1.jar
* Other mods: All-the-mods 8

![2022-12-24_14 59 55](https://user-images.githubusercontent.com/11374726/209450506-8305ddb0-2ad8-4bc6-b8d8-623016aacbe4.png)

**Comment by Kotori316** [comment]
Make sure that there is no block expect Air between the pump and fluid.
