### ISSUE TITLE
Quarryplus constantly stops working sometime starts working, and then stops again. (ATM8)

### ISSUE THREAD

**Issue by BandeeDee** [Kotori316/QuarryPlus#229]
Playing in Minecraft world using quarryplus and it suddenly decides to stop breaking blocks, as in it takes the fuel/energy, builds the frame, slowly moves the hand down, and just goes along its track without breaking blocks, and instead opts to go through them. No matter what dimension, no matter which of the quarrys i use both just break.

I have no idea what causes it to break nor to get it to work again, all I know is when i started using it it was broken and when i tried again later it worked, and then soon after it broke mid excavation. I have tried asking the allthemods8 server/reddit and the ftb reddit to no avail and i have scoured everywhere also to no avail. the only thing close ive gotten to an answer from other threads is something to do with fake players or something but no clue if that applies here

* Minecraft version: 1.19.2
* Single Player or Multi Player?: Single
* Forge version: 43.1.55
* QuarryPlus version: 19.10.1
* Other mods: All the mods 8 pack

(Images of the setup I have and what the arm is doing [FYI the setup has nothing to do with the issue as it happened before the stuff i added from create])
![image (2)](https://user-images.githubusercontent.com/121696207/210114134-064106ba-ebb6-4497-9d8a-afaabaeacbe0.png)
![image](https://user-images.githubusercontent.com/121696207/210114140-a95db006-70b5-4095-8687-09388622b149.png)

**Comment by BandeeDee** [comment]
oops wrong first image, heres the correct one, the setup

**Comment by BandeeDee** [comment]
accidently closed it my bad

**Comment by BandeeDee** [comment]
i am so sorry that i keep pressing the wrong button THIS IS the correct first image
![image](https://user-images.githubusercontent.com/121696207/210114539-67618f95-8335-45a8-946e-c21cfcc443e7.png)

**Comment by Kotori316** [comment]
I think the problem is the amount of energy supplied to the machine. Once quarry works(making frame, moving head, removing blocks), it stops until it has enough energy to do next work.
If using Creative Generator or enabling `NoEnergy` in config fixes your problem, energy shortage causes this problem.
If not, there is insufficient information to solve this issue. Then, turn on `debug` in config and the energy usage will be logged. Attaching the log might be useful to solve this issue.

**Comment by BandeeDee** [comment]
Well thats the issue, it does have fuel (the picture was just for the set up i have made it build itself) the problem i was having had to do with it not breaking blocks but consuming fuel and moving. however i think i fixed the issue by having the chunk constantly be loaded with a different mod so i think everythings good now.
