### ISSUE TITLE
Chunk Destroyer Not Collecting Ores?

### ISSUE THREAD

**Issue by Mihoshika** [Kotori316/QuarryPlus#230]
ATM8, most recent version.

Chunk Destroyer collects all the blocks for the first few seconds, then it only collects some types. Watched it mine over plenty of iron ore, but wasn't any being added to the chest.

Enchanted w/ Eff V, Unbreaking 3, Fortune 3. 
EnergyModule = 170 (assuming it's 5 per quarry fuel module)
EXP Module = 0 (Recently emptied)

**Comment by Kotori316** [comment]
I got a similar issue on curseforge, but I have no idea why this problem happens.
I thought it may be a problem of chunk loading, but it was not. Then, I think other mods "remove" the drop or prevent quarry from removing blocks, but there is no evidence.

I want you to install the latest(19.10.3) and add these lines in `common` section.
```
#Trace quarry work
logAllQuarryWork = true
```
Next, restart Minecraft and run Chunk Destroyer. Log file will be saved in `quarry-log` at the same level as mods directory.
Please attach the log, which helps me to get what is happened in quarry work.

**Comment by Mihoshika** [comment]
Just to clarify, the blocks are definitely getting removed. Just that the 'drop' isn't being collected. Will do the test later.

**Comment by Mihoshika** [comment]
Running it in single player now, not 100% certain, but the problem may just be that the chunk destroyer can't transfer fast stuff enough? It transfers one item at a time, and when you're clearing out 2+ chunks, (in the ATM mining dimension, that's about 120k+ blocks, not include fortuned stuff) per minute, it can't quite keep up.

Will post log after it finishes running.

**Comment by Mihoshika** [comment]
[quarry-logs.zip](https://github.com/Kotori316/QuarryPlus/files/10406613/quarry-logs.zip)

Needed to zip it 'cause was over 25mb

To clarify, the problem initially occurred on a server, which had lower TPS due to lag. This is a log from single player, since I can't join multiplayer server w/ different version of a mod.

Also, ended it about a third of the way through, since I didn't see the point in continuing. By the end, it was taking several minutes for it to go through all the cobble/end/deepslate/netherrack each), and only doing one type at a time.

Perhaps see if increasing transfer speed fixes issue?

**Comment by Kotori316** [comment]
The log said it successfully collected the drops, including common materials(Dirt, Stone, Netherrack, Endstone) and ores.
Any protections which interfere quarry works were not working. I thought protections from FTB Chunks always cause problems but it is not true in this case.

Transfer problem is a good point to check, so I added code to log transfers of items and fluids in v19.10.4
**Could you try this version and get new log again?** While or after quarry works, please get items from the quarry. All transfers are logged to file.

I have a question of transfer, how do you get items from the quarry? Use pipes or just place chests?
When I test quarry, I place vanilla chest next to the quarry to get items. Then I pull items from the chest with pipes or something. Or, if available, place ME Interface(from AE2)  to insert items directly to the ME network.
I haven't tried to use pipes to get items from Chunk Destroyer with `removeCommonMaterialsByCD=false`. In this case, 60 or more items are extracted in a tick. I don't know whether pipes can work in this situation. I recommend users to use Chest as buffer in order not to lost the items.

Edit: fix typo

**Comment by Mihoshika** [comment]
I just place a netherite backpack w/ 5 of the... netherite stack upgrades next to it. It shouldn't have issues with rate of transfer, though, since I've piped things into them far faster. Advanced deposit upgrade, and use that to dump them into chests at my base. 

I'll test it later today.

**Comment by Mihoshika** [comment]
Not 100% relevant to this, but maybe add a filter module, that allows you to not collect certain blocks (still breaking them), rather than forcing server owners to set just one option in the config that prevents them from being harvested completely? Wouldn't solve this issue entirely, but would allow a work around for the slow transfer rates. Would also allow for a reduction of lag, since there wouldn't be millions of blocks of cobble being transferred, maybe? *shrugs*

Starting the test now.

**Comment by Mihoshika** [comment]
[quarry-logs.zip](https://github.com/Kotori316/QuarryPlus/files/10415848/quarry-logs.zip)

**Comment by Mihoshika** [comment]
```...15,997]... SUCCESS (5x dirt,62x netherrack,20x gold_nugget,19x raw_copper,2x raw_osmium,62x end_stone,62x cobbled_deepslate,114x cobblestone,5x coal) (Total = 289 items)
...15,997]... Transfer 64x ItemKey[item=cobblestone] to <backpack> (x4, Total = 256 blocks)
...16,050]... SUCCESS (5x dirt,61x netherrack,30x gold_nugget,28x raw_copper,4x emerald,64x end_stone,63x cobbled_deepslate,113x cobblestone,6x coal) (Total = 374)
...16,051]... Transfer 64x ItemKey[item=cobblestone] to <backpack> (x4, Total = 256 blocks)
...16,106]... SUCCESS  (14x raw_iron,5x dirt,61x netherrack,3x raw_tin,42x gold_nugget,64x end_stone,62x cobbled_deepslate,107x cobblestone,14x coal) (Total = 372)
...16,106]... Transfer 64x ItemKey[item=cobblestone] to <backpack>  (x4, Total = 256 blocks)
...16,166]... SUCCESS (8x raw_crimson_iron,17x raw_iron,5x dirt,60x netherrack,7x raw_tin,16x gold_nugget,64x end_stone,61x cobbled_deepslate,104x cobblestone,23x coal) (Total = 365)
```
Just a few entries towards the end, abridged. As you can see, the amount mined is a good deal more than the amount transferred.

**Comment by Kotori316** [comment]
Thank you very mush for getting logs.
I'll see the log.

**Comment by Kotori316** [comment]
From the log, all items are transferred to the storage.
The amount of transferred items seems to be more than the amount of mined blocks, but the transferred items are changing in the log. For example, at 2023-01-13T16:51:23 quarry transferred cobbled_deepslate, but uraninite are transferred at 2023-01-13T16:59:23. I don't track every items, but the quarry outputs all items correctly to adjacent inventory.

Chunk Destroyer gets a large amount of common materials such as Cobblestone and Dirt, so I added config option(`removeCommonMaterialsByCD`) to remove these items, but this modpack changed this to `false`. Then the quarry always transfers stones. This config option can't be edited in server world.

If you change `removeCommonMaterialsByCD` to `true` in your single player world and all items are collected successfully, the amount of common material causes this item lost. In this case, I should create in-game option to remove drops from specific blocks.

**Comment by Mihoshika** [comment]
I am assuming the issue I was having possibly originates from powering the quarry and letting it mine for a bit before putting down the storage for it. The difference between the amount it mines, and the amount it transfers would end up making it have a long queue, plus relatively slow server due to lag. This would also account for there being, for instance, iron having already been mined, since it would have gotten a first spot in the queue, gotten transferred, then ended up later in the queue, which grows the longer the chunk destroyer is running, and is pushed back for a long time due to the machine getting more than it puts out.

Anyways, I appreciate you putting effort into resolving this issue. Hopefully you decide to eventually implement a 'filter' module, or something to that effect. Have a nice day~
