### ISSUE TITLE
Can you add support for this mod?

### ISSUE THREAD

**Issue by ghost** [Kotori316/QuarryPlus#234]
Due to Thermal Dynamics isn't available for Forge 1.19.2 can you add support for this: https://www.curseforge.com/minecraft/mc-mods/pipez

I can use pipes from Quark to move items but it doesn't work well.

**Comment by Kotori316** [comment]
Please describe how it should work and how it works now precisely. What is the expected work?
I've never used this mod, but I think it interacts machines in my mod via API by Forge, so basically, it should work fine.
You may have problems, but I don't have any ideas and how to solve it.

**Comment by Mihoshika** [comment]
I am able to use pipez well enough on a chunk destroyer. Surround sides with pipez, set to output, slap in some ultimate upgrades, then output that to your storage. Flux point on top for power.  It keeps up, and transfers everything.
