### ISSUE TITLE
Remove Bedrock Module Recipe Not Working - ATM8

### ISSUE THREAD

**Issue by LilHaramBae** [Kotori316/QuarryPlus#235]
## Describe the bug

Unable to create the remove bedrock module even after enabling the config.

Not sure if it's a QuarryPlus side issue or an ATM8 issue so I also decided to post it here.

## To Reproduce

1. Edited  -> config/quarryplus-common.toml
remove_bedrock_module = true

2. Can now see the Remove Bedrock Module crafting recipe JEI
https://imgur.com/a/1y8P3OC

3. Putting the recipe in the quarry plus workbench doesn't do anything.
(Requires Silk touch, which I have on the Pic Axe)
https://imgur.com/a/TgeJLDF

If your server/client has crashed, please give me the crash report.
N/A

## Versions

* Minecraft version: [1.19.2]
* Single Player or Multi Player?: Multiplayer & Singleplayer
* Forge version: [43.1.55]
* QuarryPlus version: [AdditionalEnchantedMiner-1.19.2-19.10.1]
* Other mods: [ATM8 1.0.7 mods]

## Crash report or logs
N/A

**Comment by Kotori316** [comment]
Thank you for reporting.
I found that the module can be crafted with Diamond Pickaxe with Silktouch given with command, but can't with pickaxe enchanted with Anvil.
I'll make a fixed version.

**Comment by Kotori316** [comment]
Fixed in [v19.10.5](https://www.curseforge.com/minecraft/mc-mods/additional-enchanted-miner/files/4368712)
