### ISSUE TITLE
Class Loading error

### ISSUE THREAD

**Issue by Mattslayer2006** [Kotori316/QuarryPlus#237]
## Describe the bug

An error came when trying to launch minecraft with the mod

## To Reproduce

1. Put the the additional enchanted miner plus the scalable cats force in the mod folder
2. launch minecraft
3. The error pops up with the crash-report option log file option and open mods folder button

If your server/client has crashed, please give me the crash report.

## Versions

* Minecraft version: [1.19.2]
* Single Player or Multi Player?: [singleplayer]
* Forge version: [43.2.0]
* QuarryPlus version: [19.10.2]

* Other mods: [ yes but I tried without the other mods not the issue]

## Crash report or logs

If your Minecraft has crashed, please attach the crash report. Please use pastebin or just paste the report.

[crash-2023-01-30_13.08.26-fml.txt](https://github.com/Kotori316/QuarryPlus/files/10535588/crash-2023-01-30_13.08.26-fml.txt
)

![error](https://user-images.githubusercontent.com/80539716/215473315-db514644-d735-4cdc-a6a7-d5b783b380f9.png)

**Comment by Kotori316** [comment]
You have wrong version of Scalable Cats Force. Please update to the [latest](https://www.curseforge.com/minecraft/mc-mods/scalable-cats-force/files/4028119).

**Comment by Mattslayer2006** [comment]
Thx
