### ISSUE TITLE
[19.10.2] MiningWell unable to be enchanted

### ISSUE THREAD

**Issue by drunkripper** [Kotori316/QuarryPlus#242]
Hi, I am playing with 19.10.2 and can not enchant a mining well but can enchant the quarry.

**Comment by Kotori316** [comment]
Sorry for this inconvenience. The wiki says the machine can be enchanted but it is not true for latest version.
I deleted enchantments from the machine in 1.17 because it is over spec. I think it is useless to give enchantments to MiningWell, not quarry.

**Comment by drunkripper** [comment]
Could you add it as a config option? Without it mining well is extremely
slow.

**Comment by Kotori316** [comment]
OK. It makes sense.
Currently, it takes 40 ticks(2 sec) to remove 1 block.
Then, I'll use this table for intervals.
| Efficiency | Interval |
| -: | -: |
| 0 | 40 | 
| 1 | 30 |
| 2 | 20 |
| 3 | 10 |
| 4 | 5 |
| 5 | 1 |

**Comment by drunkripper** [comment]
Thank you. Its for mining machine I’m making that moves mining wells
forward

**Comment by Kotori316** [comment]
Published as [v19.10.7](https://www.curseforge.com/minecraft/mc-mods/additional-enchanted-miner/files/4416830).
Just give enchantment to the machine (no config change is needed), then it works faster.
