### ISSUE TITLE
Mining Well Won't Ignore Water

### ISSUE THREAD

**Issue by drunkripper** [Kotori316/QuarryPlus#247]
Mining well will infinitely mine water if over a lake/pond and won't mine any useful material. 
MC 1.19.2 AEM 19.07

**Comment by Kotori316** [comment]
Opps...
I'll take a look.

**Comment by Kotori316** [comment]
Fixed in [v19.10.8](https://www.curseforge.com/minecraft/mc-mods/additional-enchanted-miner/files/4418362)
