### ISSUE TITLE
Overstacking with workbenchplus

### ISSUE THREAD

**Issue by Eq1s** [Kotori316/QuarryPlus#253]
## With the workbench plus you can keep 2b items in your inventory per slot

_What happened to you?_
I crafted a chunk destroyer and accidentally pressed a number on the keyboard when I aimed at a slot in which there were 512 blocks of glass and I had 512 blocks in the hotbar in one slot, which is actually higher than the maximum in the form of 64, I also tried with other quantities and everything fit in one slot
(sorry, closed by missclick)

## To Reproduce

1. put something in one slot in workbench, more than 64
![изображение](https://user-images.githubusercontent.com/95995139/229271209-5514c186-a22e-4b22-a1a0-6423925c89d9.png)
2. Press the button on the keyboard with a number, depending on which slot on the hotbar you want to put these items in
3. Enjoy overstacked items in your inventory 
![изображение](https://user-images.githubusercontent.com/95995139/229271483-b9c59815-b91c-4a3c-a54b-05756b79a5a1.png)

## Versions

* Minecraft version: [1.19.2]
* Single Player or Multi Player?: [singleplayer]
* Forge version: [43.2.6]
* QuarryPlus version: [1192.0.0]
* Other mods: [mods from atm 8 modpacks]

**Comment by Kotori316** [comment]
This unexpected behavior exists since old version, such as 1.18.2
I need to find which method is called when number keys in keyboard is pressed.

**Comment by Kotori316** [comment]
Released fixed version for 1.19.2
