### ISSUE TITLE
Enchantment Mover UI Blank

### ISSUE THREAD

**Issue by dieHARD120** [Kotori316/QuarryPlus#257]
What happened to you?_

- When I access the "Enchantment Mover", I get a blank UI for where the enchantments should be and my entire inventory. I do have over 100 mods which may be playing a role sadly.. Something I noticed too is that where the enchantments should be at when I click on them, I can still transfer enchantments but basically can't see what's happening. Same thing applies when I try to drag an item to any of the required slots for the mover. Any help on where to start at would be great! thxs.

![Screenshot 2023-04-09 083650](https://user-images.githubusercontent.com/128800776/230772879-7f859f6a-b708-4319-a4ce-a20a8725b328.png)

* Minecraft version: [1.19.3]
* Single Player or Multi Player?: [SP]
* Forge version: [44.1.23]
* QuarryPlus version: [v19.13]

**Comment by Kotori316** [comment]
It seems very strange. I coded to show 3 buttons in the windows, but only the first one appears.
You mean the function works well, so it is a problem in rendering.

Does the log file contain something like error or warning? I think screen rendering was interrupted by some exceptions.

Of course, in dev environment, the screen is rendered successfully.
