### ISSUE TITLE
Dupe items

### ISSUE THREAD

**Issue by BabylenMagnus** [Kotori316/QuarryPlus#258]
## Describe the bug

_What happened to you?_
I inadvertently duped the **Experience Pump** and **Mining Well**

## To Reproduce

1. Start craft **Experience Pump** in **Workbrench**
2. Click sort-button from [Inventory sorter mod](https://www.curseforge.com/minecraft/mc-mods/inventory-sorter)
3. Duped  the **Experience Pump** and **Mining Well**

## Versions

* Minecraft version: 1.19.2
* Single Player or Multi Player?: Lan Multi Player
* Forge version: 43.2.10
* QuarryPlus version: 1192.1.0
* Other mods: Inventory Sorter last version

## Crash report or logs

Video:  
https://youtu.be/CdwUDs8YZQs

**Comment by Kotori316** [comment]
Thank you for your report and recording video.

Maybe fixed in 1192.1.1
If this bug is not fixed, I'll do more investigation.
