### ISSUE TITLE
Crash in conjunction with EcologyMod

### ISSUE THREAD

**Issue by Golrith** [Kotori316/QuarryPlus#26]
When using EcologyMod in conjunction with Quarryplus, minecraft crashes on load.

[latest.log](https://github.com/Kotori316/QuarryPlus/files/2263860/latest.log)

**Comment by Kotori316** [comment]
Try this.
[AdditionalEnchantedMiner-1.12.2-0.9.12-universal.zip](https://github.com/Kotori316/QuarryPlus/files/2297718/AdditionalEnchantedMiner-1.12.2-0.9.12-universal.zip)
