### ISSUE TITLE
[Fabric] Filler not accepting energy sources but creative generator

### ISSUE THREAD

**Issue by Drakune** [Kotori316/QuarryPlus#261]
## Describe the bug

The filler wont accept any energy source, except the creative generator, making it useless in singleplayer

## To Reproduce

1. Place filler and try to connect it to solar panel or any other mod generator, tried 2

If your server/client has crashed, please give me the crash report.

## Versions

* Minecraft version: [1.20.1]
* Single Player or Multi Player?: [Multiplayer]
* Fabric version: [0.84.0]
* QuarryPlus version: [20.0.801]
* Other mods: [
* ad_astra: Ad Astra 1.15.1
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.8
		ae2: Applied Energistics 2 15.0.3-alpha
		ae2wtlib: AE2WTLib 15.0.1-beta
		appleskin: AppleSkin 2.5.0+mc1.20
		architectury: Architectury 9.0.8
		bclib: BCLib 3.0.10
			wunderlib: WunderLib 1.1.3
		betterend: Better End 4.0.7
		betternether: Better Nether 9.0.7
		biomemusic: Biome Music Mod 1.20.1-1.6
		botarium: Botarium 2.1.0
		carpet: Carpet Mod 1.4.112+v230608
		chunkloaders: Chunk Loaders 1.2.4
		chunky: Chunky 1.3.92
		cloth-config: Cloth Config v11 11.0.99
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 12.0.0.3
		collective: Collective 6.62
		connectedglass: Connected Glass 1.1.6
		connectivity: Connectivity Mod 1.20.1-4.2
		cristellib: Cristel Lib 1.1
		dungeons_andtaverns_mr: Dungeons and Taverns 1-v2.1.3
		dungeons_arise: When Dungeons Arise 2.1.56.1
		easyelytratakeoff: Easy Elytra Takeoff 4.0
		elytraslot: Elytra Slot 6.3.0+1.20.1
		fabric-api: Fabric API 0.84.0+1.20.1
			fabric-api-base: Fabric API Base 0.4.29+b04edc7a77
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.34+4d8536c977
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.10+b3afc78b77
			fabric-block-api-v1: Fabric Block API (v1) 1.0.9+e022e5d177
			fabric-command-api-v1: Fabric Command API (v1) 1.2.32+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.11+b3afc78b77
			fabric-commands-v0: Fabric Commands (v0) 0.2.49+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.61+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.7+b3afc78b77
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.3+b3afc78b77
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.1.11+b3afc78b77
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.51+b3afc78b77
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.21+b3afc78b77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.0+b3afc78b77
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.61+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.38+b04edc7a77
			fabric-item-api-v1: Fabric Item API (v1) 2.1.26+b3afc78b77
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.7+b3afc78b77
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.20+b3afc78b77
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.37+b3afc78b77
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.41+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.6+b3afc78b77
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.47+b3afc78b77
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.8+b3afc78b77
			fabric-networking-v0: Fabric Networking (v0) 0.3.48+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.0.6+b3afc78b77
			fabric-particles-v1: Fabric Particles (v1) 1.0.28+b3afc78b77
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.18+b3afc78b77
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.2.6+b3afc78b77
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.33+b3afc78b77
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.26+b3afc78b77
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.5+ea08f9d877
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.7+f7923f6d77
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.27+b3afc78b77
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.2.2+b3afc78b77
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.2.0+b3afc78b77
		fabric-language-kotlin: Fabric Language Kotlin 1.9.6+kotlin.1.8.22
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.8.22
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.8.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.8.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.8.22
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.21.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.1
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.1
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.5.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.5.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.5.1
		fabricloader: Fabric Loader 0.14.21
		ferritecore: FerriteCore 6.0.0
		handcrafted: Handcrafted 2.3.2
		immersive_aircraft: Immersive Aircraft 0.5.1+1.20.1
		inventorytotem: Inventory Totem 3.0
		jade: Jade 11.1.4
		jamlib: JamLib 0.6.0+1.20
		java: Java HotSpot(TM) 64-Bit Server VM 17
		kotori_scala: Scalable Cat's Force Fabric 2.0.0
			org_scala-lang_scala-library: scala-library 2.13.10
			org_scala-lang_scala3-library_3: scala3-library_3 3.3.0
			org_typelevel_cats-core_3: cats-core_3 2.9.1-kotori
			org_typelevel_cats-free_3: cats-free_3 2.9.1-kotori
			org_typelevel_cats-kernel_3: cats-kernel_3 2.9.1-kotori
		letmedespawn: Let Me Despawn fabric-1.20-1.1.0
		mcpitanlibarch: MCPitanLib 1.6.10-1.20.1-fabric
			org_yaml_snakeyaml: snakeyaml 2.0
		mcwbridges: Macaw's Bridges 2.1.0
		mcwpaths: Macaw's Paths and Pavings 1.0.3
		mcwroofs: Macaw's Roofs 2.2.4
		minecraft: Minecraft 1.20.1
		modernfix: ModernFix 5.1.1+mc1.20.1
		mtr: Minecraft Transit Railway 1.20-3.2.2-hotfix-1
		owo: oωo 0.11.0+1.20
			blue_endless_jankson: jankson 1.2.2
		quarryplus: QuarryPlus 20.0.801
		reborncore: Reborn Core 5.8.3
			team_reborn_energy: Energy 3.0.0
		resourcefulconfig: Resourcefulconfig 2.0.0
		resourcefullib: Resourceful Lib 2.1.1
			com_teamresourceful_yabn: yabn 1.0.3
		rightclickharvest: Right Click Harvest 3.2.2+1.19.x-1.20.1-fabric
		roughlyenoughitems: Roughly Enough Items 12.0.625
			error_notifier: Error Notifier 1.0.9
		simplyswords: Simply Swords 1.48.0-1.21
		smoothchunk: Smooth chunk save Mod 1.20.1-3.0
		supermartijn642configlib: SuperMartijn642's Config Lib 1.1.6
		supermartijn642corelib: SuperMartijn642's Core Lib 1.1.9
		t_and_t: Towns and Towers 1.10.2
		techreborn: Tech Reborn 5.8.3
		tesseract: Tesseract 1.0.34
		treeharvester: Tree Harvester 8.2
		trinkets: Trinkets 3.7.0
			cardinal-components-base: Cardinal Components API (base) 5.2.0
			cardinal-components-entity: Cardinal Components API (entities) 5.2.0
		universal-graves: Universal Graves 3.0.0-beta.4+1.20.1
			common-protection-api: Common Protection API 1.0.0
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
			placeholder-api: Placeholder API 2.1.1+1.20
			polymer-core: Polymer (Core) 0.5.3+1.20.1
				polymer-networking: Polymer (Networking) 0.5.3+1.20.1
				polymer-registry-sync-manipulator: Polymer (Registry Sync Manipulator) 0.5.3+1.20.1
			polymer-resource-pack: Polymer (Resource Pack) 0.5.3+1.20.1
			polymer-virtual-entity: Polymer (Virtual Entity) 0.5.3+1.20.1
				polymer-common: Polymer (Common) 0.5.3+1.20.1
			predicate-api: Predicate API 0.1.2+1.20
			server_translations_api: Server Translations API 2.0.0+1.20
				packet_tweaker: Packet Tweaker 0.4.0+1.19.4
			sgui: sgui 1.2.2+1.20
		usefulbackpacks: Useful Backpacks 2.0.1.119
		uteamcore: U Team Core 5.1.3.267
]

## Crash report or logs

If your Minecraft has crashed, please attach the crash report. Please use pastebin or just paste the report.

**Comment by Kotori316** [comment]
Oh, it seems something is wrong. Quarry Plus can accept energy from Tech Reborn but Filler can't. I'll take a look.

**Comment by Kotori316** [comment]
Fixed in the latest release in CurseForge
