### ISSUE TITLE
Add config to change the limit for the Flexible marker

### ISSUE THREAD

**Issue by yutoe** [Kotori316/QuarryPlus#266]
## Idea

Wanted to see if you could add a config for the Flexible markers, as the mining dimension in All the Mods 8 reaches from 255 down to -64 and the marker wouldn't reach that far

## Versions

Using All the Mods 8-1.0.22

**Comment by Kotori316** [comment]
Memo
Minecraft 1.19.2 with Forge

Check `TileFlexMarker#maxRange` (https://github.com/Kotori316/QuarryPlus/blob/72eb56ba75ef30194610f9f578c66e9336f690fe/src/main/scala/com/yogpc/qp/machines/marker/TileFlexMarker.java#L26-L27) and change to load config value, that's it.

**Comment by yutoe** [comment]
Thank you for what you do, ive seen that are very active with your mod, Thank you again for your hard work

**Comment by Kotori316** [comment]
Uploaded [v1192.2.1-forge [1.19.2]](https://legacy.curseforge.com/minecraft/mc-mods/additional-enchanted-miner/files/4695707)
