### ISSUE TITLE
[1.20.1] Marker Plus craft is missing.

### ISSUE THREAD

**Issue by programgames** [Kotori316/QuarryPlus#267]
## Describe the bug

The craft of the item 'Marker Plus' is missing
## To Reproduce

1.  Click of the 'Marker Plus' item on JEI to see the craft.
2. The craft view page does not show up.

## Versions

* Minecraft version: 1.20.1
* Single Player or Multi Player?: Both
* Forge version: 47.1.3
* QuarryPlus version: 1.20.1-1201.0.11-SNAPSHOT
* Other mods: JEI

**Comment by programgames** [comment]
Ok as I understand the item is partially removed https://github.com/Kotori316/QuarryPlus/issues/239
So I can use the flexible marker that I can craft with the second craft ( the one without the Marker Plus )

**Comment by Kotori316** [comment]
You can add recipe for Marker Plus with your own datapack.
(I think I should create the datapack to add recipe to convert markers. I'll try if I have time to do)

The guide line or marker line can't be rendered far away from marker. It disappears if you're 256 blocks far from the marker. This issue might cause complains so I disabled the basic marker.
