### ISSUE TITLE
How does the blacklist.json work for minecraft 1.19.2 (mod version: 1192.1.1 - Forge)?

### ISSUE THREAD

**Issue by contestsauce** [Kotori316/QuarryPlus#268]
I tried following the post https://github.com/Kotori316/QuarryPlus/issues/221, but I couldn't make it work. I'm trying to blacklist the end stone block but no success.

Does it work differently for 1.19.2? Also, just to confirm, does the blacklist.json file cause the machine not to break the blacklisted block? Or does it cause the machine not to output the blacklisted block after breaking it?

**Comment by Kotori316** [comment]
The original post if only for 1.12 and old version. It never works in 1.18 or later.

For the current version, there is an item named "Void Module" which deletes the output items after breaking. It might be useful if you don't want to collect terrain blocks added by other mods.

If you want to keep End Stone, you can use Mini Quarry. See [this page](https://github.com/Kotori316/QuarryPlus/wiki/MiniQuarry) and set disallow list. This machine will get blocks in End except the End Stone.
If you want to get more detail, please ask me.

**Comment by contestsauce** [comment]
I see. I was actually looking to disable the end stone from being mined through any machine, making it not quarryable, only player mineable. Is this possible?

**Comment by Kotori316** [comment]
Currently, no. I need to implement this feature to force machines to ignore specific blocks in global setting(server side config). I'll work when I have time. (just a few days)

I want to ask these questions.
1. Are you in multi player server? This is a question to decide where to place config, client side or server side. The server side config is only for the world, but it suits if you're the admin of a multi player server.
2. Do you want to disallow players to mine End Stone with automatic machines including one from other mods, not limited to my mod? I can add config for my mod, but it doesn't work for other mods.

**Comment by contestsauce** [comment]
No worries. Below are your answers:
1. Yes, I'm the admin of a multi player server
2. Actually, my overall goal is to disallow players to mine in **the End dimension** with automatic machines including one from other mods. I was trying to achieve that by disabling the mining of the end stone which would achieve what I'm looking for as well. And I understand that you can only add config for your mod.

Feel free to close this issue if you don't have anything else to comment.

**Comment by Kotori316** [comment]
Thank you for fast answering.

I'll add some config to disable machines for my mod. Also I made a plan to create a mod which denies mining by specific player including Fake Player (the system user mods should use).

I'll keep this issue open until I implement config for my mod.

**Comment by Kotori316** [comment]
I added a new config option `unworkableDimensions` in server config. Set to `minecraft:the_end`. This will disable machine work in the dimension. This is released as [1192.2.13-forge](https://modrinth.com/mod/additional-enchanted-miner/version/1192.2.13) (also available in curse forge). Change log says it's 2.3, but this is just a mistake.

If you get some bugs, post here for fix.
