### ISSUE TITLE
ChunkDestroyer not mining 

### ISSUE THREAD

**Issue by Pytness** [Kotori316/QuarryPlus#275]
## Describe the bug 

ChunkDestoyer suddenly has stopped working. It generates the area frame but does not mine. It consumes no power, and shows that it has power even when there is none connected

## To Reproduce

1. Put ChunkDestroyer
2. Give it power
3. Hit Start

If your server/client has crashed, please give me the crash report.

## Versions

* Minecraft version: 1.19.2
* Single Player or Multi Player?: Singleplayer
* Forge version: 43.2.14
* QuarryPlus version: 1192.2.1
* Other mods: AllTheMods8

## Crash report or logs

Cannot upload to pastebin as logfile is too large.
This are some related lines i could find.

```
[18Sep2023 07:33:32.697] [Server thread/DEBUG] [QuarryPlus/]: ChunkDestroyer(BlockPos{x=1120, y=253, z=1643}) State changed from Waiting to MakeFrame.
[18Sep2023 07:33:34.597] [Server thread/DEBUG] [QuarryPlus/]: ChunkDestroyer(BlockPos{x=1120, y=253, z=1643}) State changed from MakeFrame to BreakBlock.
```

If your Minecraft has crashed, please attach the crash report. Please use pastebin or just paste the report.

**Comment by Kotori316** [comment]
1. Change `allowWorkInClaimedChunkByFBTChunks` in config to `true`
2. Change `logAllQuarryWork` in config to `true`, then re-run the machine.
    * This will log all works in Quarry in log dir(`quarry-logs/quarry-debug.log)
    * It might help me to get the reason why quarry doesn't work in your world.

(Changing config requires Minecraft to restart)

Your log file may be useful to check errors in my mod. Just making zip file is enough for me.

**Comment by Pytness** [comment]
`allowWorkInClaimedChunkByFBTChunks` was already `true`.

Here is the quarry log (Loading world, placing quarry down, restarting): https://pastebin.com/tacM3V2S

Debug log from minecraft: [latest.zip](https://github.com/Kotori316/QuarryPlus/files/12648317/latest.zip)

~When I place down the quarry (without an energy source), it spawn with full energy (1K), when it places the frame, it goes down to 940 (mining 1 chunk), and then goes back up to 1k.~

Config files: 
[config_files.zip](https://github.com/Kotori316/QuarryPlus/files/12648393/config_files.zip)

**Comment by Pytness** [comment]
The energy going up is my bad, as i had useEnergy off while testing.

**Comment by Pytness** [comment]
Might have found the issue (and the solution).
ATM8 seems to have a very low default energy capacity; 6k instead of the default 300K. May be the other way around, so low capacity but using high energy usage. Either way is a configuration issue.

Resetting the config fixes the issue. It could be nice to have a message explaining the problem

**Comment by krpgopack** [comment]
Pytness, can you explain how you fixed this? I'm having the same problem and it has been so aggravating trying to resolve it.

**Comment by Kotori316** [comment]
He changed the config.
In power map section, your config might be modified to set low `maxEnergy`. So change the config or resetting to default will solve this issue.

The default config parameters
```json
"powerMap": {
  "mini_quarry": {
    "maxEnergy": 1000.0,
    "breakBlockBase": 20.0
  },
  "solid_fuel_quarry": {
    "maxEnergy": 1000.0,
    "breakEfficiencyCoefficient": 1.379729661461215,
    "breakBlockBase": 25.0,
    "moveHeadBase": 1.0,
    "efficiencyCoefficient": 1.5848931924611136,
    "makeFrame": 15.0,
    "breakBlockFluid": 125.0,
    "expCollect": 2.5,
    "breakFortuneCoefficient": 1.5874010519681996,
    "breakSilktouchCoefficient": 4.0
  },
  "adv_quarry": {
    "maxEnergy": 50000.0,
    "breakEfficiencyCoefficient": 1.379729661461215,
    "breakBlockBase": 25.0,
    "moveHeadBase": 1.0,
    "efficiencyCoefficient": 1.5848931924611136,
    "makeFrame": 15.0,
    "breakBlockFluid": 125.0,
    "expCollect": 2.5,
    "breakFortuneCoefficient": 1.5874010519681996,
    "breakSilktouchCoefficient": 4.0
  },
  "filler": {
    "maxEnergy": 1000.0,
    "breakBlockBase": 15.0
  },
  "book_mover": {
    "maxEnergy": 50000.0
  },
  "workbench": {
    "maxEnergy": 5.0
  },
  "quarry": {
    "maxEnergy": 10000.0,
    "breakEfficiencyCoefficient": 1.379729661461215,
    "breakBlockBase": 25.0,
    "moveHeadBase": 1.0,
    "efficiencyCoefficient": 1.5848931924611136,
    "makeFrame": 15.0,
    "breakBlockFluid": 125.0,
    "expCollect": 2.5,
    "breakFortuneCoefficient": 1.5874010519681996,
    "breakSilktouchCoefficient": 4.0
  }
}
```

In the latest version, something like `required %d FE for %s, but maxEnergy is %d FE` is logged in warn level.
