### ISSUE TITLE
Fuel Module does not work

### ISSUE THREAD

**Issue by KH3Sora** [Kotori316/QuarryPlus#276]
The quarry plus fuel Module does not increase the speed of the quarry in multiplayer or single player

1. place quarry fuel Module in Quarry.
2. Speed does not increase

## Versions

* Minecraft version: 1.20.1
* Single Player or Multi Player?: Both
* Forge version: 47.1.3
* QuarryPlus version: AdditionalEnchantedMiner-1.20.1-1201.0.17.jar
* Other mods: atm9

**Comment by Kotori316** [comment]
It is not an item to increase the speed of quarry. It just supplies 5 FE/t per an item and can used as infinite power source. 64-stacked item will supply 320 FE/t.

To speed up the quarry, you can add Efficiency enchantments.
