### ISSUE TITLE
WorkbenchPlus is not crafting

### ISSUE THREAD

**Issue by collapse17** [Kotori316/QuarryPlus#277]
## Describe the bug

Workbench plus is not crafting any recipe. Clicking on any recipe causes a green frame to appear briefly on the screen. Nothing happens next

## To Reproduce

1. Place WorkbenchPlus
2. Put the necessary resources into it
3. Give it power/or no
4. Click on recipe

_onclick green frame appeared_
![2023-10-19_12 34 35](https://github.com/Kotori316/QuarryPlus/assets/33090441/1c952b8c-c9c9-43a9-93ce-6dabfe76fc59)

_a moment later nothing happens_
![2023-10-19_12 34 34](https://github.com/Kotori316/QuarryPlus/assets/33090441/f0274687-718d-4904-9908-fada240bd62e)

## Versions

* Minecraft version: 1.20.2
* Single Player or Multi Player?: both
* Forge version: 48.0.19, 48.0.30

* QuarryPlus version: 1202.0.19
* Other mods: Energizedpower 1.20.2-2.2.0, XaerosMiniMap, JEI/or without mods

## Crash report or logs

No crashes

**Comment by Kotori316** [comment]
I'm sorry for that inconvenience. I fixed in the latest version for 1.20.2
