### ISSUE TITLE
Too many Block Dummies

### ISSUE THREAD

**Issue by djnifos** [Kotori316/QuarryPlus#278]
I unknowingly quarried a bunch of ocean with my Chunk Destroyer, and have made an area where I can't break the dummy blocks without crashing the server. 

This is what the server crash looks like. 
https://mclo.gs/TkTljeq

**Comment by Kotori316** [comment]
It seems quarry tries to remove too much block in a tick, but it took over 180 seconds so Minecraft crashed.

I think it is just a performance issue, but I'll make a limit of number of blocks to remove in just one tick.

**Comment by djnifos** [comment]
Verified this fix works, no crash
