### ISSUE TITLE
Suggestion - Horizontal mode for Quarry Plus, Chunk Destroyer, and Miningwell

### ISSUE THREAD

**Issue by Unjustifiable** [Kotori316/QuarryPlus#28]

**Comment by Kotori316** [comment]
QuarryPlus has frame mode, which digs inside the frame.
Use 4 markers and <font color=00FF00>right click quarryplus before sending energy</font>.
See the pictures below.

1. How to place markers.
![2018-08-08_14 19 44](https://user-images.githubusercontent.com/28705167/43817899-edf23814-9b16-11e8-92c2-cf1316c5541c.png)
![2018-08-08_14 21 57](https://user-images.githubusercontent.com/28705167/43817909-fdaab6e6-9b16-11e8-8ada-087901e82f9b.png)
2. **Right click quarryplus to change its mode to Frame Mode.**
![2018-08-08_14 22 17](https://user-images.githubusercontent.com/28705167/43817918-0cb5ff24-9b17-11e8-86c5-fd4d908f113a.png)
3. Worikng
![2018-08-08_14 24 01](https://user-images.githubusercontent.com/28705167/43817925-141a7bb4-9b17-11e8-9d11-771cf81fd52f.png)
4. Work has done.
![2018-08-08_14 25 06](https://user-images.githubusercontent.com/28705167/43817930-1bf1c59a-9b17-11e8-9511-4226472d8086.png)

Use quarryplus to flatten your world. (Other machines don't have this mode.)

**Comment by Unjustifiable** [comment]
Okay so I can use frame mode to dig holes in walls then?

**Comment by Kotori316** [comment]
I think you can do it.
Notice that you can't remove bedrock and other unbreakable blocks because ChunkDestroyer doesn't have frame mode.

**Comment by Unjustifiable** [comment]
Right, but what I mean is, in 'horizontal mode' like I was suggesting, the quarry would act like a tunnel bore and dig indefinitely in a straight pattern.

**Comment by Kotori316** [comment]
I won't implement it because it can make your save file too big. In normal world (default world creating), there is no bedrock or unbreakable block that stops quarry's horizontal mode work. It means quarry can't stop and load world infinitely.

**Comment by Unjustifiable** [comment]
Oh. Yeah I didn't think about that part.
