### ISSUE TITLE
server crash

### ISSUE THREAD

**Issue by bubblesayoyo** [Kotori316/QuarryPlus#3]
launched on my client fine but getting this during server start

[crash-2017-12-06_12.48.13-server.txt](https://github.com/Kotori316/QuarryPlus/files/1536291/crash-2017-12-06_12.48.13-server.txt)

**Comment by Kotori316** [comment]
I'm sorry for this inconvenience.
This is my mistake about Server and Client side problem.
I will fix this problem, but I don't have server environment and you may get further issues.
(I have never tested this mod in server environment.)
