### ISSUE TITLE
Advanced Pump Menu

### ISSUE THREAD

**Issue by OskarMZ** [Kotori316/QuarryPlus#310]
## Describe the bug

Unable to access the menu for the advanced Pump like in the screenshots for it's usage. Takes me directly to modules. Not sure if it's fault on my end as a video online shows its usage to disable the frame. But ingame I go directly to the modules part of the pump.

## Versions ATM8 1.19.2

* Minecraft version: [ATM8 1.19.2]
* Single Player or Multi Player?: [Single Player]
* Forge version: [43.2.14]
* QuarryPlus version: []
* Other mods: []

**Comment by Kotori316** [comment]
I forgot to update the screenshots in usage page. In 1.19.2, the screen for advanced pump is not implemented.

How to use in 1.19.2 pump

* To enable "deleting fluids", use Stick(the vanilla item, you know, used to create tools in crafting) to the pump.
* You can't change "frame mode". It's always on.
* To start the machine, send enough energy.

After the pump works for Water in the wide ocean, blocks(named "Dummy block") remain. I got some crash reports that complain breaking tooo many blocks in a tick cause crash, so please remove the block by yourself.

**Comment by Kotori316** [comment]
Do you want to disable frame? Then I'll add a way to configure it.

**Comment by OskarMZ** [comment]
Yes please. Trying to drain an ocean monument, I've walled of the area with sand meaning I can drain it and one hit click the frame and it gets destroyed (no surrounding water around the frame). But with a one block gap in the wall (I think due to underground tunnels) it causes the frame to generate outside the wall, meaning each frame has to be destroyed individually as it's touching the water, taking hours. 

I tried in creative to use the replacer module and replaced the water with "Dummy Blocks" so the frame wasn't generated. But I then realised there is no recipe in survival.

It would be extremely useful to be able to disable the frame entirely or some way to quickly destroy the frame blocks like using a wrench (currently using destruction gadget). Pic of why I'd like to disable the frame. 
![2024-01-03_13 35 58](https://github.com/Kotori316/QuarryPlus/assets/49291094/d59cc971-d6dc-490d-97f8-c49d229723ce)

**Comment by Kotori316** [comment]
Uploaded a new version for 1.19.2
