### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Andrey1661** [Kotori316/QuarryPlus#33]
Game crashes on startup with the following crash report. Tried versions 0.9.20 and 0.9.21
[crash-2018-09-30_18.05.53-client.txt](https://github.com/Kotori316/QuarryPlus/files/2431491/crash-2018-09-30_18.05.53-client.txt)

**Comment by Kotori316** [comment]
Use latest forge or newer than 14.23.4.2705
