### ISSUE TITLE
Filler only works with FE and not with E (fabric)

### ISSUE THREAD

**Issue by Pib-k** [Kotori316/QuarryPlus#339]
When using TechReborn, which uses E instead of E, the quarry works but the filler does not get energy from the machines, The filler does get energy from the Creative Generator from the QuarryPlus (this) mod.

**Comment by Kotori316** [comment]
I'll take a look. Which Minecraft version?

**Comment by Pib-k** [comment]
I'm on 1.20.1 (fabric)

**Comment by Kotori316** [comment]
Released a fixed version
https://www.curseforge.com/minecraft/mc-mods/additional-enchanted-miner/files/5123141
