### ISSUE TITLE
Ender Quarry-ish

### ISSUE THREAD

**Issue by Milii20** [Kotori316/QuarryPlus#34]
Greetings, first, i am loving the mod, and if possible i would like to make a suggestion

a quarry which works like the ender quarry from extra utilities in 1.7.10 (since i havent seen anyone making it again, and got replaced by the quantum quarry in extra utilities 2), it would be basically a normal quarryplus (maybe the basic version can be as fast as a fully enchanted quarry plus, and then you can place enchants on top of it?) but, everything it mines it replaces it with dirt and grass

maybe it can sit in a sort of middle of the road in cost between the quarryplus and the chunk destroyer?

Anyways, thank you!

**Comment by Kotori316** [comment]
Added replacer in 0.10.0.
You can download Jar from CurseForge.
To use replacer, read [this page](https://github.com/Kotori316/QuarryPlus/wiki/Replacer).
I think it is interesting to see world replaced to glass.
