### ISSUE TITLE
Causes client and server to crash

### ISSUE THREAD

**Issue by viktordimov** [Kotori316/QuarryPlus#361]
## Describe the bug

_Client crashed_

## To Reproduce

Install mod on client, run instance
Install mod on server, run instance
Server simply stops, no crash report produced

## Versions

* Minecraft version: [1.20.4]
* Single Player or Multi Player?: [single player]
* Fabric version: [0.15.6]
* QuarryPlus version: [20.4.56]
* Other mods: [[mods-list](https://pastebin.com/raw/U7DXzLDP)]

## Crash report or logs
[crash-report](https://pastebin.com/QrJ8VEJ2)

**Comment by Kotori316** [comment]
Thank you for your report, but you may have installed wrong file. Could you try to use the file in CurseForge?
I may have uploaded wrong file to Modrinth.

**Comment by Kotori316** [comment]
Fixed in 20.4.57-fabric
