### ISSUE TITLE
Enchantment energy coefficients: Confirming it doesn't work in Fabric.

### ISSUE THREAD

**Issue by isaiahshiner** [Kotori316/QuarryPlus#370]
I'm currently playing a 1.20.1 fabric modpack and adding this mod to it. I'm using alpha version `v20.1.1159-fabric`, which seems to be running fine.

It appears that the enchantment energy modifiers [mentioned in the original QuarryPlus](http://mcmods.yogpc.com/en_US/qp/Readme.html) _are_ implemented for Forge and NeoForge, but _not_ for Fabric. And not for 1.20.4 Fabric either.

The default config doesn't seem to require very much energy, and I was trying to increase it, but the enchanted quarry actually seems to use less energy than the normal quarry 😅

**Comment by Kotori316** [comment]
You can change energy configuration in config file. Change the value of `quarryEnergyBreakBlock` to higher, then quarry will require more energy.
I don't implement Enchantments-Coefficient option, as it's too complicated in calculation.

> the enchanted quarry actually seems to use less energy than the normal quarry

It's intended. Unbreaking will reduce the consumption of energy.
