### ISSUE TITLE
Starting chunk destroyer in mining dimension crashes server

### ISSUE THREAD

**Issue by dallman2** [Kotori316/QuarryPlus#376]
## Describe the bug

_What happened to you?_

every time we tried to start the chunk destroyer it instantly crashed out ATM9 server

## To Reproduce

1. place chunk destroyer in mining dimension
2. start machine

If your server/client has crashed, please give me the crash report.

## Versions

* Minecraft version: [1.20.1]
* Single Player or Multi Player?: [mp]
* Forge version: [47.2.20]
* QuarryPlus version: [?]
* Other mods: [ATM9 0.1.8]

## Crash report or logs

No logs were recovered. My suspicion is that it was a similar issue to this: 
https://www.reddit.com/r/allthemods/comments/1asodz3/chunk_destroyer_crashing_the_game_end_dimension/

EDIT: jk, i have the crash report...
[crash-2024-03-17_20.33.00-server.txt](https://github.com/Kotori316/QuarryPlus/files/14628886/crash-2024-03-17_20.33.00-server.txt)
[crash-2024-03-17_20.40.31-server.txt](https://github.com/Kotori316/QuarryPlus/files/14628887/crash-2024-03-17_20.40.31-server.txt)

**Comment by Kotori316** [comment]
I don't think the crash report is related to Quarry Plus. Some entity in the world might cause lag with calculating something.
