### ISSUE TITLE
[Suggestion] Add end stone to the list of voided common stone.

### ISSUE THREAD

**Issue by Kevin-Marsh** [Kotori316/QuarryPlus#395]
Adding End stone to the list of commonly voided stone would be beneficial and help players keep a cleaner mining setup.

**Comment by Kotori316** [comment]
Hi. Thank you for your suggestion.

In this case, you can use `Void Module` to remove items quarry mines. Right click with the item in your hand, then insert End Stone, and put the module into quarry's module inventory.
The mining machine holds module items when removed, so in next mining, you just put the machine and modules will be  installed.
