### ISSUE TITLE
drill pipes are not cleaned if the drill isn’t dig up

### ISSUE THREAD

**Issue by KiraLinux** [Kotori316/QuarryPlus#42]
if the drill did not start digging or did not dig to the end, then the drill pipe remains from it after the drill itself was removed

![2019-01-24_205504](https://user-images.githubusercontent.com/20641834/51698224-b89c4b80-201a-11e9-895d-750ede165553.png)
![2019-01-24_205902](https://user-images.githubusercontent.com/20641834/51698317-eb464400-201a-11e9-92bd-995f033d6bc2.png)
![2019-01-24_205906](https://user-images.githubusercontent.com/20641834/51698351-f9946000-201a-11e9-9556-28be75ecc062.png)

**Comment by Kotori316** [comment]
Added this function in 0.11.0
