### ISSUE TITLE
[Feature Request] Use partial tick for quarry 'arm' thing

### ISSUE THREAD

**Issue by Zepalesque** [Kotori316/QuarryPlus#424]
Currently, the quarry arm (or whatever it's called) seems to not use the partial tick value, which gives it a sort of choppy look.

My suggestion is to make it use the partial tick value, which should be as easy as storing the arm's location from the previous tick and linearly interpolating between the two with the partialTick value when rendering the arm.

**Comment by Kotori316** [comment]
I need to "store" the location of arm... Maybe it's needed only in client side, and not needed to save.

Thank you for your suggestion. I keep this issue open.

**Comment by Zepalesque** [comment]
yeah like as a client side value
vanilla does this with a lot of things, that may be helpful (for instance I think most living entities have both a head rotation value and a prev head rotation value, the prev one is set to the actual one at the beginning of the tick, before the head rotation gets updated, and then the renderer interpolates between the two)

**Comment by Kotori316** [comment]
memo

![image](https://github.com/Kotori316/QuarryPlus/assets/28705167/c3dd1679-fb78-4fd7-b7d4-1e7ade4729f0)
It seems I need to add some logic to reset head pos every tick.

**Comment by Kotori316** [comment]
OK, seems good
![image](https://github.com/Kotori316/QuarryPlus/assets/28705167/adc8ffd5-c3d2-407c-a08c-5ceb9b96ab04)
The orange line shows the position sent from server, and the blue line shows rendered position.

![image](https://github.com/Kotori316/QuarryPlus/assets/28705167/3dcdb4e0-8720-4004-ae5b-0b5f69c8a74c)
This figure shows the first period of quarry, moving the arm to block pos. Seems smooth!

**Comment by Kotori316** [comment]
Released for several version. Closing.
