### ISSUE TITLE
[Forge 1.20.1] JEI category shows up when using REI

### ISSUE THREAD

**Issue by vizthex123** [Kotori316/QuarryPlus#426]
## Describe the bug

As the title says, when using REI the JEI category for the Workbench Plus appears in the recipe menu

This one's ID says it's for REI:
![image](https://github.com/Kotori316/QuarryPlus/assets/31721920/06994fdb-10ab-4649-a69a-a010f244991a)

And this one's ID says it's for JEI:
![image](https://github.com/Kotori316/QuarryPlus/assets/31721920/a67fd168-0da8-407b-89f8-da928a4c97ad)

## To Reproduce

1. Install REI alongside this mod
2. Check the recipes for the Workbench Plus (or any item that's crafted in it)

## Versions

* Minecraft version: 1.20.1
* Single Player or Multi Player?: Singleplayer
* Forge version: 47.2.6
* QuarryPlus version: 1201.0.58
* Other mods: REI

## Crash report or logs
[latest.log](https://github.com/Kotori316/QuarryPlus/files/15370670/latest.log)

Not sure if you need this one, but i'll add it just in case
[quarry-debug.log](https://github.com/Kotori316/QuarryPlus/files/15370674/quarry-debug.log)

**Comment by Kotori316** [comment]
I don't know much about REI, but it seems I need to prevent JEI plugin loading. I'll take a look.

**Comment by vizthex123** [comment]
would be nice, thanks.

**Comment by Kotori316** [comment]
Confirmed. The "REI Plugin Compatibilities (REIPC)" mod loads JEI plugin. I'll find a way to disable JEI one.

**Comment by Kotori316** [comment]
Released fixed version.

**Comment by vizthex123** [comment]
noice, thanks.
