### ISSUE TITLE
After server restart, the quarry stops working unless a player is nearby

### ISSUE THREAD

**Issue by hozzdutch** [Kotori316/QuarryPlus#427]
I'm on 1.19.2. There appears to a problem with the quarry. I'm assuming it uses a chunk loader to keep the area it's mining in memory? When the server is restarted, the quarry only works if you're standing in the same area as it. Moving away from it, it'll stop working. The only way I've been able to get around this is every restart to pick up the quarry and then place it down again - especially annoying on a very large quarry when I have to place down the 3 markers every time.
Only a freshly placed quarry will continue to work when you move away from it (until a restart happens)

**Comment by Kotori316** [comment]
>  I'm assuming it uses a chunk loader to keep the area it's mining in memory?

Yes.

You can use Chunk Loaders from other mods. QuarryPlus uses a logic of chunk loading which might cause conflict with other systems. Your environment might have this kind of issue.

In my minimum environment, the chunk loading system works fine.
