### ISSUE TITLE
Chunk destroyer Question

### ISSUE THREAD

**Issue by Breadabix** [Kotori316/QuarryPlus#439]
Im using the chunk destroyer in 1.12 for the first time and love it, but I cant seem to get fluid out of it at all, ive tried BC pipes, fluiducts, mechanical pipes, ME fluid import busses and different tanks placed next to it with no result. Is there a known bug with this or am I missing something that should be obvious to me?

Edit: singleplayer and multiplayer

**Comment by Kotori316** [comment]
I think there is a config option related to fluid extraction of Chunk Destroyer.

**Comment by Breadabix** [comment]
The only option I can see if to disable fluid management on the chunk destroyer. I have done this and it still removed fluids but doesnt store them, just deletes them from existance. Its not the end of the world if there isnt any way around it  just thought id ask in case there was a known issue

**Comment by Kotori316** [comment]
OK, I tries in my environment.

1. Create a item called "LiquidSelector"
2. Right click the machine with the item
3. Click Add(FronList) and choose the fluid to extract. Just one. (See 1st Figure)
4. Connect pipe or something to extract fluid. The machine doesn't push any fluids, so use a pipe that can extract fluid, such as Ender IO conduit (2nd figure)

![2024-06-20_22 07 33](https://github.com/Kotori316/QuarryPlus/assets/28705167/cbdfd9b0-d586-48fb-b5b9-20c2f557a49c)
![2024-06-20_22 07 29](https://github.com/Kotori316/QuarryPlus/assets/28705167/cbbb8350-e863-48a6-83a7-84d4c298c47d)

**Comment by Breadabix** [comment]
Thanks for the help :)
