### ISSUE TITLE
Specific Workbench Plus recipe configurability

### ISSUE THREAD

**Issue by WrongWeekend** [Kotori316/QuarryPlus#44]
I don't see any mention of this mod in the Crafttweaker wiki, and the config does not seem to offer a way to control specifically which items a machine requires to build using the workbench. Some sort of way to control exactly which items and how many of each are required to build each machine would be useful.

**Comment by Kotori316** [comment]
I wrote how to write script in [this page](https://github.com/Kotori316/QuarryPlus/wiki/CTRecipe).
