### ISSUE TITLE
Crash on server startup

### ISSUE THREAD

**Issue by Xplodin** [Kotori316/QuarryPlus#441]
## Describe the bug

_What happened to you?_
Server go crash
## To Reproduce
Custom modpack with connector and tons of others. Seems to not work after trying to update my pack

1. start server
2. get to end of starting cycle
3. crash after world is generated
4. 

If your server/client has crashed, please give me the crash report.
[crash-2024-06-16_18.00.03-server.txt](https://github.com/user-attachments/files/15860005/crash-2024-06-16_18.00.03-server.txt)

## Versions
[crash-2024-06-16_18.00.03-server.txt](https://github.com/user-attachments/files/15860005/crash-2024-06-16_18.00.03-server.txt)

* Minecraft version: [1.20.1]
* Single Player or Multi Player?: [SERVER]
* Forge version: [47.2.19]
* QuarryPlus version: [1201.1.64]
* Other mods: [you dont wanna see this, its too long and its in the crash report]

## Crash report or logs
https://gist.github.com/Xplodin/e6820baf3410a67bf0c5ced9f112edb5
If your Minecraft has crashed, please attach the crash report. Please use pastebin or just paste the report.

**Comment by Kotori316** [comment]
I released a new version. It might fix this issue.
