### ISSUE TITLE
Quarry will not accept energy from any source or side [NFORGE 1.20.4]

### ISSUE THREAD

**Issue by Shadowevil015** [Kotori316/QuarryPlus#444]
## Describe the bug

_What happened to you?_

## To Reproduce

1. Place a quarry plus
2. Place it down
3. Attempt to power it with anything (e.g mekanism, energized power, powah!, ae2)
4. Quarry does nothing

If your server/client has crashed, please give me the crash report.
N/A

## Versions

* Minecraft version: 1.20.4
* Single Player or Multi Player?: Multiplayer
* Neoforge version:  20.4.237
* QuarryPlus version: 20.4.57
* Other mods: Custom modpack (long list)

## Crash report or logs

If your Minecraft has crashed, please attach the crash report. Please use pastebin or just paste the report.

**Comment by Shadowevil015** [comment]
Note that using the QuarryPlus creative generator makes the quarry work. :)

**Comment by Kotori316** [comment]
I don't think I did anything to follow changes in NeoForge capability system. I'll take a look

**Comment by Shadowevil015** [comment]
Thanks! I really appreciate the quick fix!! <3

**Comment by Kotori316** [comment]
(Not released yet. CI is running)

**Comment by Shadowevil015** [comment]
I think it might have failed

**Comment by Kotori316** [comment]
I'll run release script from my local environment. Just a moment.

**Comment by Kotori316** [comment]
OK, released as `20.4.69-neoforge`. Modrinth download is available. Curse needs to be reviewed.
https://modrinth.com/mod/additional-enchanted-miner/version/20.4.69
