### ISSUE TITLE
[TEXTURE] Is it possible to reduce the number of pixels in the "quarryplus:block/mod_quarryplus" texture?

### ISSUE THREAD

**Issue by Lolothepro** [Kotori316/QuarryPlus#446]
Currently, it has a resolution of 512x512, which takes up a lot of space in a texture atlas, and consumes VRAM for the texture. Would it be possible to make the texture smaller?

![image](https://github.com/Kotori316/QuarryPlus/assets/68275908/cb5c1e68-f45c-4b29-ad88-5600ae862b63)

**Comment by Kotori316** [comment]
No benefit for me. Also, you can override the texture with resource packs.
