### ISSUE TITLE
Frame mode stopped halfway

### ISSUE THREAD

**Issue by Kalman11** [Kotori316/QuarryPlus#45]
I've got some problems with my QuarryPlus. It stopped making the frame halfway. It's in frame mode, it is getting about 1500-1600RF/t and it doesn't move. I'm using Magmatic Dynamos to power it with EnderIO conduits.

https://imgur.com/a/qENu01X

I'm using latest version (0.11.2)

**Comment by Kotori316** [comment]
I left comment, https://minecraft.curseforge.com/projects/additional-enchanted-miner#c69.
I can't reproduce your problem in my development environment so I can't get what was wrong.

**Comment by Kotori316** [comment]
Left comment, https://minecraft.curseforge.com/projects/additional-enchanted-miner?comment=71
Try [1.0.1](https://minecraft.curseforge.com/projects/additional-enchanted-miner/files/2677471).
