### ISSUE TITLE
Filling in an Area with a lot of already filled blocks creates a lot of lagg (Fabric 1.20.4)

### ISSUE THREAD

**Issue by Pib-k** [Kotori316/QuarryPlus#450]
Singleplayer
Fabric 1.20.4

Wanted to fill in caves in a large area (133 x 133 x 128) with the filler, however this creates a lot of lag. My theory is that checking the skipped Arraylist for each position is mostly the cause of this lag. Using a Hashset instead of an ArrayList might improve performance. I could write a PR if you are interested.

**Comment by Kotori316** [comment]
The collection itself is not the problem. I think I wrote code to check the skipped list every tick, however I should do it every 20s or at the end of work.

**Comment by Pib-k** [comment]
Ahh yeah that makes sense, if you need help with the workload let me know!

**Comment by Kotori316** [comment]
I'll release a new version. Just a moment.
