### ISSUE TITLE
Can't find the mod for 1.20.1 for FABRIC

### ISSUE THREAD

**Issue by StarWeizz** [Kotori316/QuarryPlus#457]
## Describe the bug

_What happened to you?_
I can't find quarryplus mod for fabric in 1.20.1

## Versions

* Minecraft version: [1.20.1]
* Single Player or Multi Player?: [Multiplayer]
* Forge version: [no, fabric]

**Comment by Kotori316** [comment]
https://modrinth.com/mod/additional-enchanted-miner/version/20.1.1159
