### ISSUE TITLE
Can't connect pipe to pump plus

### ISSUE THREAD

**Issue by xardius** [Kotori316/QuarryPlus#459]
## Describe the bug

I am not able to connect a mekanism mechanical pipe to the pump plus module.
The same pipe connects just fine to the advanced pump

## To Reproduce

1. Place a Quarry Plus
2. Place a Pump Plus next to it
3. Try to connect the fluid pipe to the pump plus module like mentioned in the wiki

If your server/client has crashed, please give me the crash report.

## Versions

* Minecraft version: 1.20.1
* Single Player or Multi Player?: Single Player
* Forge version: 47.1.106 (Neo)
* QuarryPlus version: 1201.1.66
* Other mods: Mekanism 10.4.8

Advanced Pump vs. Pump plus
![grafik](https://github.com/user-attachments/assets/2179960b-7ba6-49de-9178-b653e4cc5afd)

**Comment by Kotori316** [comment]
Connect to the quarry. Pump plus doesn't have fluid storage.

**Comment by xardius** [comment]
Thank you. I guess your wiki is wrong then? Or did I misunderstood the pictures there?

**Comment by Kotori316** [comment]
Yes, the picture in wiki is wrong. It's something in 1.12.2 era. The last change is 2018.
