### ISSUE TITLE
1.20.1 Server Crashing - Corrupted Chunk

### ISSUE THREAD

**Issue by Kowantify** [Kotori316/QuarryPlus#460]
## Describe the bug
Server crashing
Quarry is mining, and once it hits a specific level the server crashes, I've restored some backups and it crashes in the same error with a "ticking block entity error"

## To Reproduce

1. Place down Quarry
2. Let Quarry mine for a while (I did a 10x20x20 area)
3. Crashes at some random level, I do have a lot of mods installed currently but was hoping this is something that can be fixed as this modpack is used by a number of users, I'd hate to corrupt more worlds.

If your server/client has crashed, please give me the crash report.
[crash-2024-07-25_19.46.40-server.txt](https://github.com/user-attachments/files/16385324/crash-2024-07-25_19.46.40-server.txt)

## Versions

* Minecraft version: [1.20.1]
* Single Player or Multi Player?: [Multiplayer]
* Forge version: [47.3.0]
* QuarryPlus version: [1201.1.66]
* Other mods: [A lot of mods (270+ mods)]

## Crash report or logs

If your Minecraft has crashed, please attach the crash report. Please use pastebin or just paste the report.

I apologize about the large amount of mods, I understand removing all of them and only having the quarry would probably fix the issue, but this modpack has been running for about a month and we just stumbled into this.

Thanks!

**Comment by Kotori316** [comment]
Something is wrong in the save data...? I'll add a workaround, but it might skip some blocks.

**Comment by Kowantify** [comment]
I will test the Quarry in the exact same location it had crashed from, and will report back with findings.

Thank you!

**Comment by Kowantify** [comment]
Tested and verified server did not crash in the same area, I think that solved it!

**Comment by Kotori316** [comment]
Thank you for reporting.
[v1201.1.80-forge](https://modrinth.com/mod/additional-enchanted-miner/version/1201.1.80)
