### ISSUE TITLE
Can't add seconds Void Module to Quarry

### ISSUE THREAD

**Issue by xardius** [Kotori316/QuarryPlus#470]
## Describe the bug

In the Wiki you stated that Machines can accept multiple void modules. However I am unable to add a second module to my Quarry.

## To Reproduce

1. add one Module to the Quarry -> works fine
2. try to add second module -> not possible, neither via drag and drop or right click.

If your server/client has crashed, please give me the crash report.

## Versions

* Minecraft version: 1.20.1
* Single Player or Multi Player?: Single Player
* Forge version: 47.1.106 (Neo)
* QuarryPlus version: 1201.1.80
* Other mods:
AdditionalEnchantedMiner-1.20.1-1201.1.80.jar
alexsmobs-1.22.8.jar
animal_feeding_trough-1.1.0+1.20.1-forge.jar
appleskin-forge-mc1.20.1-2.5.1.jar
Applied-Mekanistics-1.4.2.jar
appliedenergistics2-forge-15.2.11.jar
architectury-9.2.14-forge.jar
automaticdoors-1.20.1-4.6.jar
azure-paxels-neo-1.20.1-1.0.6.jar
balm-forge-1.20.1-7.3.6-all.jar
BetterF3-7.0.2-Forge-1.20.1.jar
Bookshelf-Forge-1.20.1-20.2.13.jar
BotanyPots-Forge-1.20.1-13.0.36.jar
caelus-forge-3.2.0+1.20.1.jar
charmofundying-forge-6.5.0+1.20.1.jar
citadel-2.5.6-1.20.1.jar
cloth-config-11.1.118-forge.jar
Clumps-forge-1.20.1-12.0.0.4.jar
collective-1.20.1-7.77.jar
comforts-forge-6.4.0+1.20.1.jar
compact-storage-1.20.1-forge-6.0.1.70.jar
cristellib-1.1.5-forge.jar
cupboard-1.20.1-2.7.jar
curios-forge-5.9.1+1.20.1.jar
disenchanting_table-forge-1.20.1-3.0.1.jar
doubledoors-1.20.1-5.7.jar
EasyAnvils-v8.0.2-1.20.1-Forge.jar
EasyMagic-v8.0.1-1.20.1-Forge.jar
elytraslot-forge-6.4.2+1.20.1.jar
embeddium-0.3.28+mc1.20.1.jar
EnchantingInfuser-v8.0.3-1.20.1-Forge.jar
enderchests-forge-1.20.1-1.2.jar
endertanks-forge-1.20.1-1.3.jar
endportalrecipe-1.20.1-5.2.jar
ExplorersCompass-1.20.1-1.3.3-forge.jar
extendedbonemeal-1.20.1-3.4.jar
fastercrouching-1.20.1-2.5.jar
ferritecore-6.0.1-forge.jar
FiltPick-forge-mc1.20.1-0.0.2.jar
flatbedrock-forge-3.0.1-build.18+mc1.20.1.jar
ForgeConfigScreens-v8.0.2-1.20.1-Forge.jar
ftb-chunks-forge-2001.3.1.jar
ftb-library-forge-2001.2.4.jar
ftb-teams-forge-2001.3.0.jar
fullbrightnesstoggle-1.20.1-4.1.jar
glowingores-1.20.1-2.9.jar
grassseeds-1.20.1-3.2.jar
gravelminer-forge-1.20-16.0.2.jar
gravestone-forge-1.20.1-1.0.17.jar
hideexperimentalwarning-1.20.1-1.1.jar
Incendium_1.20.x_v5.3.5.jar
ironfurnaces-1.20.1-4.1.6.jar
Jade-1.20.1-forge-11.9.4.jar
jei-1.20.1-forge-15.8.0.16.jar
jei-1.20.1-forge-15.8.2.23.jar
JustEnoughMekanismMultiblocks-1.20.1-4.4.jar
keepmysoiltilled-1.20.1-2.3.jar
liste.txt
Mekanism-1.20.1-10.4.8.43.jar
MekanismGenerators-1.20.1-10.4.8.43.jar
MekanismTools-1.20.1-10.4.8.43.jar
mineralchance-1.20.1-3.6.jar
MobCapturingTool-forge-1.20.1-3.0.2.jar
modernfix-forge-5.19.0+mc1.20.1.jar
monolib-forge-1.20.1-1.3.0.jar
MouseTweaks-forge-mc1.20.1-2.25.1.jar
NaturesCompass-1.20.1-1.11.2-forge.jar
Nullscape_1.20.x_v1.2.7.jar
oculus-mc1.20.1-1.7.0.jar
oreharvester-1.20.1-1.3.jar
PickUpNotifier-v8.0.0-1.20.1-Forge.jar
PuzzlesLib-v8.1.21-1.20.1-Forge.jar
redstonepen-1.20.1-neoforge-1.3.33.jar
right-click-harvest-3.2.3+1.20.1-forge.jar
ScalableCatsForce-3.3.1-build-0-with-library.jar
shetiphiancore-forge-1.20.1-1.3.jar
stackrefill-1.20.1-4.4.jar
Structory_1.20.x_v1.3.5.jar
Structory_Towers_1.20.x_v1.0.7.jar
supermartijn642configlib-1.1.8-forge-mc1.20.jar
supermartijn642corelib-1.1.17-forge-mc1.20.1.jar
Terralith_1.20.x_v2.5.4.jar
TinyCoal-forge-1.20.1-1.1.5.jar
Towns-and-Towers-1.12-Fabric+Forge.jar
TrampleStopper-Forge-5.0.0+mc1.20.1.jar
trashcans-1.0.18b-forge-mc1.20.jar
trashslot-forge-1.20-15.1.0.jar
treeharvester-1.20.1-8.7.jar
trenzalore-forge-3.3.10+mc1.20.1-all.jar
Uppers-1.0.1.jar
VisualWorkbench-v8.0.0-1.20.1-Forge.jar
warp-portals-1.4.0.jar
whatdurability-1.20.1-1.0.jar
wso16-forge-1.1.jar
xptome-1.20.1-2.2.1.jar
[1.20.1][forge47.1.0]mod_PickupWidelySMP_v1.2.4.jar

**Comment by Kotori316** [comment]
Maybe I forgot to add Void Module to "ignore" list for counting modules...

**Comment by Kotori316** [comment]
Fixed in the latest version
