### ISSUE TITLE
Silk Touch and Fortune

### ISSUE THREAD

**Issue by Marius8** [Kotori316/QuarryPlus#51]
In the original version you were able to move Silk Touch AND Fortune onto the QuarryPlus machines.
That way, on the quarry, you were able to select, which blocks were supposed to be mined with silk touch, and which to be mined with fortune, using the ListEditor.
the PumpPlus, too has different (non exclusive) effects for these enchantments.
It is not possible to do so in the current 1.12.2 build.

**Comment by Kotori316** [comment]
Try [1.0.6](https://minecraft.curseforge.com/projects/additional-enchanted-miner/files/2716844).

You can move both Fortune and Silktouch to QuarryPlus. (Is this what you want?)

Use ListEditor **with Silktouch** (not Fotrune, because of the order in code to apply enchantment) to EXCLUDE blocks you want to apply fortune.

PumpPlus can't be enchanted with both Fortune and Silktouch at the same time but, in fact, fortune has no effect. You should add Unbreaking and Silktouch to PumpPlus to work it effectively. (See [this page](https://github.com/Kotori316/QuarryPlus/wiki/EnchantMover#effects) to get how enchantments works.)

**Comment by Marius8** [comment]
I don't know, if you changed the behavior of the PumpPlus in your edition, but in the [Readme](http://mcmods.yogpc.com/en_US/qp/Readme.htmlhttp://mcmods.yogpc.com/en_US/qp/Readme.html) of yogpstop, you find this text on the PumpPlus:

> You can get liquids if you place it next to MiningWellPlus or QuarryPlus.
> At default, liquid is volatilized in re login.
> Unbreaking Enchant produce working with less energy.
> Fortune enchant produce drain bigger area liquids.
> Silktouch enchant produce liquid is not volatilized in re login.

so, unless you changed some behavior here, both should be possible.
going to be testing the new version in the next days, as i am in the process of updating mods on a Private server.

**Comment by Kotori316** [comment]
I'll release a new version, in which you can add the 3 enchantments to PumpPlus.

Do you know how fortune affect on PumpPlus's work? It does nothing when you use the machine as an attachment of QuarryPlus, just draining fluid in quarry area. Right click PumpPlus wih fortune before quarry starts to work to change Pump's mode and find what happens. 

As for silktouch, the original readme said 
> liquid is not volatilized in re login.

This means fluids in PumpPlus is saved to nbt when you leave the world. If you transfer all fluids in pump with pipes or tanks, fluid is saved in the pipes or tanks and there are no need to hold data in pump. Silktouch is useful if you don't pull fluids immediately and you want to back to main menu.

**Comment by Marius8** [comment]
no clue, on how it is written, but when fortune was on the PumpPlus, it drained the whole layer of connected water/lava/'whatever fluid', when on max enchant, with max-range configured (for this situation sadly, i never went with less than max enchant).
maybe, that enchant, only has an effect, when used in combination with the MiningWellPlus, tho.. (never used it..
as for silktouch, this is more important for me, regarding server-shutdown, or crash, and siktouch is working correctly.

**Comment by Kotori316** [comment]
Updated [1.0.7](https://minecraft.curseforge.com/projects/additional-enchanted-miner/files/2717290).

I noticed that PumpPlus with Fortune, connected QuarryPlus, can drain fluid in larger area than quarry's dig area. See the screen shot.
![2019-05-29_19 43 27](https://user-images.githubusercontent.com/28705167/58558769-a0546b80-825c-11e9-9714-b3e3e1efc485.png)
![2019-05-29_19 42 23](https://user-images.githubusercontent.com/28705167/58558770-a0546b80-825c-11e9-9ec6-9555f9f7d250.png)
