### ISSUE TITLE
Are you taking textures?

### ISSUE THREAD

**Issue by onyxromero** [Kotori316/QuarryPlus#52]
Would you like some help with textures? If I have time maybe I could make some for you. :)

**Comment by Kotori316** [comment]
Yes. Thank you for your helping.

**Comment by Unjustifiable** [comment]
> 
> 
> Yes. Thank you for your helping.

All right, I'll see what I can come up with. Happy to help you in your work. :)

**Comment by onyxromero** [comment]
Retexturing in progress.
