### ISSUE TITLE
(enhancement) make mobs hostile to the quarry head

### ISSUE THREAD

**Issue by Heatwu** [Kotori316/QuarryPlus#522]
make mobs hostile to the quarry head, if the head is hit then progress is halted for 10-20 sec
add as optional config

**Comment by Kotori316** [comment]
Thanks for the suggestion! We appreciate you taking the time to share your ideas for improving the game. However, we've decided not to implement mob hostility towards the quarry head at this time. We'll keep this feature in mind for future updates.

We believe that this feature might not align with the core playing experience we're aiming for.
