### ISSUE TITLE
Suggestions/Enhancements

### ISSUE THREAD

**Issue by onyxromero** [Kotori316/QuarryPlus#53]
1. Combine Solid Fuel Quarry and Powered Quarry into one block.

So, keeping the original Solid Quarry as an early game option, what if, when you got the Powered Quarry you could power it with Solid Fuels the same way? The fuel it burns would fill up an Internal Power Buffer as it burns, a Buffer that can't be extracted from, only inserted into.

2. Modules

Instead of having dedicated blocks that you have to place down next to the Quarry, why not replace them with Module Items? Like for instance, in other mods you'd right click on the machine and open a GUI, then it would have Upgrade Slots. Well, in Additional Enchanted Miner, why not have slots in the machines where you can install them as Modules? Also, why not have the Modules work in more than just the Quarry, like for Example, say you turn the QuarryPump into a "Pump Module", What if you could insert that into the Mining Well? If the Mining Well strikes Water or Lava, why not have the Mining Well suck it up into an internal tank only enabled by the Pump Module?

3. Experience Pump Changes

So, this kind of goes with the second suggestion, since the Experience Pump sucks up Experience Orbs, why not have it convert the Experience Orbs into xpjuice that can be pumped out of the Machine with the additional functionality that you can press a button within the machine's GUI to get all the Experience Stored in the Machine? The machine could have two different Fluid Tanks, one for regular fluids, the other for xpjuice.

4. Enchantment Slots in Machines

So, it's great to be able to have the EnchantMover Blocks, but what if instead of having to use a dedicated block to move the Enchantments over and over again, why not add Slots in the machines to add Enchantments to it? Say you can only apply up to 3 Enchantments at once per Machine to make it Balanced. Like, you can only insert 3 different enchanted books at one time.

5. Y-Setter Changes

Instead of having a Y-Setter item, why not have the ability to change the Y level within the Machine's GUI? Also, showing the current Y level within the Machine's GUI would also be a nice change.

6. Name Change.

Okay, so, since QuarryPlus or Additional Enchanted Miner is no longer an addon for Buildcraft and the mod is kind of swaying away from BC, why not name it something else that reflects what the mod actually is? Additional Enchanted Miner implies it's an Addon for a Mod rather than a Standalone Mod with no dependencies.

That's all from me for now. :)

**Comment by Kotori316** [comment]
1. This is the case I should use module system. Quarry requires very large amount of energy that can't be produced by just one generator, so few user use solid fuel instead of connecting energy pipe.

2. Very smart, but not explicit and difficult to tell usage. Just placing attachment next to machine or installing module, setting is saved when broken, clicking the icon in GUI to open setting... Which is simple?
The module idea is worth implementing, but I don't want to remove the idea origial author had. I'll use the both methods.

3. I don't know the conversion rate. And how to choose xp fluid, like one from CoFHCore and from Ender Core? You can get all xp by breaking the machine.

4. Enchantments should not be extracted, as vanilla intended, and it's more difficult to get enchantment book of Efficiency, Fortune, Silktouch than to get a pickaxe with these enchantments. One more, items in GUI slot is easy to be  deleted if you get a crash.

5. It is done if I use odule system. My basic idea is easy to access the setting GUI. It's difficult for users to understand how to change configuration if GUI has deep structure.

6. This mod is actually standalone, but the idea is taken from BluidCraft. I don't lose respect for them.

**Comment by onyxromero** [comment]
Also, will whatever changes you end up doing be backported to 1.12.2?

**Comment by Kotori316** [comment]
I'll transport changes in current branch to 1.12.2 version after finishing implementation.

**Comment by onyxromero** [comment]
Going forward with the option to use Modules OR Attachments is smart. So with that being said, will there be a configuration to turn off or on both Methods?

**Comment by onyxromero** [comment]
Also, I suggest changing the name of the "PumpPlus" to "Quarry Fluid Storage" as well as changing the name of the "Experience Pump for Quarry" to "Quarry Experience Storage". Then, you can rename the Standalone Pump to "Pump Plus", this will distinguish the attachments/modules from the Standalone Machines.

**Comment by Kotori316** [comment]
1. I've added disable option in config for each machine. I won't give option to turn off a method of enhancing quarry's work. Disabling all module items or all attachment machines will be equal to your suggestion.
2. I'm rewriting all code for quarry and I added both fluid and item storage. The work is almost done expect implementing GUI of container and module as an item. Then, the PumpPlus only removes fluids in world, does not works as a fluid storage. The module item name will be "Pump Module", "Replace Module" or "Exp Collect Module" or something like these.
I won't change names of attachment blocks.

**Comment by onyxromero** [comment]
1. That's exactly what I meant by turning off or on both methods. Disabling attachments or module items.

2. That is excellent news.

3. I would assume the modules would also work in the Chunk Destroyer, since it's basically just an advanced QuarryPlus that mines a row of blocks at a time?

4. The new textures are 50% complete. How do I get them to you for review?

**Comment by Kotori316** [comment]
I've not started working for module system of Chunk Destroyer. Now the machine works correctly, but no module system installed. The work will be started after I finish works for normal Quarry Plus.

As for your textures, if you have git, please commit to your branch and make pull request. If not, make zip and attach to this thread.

**Comment by Kotori316** [comment]
Uploaded 12.2.0 on CurseForge, which has new quarry.
Basic works for quarry is finished but it may have a lot of bugs. So be careful to install the mod. In my environment, it caused a crash and the world is no longer available.

**Comment by Kotori316** [comment]
Close as module system is added to Chunk Destroyer.
