### ISSUE TITLE
Is a virtually unlimited internal buffer a bug or a feature?

### ISSUE THREAD

**Issue by alexipeck** [Kotori316/QuarryPlus#535]
I count ~600k items visible in the buffer, but I'm assuming it can only show so much. I have an EnderChests Ender Chest on top, my system on the other end was full, but it just kept mining.
![2024-08-15_22 15 23](https://github.com/user-attachments/assets/a48c1f9e-ccb9-48e2-8f0d-71c3cb7040ec)

I tried looking for documentation prior to creating this issue, but can't seem to find any.

**Comment by Kotori316** [comment]
It's intended in all version, platform.

Quarry can hold all items it mined. The items are saved in world, so kept in loading/unloading the world. However, you can't get items if you remove the Quarry block. Then items will go to the void.
