### ISSUE TITLE
AdditionalEnchantedMinerBuilding Mods Stage Crash 1.0.9 MC 1.22.2 

### ISSUE THREAD

**Issue by AbrahamArmasCordero** [Kotori316/QuarryPlus#55]
Crash report https://gist.github.com/AbrahamArmasCordero/2ce2f73291a32771cf583ecb6678f7bf

BC 7.99.23
Forge 14.23.5.2768

**Comment by AbrahamArmasCordero** [comment]
Sorry ill edit now im trying to upload the gist

**Comment by AbrahamArmasCordero** [comment]
Im going to try to go a previus version of the mod for 1.12.2 maybe its the current build of buildcraft so if i try a previus one it will work?

**Comment by onyxromero** [comment]
You're using an alpha version of buildcraft, which is highly unstable. I recommend updating to version 7.99.24 and seeing if that helps. I doubt the problem is QuarryPlus related.

https://minecraft.curseforge.com/projects/buildcraft/files/2702041

**Comment by AbrahamArmasCordero** [comment]
Done, Didn't work :/ Updated the gist with the second crash report after installing new BC 7.99.24.1

**Comment by onyxromero** [comment]
What version of forge are you using?

**Comment by AbrahamArmasCordero** [comment]
Forge 14.23.5.2768

**Comment by onyxromero** [comment]
Try updating to 14.23.5.2836

**Comment by AbrahamArmasCordero** [comment]
Doing it let me 10 minutes to test it :D i'll edit this message

**Comment by onyxromero** [comment]
Well there ya go. Hope I helped. :)

**Comment by AbrahamArmasCordero** [comment]
It works now but this forge version appear to consume much more ram. But your mod now works perfectly Thanks :D

**Comment by onyxromero** [comment]
Not my mod, I just contribute suggestions and I've been given permission to make textures for Kotori. Tbh, most of the stuff that is in the mod has stemmed from suggestions of mine. Kotori316 is the only person that is maintaining the code of this mod and constantly improving it whenever he has time. If I knew Java and minecraft modding fluently, I'd offer to help out with the coding.

**Comment by Kotori316** [comment]
Thanks Unjustifiable for answering. This crash is caused by [this commit](https://github.com/Kotori316/QuarryPlus/commit/272a28bcf97149a24f79f3411a1b6f866b5db518), which changed the way to get method in games.

@AbrahamArmasCordero I'll build a version for forge 14.23.5.2768, reverting critical changes of usage of forge API.

**Comment by Kotori316** [comment]
@Kotori316 TODO
1. Build an environment of forge 14.23.5.2768. Be careful this is for Minecraft 1.12.2.
2. revert commit 272a28bcf97149a24f79f3411a1b6f866b5db518
3. Test run.
4. Call build script.

**Comment by AbrahamArmasCordero** [comment]
Yay thanks and don't worry i was just pointing a silly thing actually yesterday by testing (because the performance with Forge 14.23.5.2836 went down so much) and with just the previous version it goes smooth as silk. 

And sorry i wasn't pointing out that you mod is inefficient i was just pointing that with the new forge it appeared to consume much more because its a beta version i think .

The mod is great it solves the limitations of the normal bc quarry for ppl that dont want those limitations :D 

you can close this now if you think it is solved or if you want me to test it with the 2768 i will gladly do it.

**Comment by Kotori316** [comment]
Uploaded file for forge 2768. Change the extension to jar and try it.
[AEM-1.12.2-1.0.9-2768.zip](https://github.com/Kotori316/QuarryPlus/files/3321560/AEM-1.12.2-1.0.9-2768.zip)

**Comment by AbrahamArmasCordero** [comment]
hey man, sorry i forgot about this, just tested it with forge 2768 works perfectly

**Comment by AbrahamArmasCordero** [comment]
btw i post it here because i dont know if it actually a bug or not
i couldnt seee the recipes untill i pasted the default recipes into the recipes folder, i dont know if thats okey i could do another issue

**Comment by Kotori316** [comment]
Good to here the file works better.

You can post anything about this mod to GiuHub issue page, but I think the comment area in CurseForge isn't a place to post crash logs. Even if you don't know quarry works as intended, you can post a question or bug report to this page.

**If you have another issue, please open a new issue**.
