### ISSUE TITLE
Quarry head resets to 0,0 on every log off

### ISSUE THREAD

**Issue by Dener007** [Kotori316/QuarryPlus#550]
Every time I save and close the world, after I log back on the quarry head is on XYZ 0,0,0.  When checking it with the status checker I can confirm it is ad 0,0. it will fly back to the location of the active quarry. but this takes a few minutes because it will fly back at normal operating speed.

* Minecraft version: 1.19.2
* Single Player 
* Forge version: 43.4.0

**Comment by Kotori316** [comment]
I forgot to read the head data from NBT...

**Comment by Kotori316** [comment]
Fixed in the latest version
