### ISSUE TITLE
1.20.1 workbench gets free power?

### ISSUE THREAD

**Issue by jaz000** [Kotori316/QuarryPlus#578]
## Describe the bug

The workbench slowly gains power even with no power source connected. About 5FE/t I think. Adding additional power is still working
the config has NoPower=false
Is there anyway to configure this so that the workbench requires power?
thanks

## To Reproduce

Steps to reproduce the behaviour:

1. put down workbench
2. add ingredients
3. select output
4. watch it slowly get made for free

If your server/client has crashed, please give me the crash report.

## Versions

* Minecraft version: [1.20.1]
* Single Player or Multi Player?: [single]
* Forge version: [47.3.0]
* QuarryPlus version: [AdditionalEnchantedMiner-1.20.1-1201.1.90.jar]
* Other mods: [All of them - also experiencing this this with the latest All The Mods 9 pack, well version 0.3.0 from a couple of weeks ago ...]

**Comment by Kotori316** [comment]
Yes, it gets 5FE/t. I don't remember why I added, but I think I got a report of failure to supply energy to Workbench.
Machines require 100k FE or more, so it takes a few hours to create machine with 100FE/s.
