### ISSUE TITLE
[1.12.2] QuarryPlus Modules are non-functional

### ISSUE THREAD

**Issue by onyxromero** [Kotori316/QuarryPlus#59]

**Comment by Kotori316** [comment]
I added completely new block, called QuarryPlus, with quarryplus:quarry as registry name. I didn't replace the old one, with quarryplus:quarryplus as registry name, to avoid bugs from NBT incompatibility. These 2 have the same textures so you can distinguish them by names.

The new one has GUI you can open just by right click. Old one doesn't.
Did your new quarry show GUI?

**Comment by onyxromero** [comment]
It shows the GUI but like, the modules themselves don’t work in the new block, like the quarry doesn’t pump fluids, the replacer module doesn’t replace blocks, and the XP module doesn’t work

**Comment by onyxromero** [comment]
Like you can insert the modules but the modules don’t actually  do anything, and this is with just the quarry plus mod itself installed and Mekanism

**Comment by Kotori316** [comment]
I took a mistake on checking the module is disabled in config.
Change the config, DisableXXXModule to **true** and try again.

I'll release fixed version.

**Comment by Kotori316** [comment]
You can get fluid from new quarry just placing tank next to the quarry.

**Comment by Kotori316** [comment]
Config issue is fixed in v12.2.1 and extracting with pipe is implemented in v12.2.2
