### ISSUE TITLE
[Suggestion] Plus Machine Torch Placer Module

### ISSUE THREAD

**Issue by onyxromero** [Kotori316/QuarryPlus#61]
So, we all know that once the Quarry is done, it leaves a HUGE hole in the ground, which, if you're using the Quarry underground can be a breeding ground for Monsters. How the Torch Placer Module would work is once the Quarry Reaches the bottom layer or whatever layer was set on the Y Setter is it would place Torches on that layer where the light level is on or below light level 7.

**Comment by Kotori316** [comment]
![2019-08-15_23 09 57](https://user-images.githubusercontent.com/28705167/63101049-40e03f00-bfb3-11e9-98f1-86dbbfa1c5a3.png)
Quarry, inserted torch module, places torch like this picture. (Taken in MC 1.12.2)
Implemented in [v12.2.3](https://www.curseforge.com/minecraft/mc-mods/additional-enchanted-miner/files/2762512)
