### ISSUE TITLE
[1.21.1][NEOFORGE] Quarry and chunk destroyer void power

### ISSUE THREAD

**Issue by ThatElektrika** [Kotori316/QuarryPlus#626]
## Describe the bug

_Whenever I power a quarry or chunk destroyer, ALL incoming power gets voided. The quarry/C.D. accepts more power than it can hold, and to test this I used a nitro energy cell from Powah that was COMPLETELY FILLED and the entire thing was draining at 2M rf/t, which neither the quarry nor the C.D. needs to operate. This has caused a lot of issues, because it also seems to bypass the limits of energy pipes from Pipez which is a bit strange._

## To Reproduce

1. Just...power it with a full energy cell from Powah

## Versions

* Minecraft version: [1.21.1]
* Single Player or Multi Player?: [Both]
* Neoforge version: [21.1.65]
* QuarryPlus version: [21.1.105]
* Other mods: [TNP Limitless 8 modpack, but also does this with only Powah and Pipez installed]

**Comment by Kotori316** [comment]
I'll take a look

**Comment by Kotori316** [comment]
It works in my env.
![2024-10-12_00 21 36](https://github.com/user-attachments/assets/91e8125a-f96c-4d39-bd01-53f6c202f059)

**Comment by Kotori316** [comment]
If you have more info or question, please post.

**Comment by ThatElektrika** [comment]
Based on your image, you clearly seem to misunderstand. I’m saying that the quarries are taking more power than they require. Use a full nitro energy cell and watch how quickly the power drops.

**Comment by ThatElektrika** [comment]
I don’t mean the quarry doesn’t work at all, I mean that it is accepting more power than it can hold or use. As such, excess power gets voided.

**Comment by Kotori316** [comment]
You mean quarry accepts more energy than its capacity?

**Comment by ThatElektrika** [comment]
so ig this means you found something and were able to patch it? (srry for the late response, was asleep)

**Comment by Kotori316** [comment]
Yes. I released fixed version.

**Comment by ThatElektrika** [comment]
ok, thank you!
