### ISSUE TITLE
ATM 9 Quarry is not mining when chunks are loaded/claimed by FTB Chunks

### ISSUE THREAD

**Issue by fengyuan213** [Kotori316/QuarryPlus#630]
## Describe the bug

_What happened to you?_
ATM 9 Quarry is not mining when chunks are loaded/claimed by FTB Chunks
## To Reproduce
![image](https://github.com/user-attachments/assets/cc327661-7921-4d43-b487-3bb8b973ae72)
I have already enabled chunck mining when claimed, in the config file and I did restart game, now the warning says that " Chunk is not protected" when placing the miner is gone, however, when actually mining, it does not break the block, just go pass it. The miner I am using is solid fuel quarry
## Versions

* Minecraft version: [1.20.1]
* Single Player or Multi Player?: [Single]
* Forge version: [47.2.8]
* QuarryPlus version: [1201.1.90]
* Other mods: []

## Crash report or logs

If your Minecraft has crashed, please attach the crash report. Please use pastebin or just paste the report.

**Comment by Kotori316** [comment]
Give me the version of FTB Chunk

**Comment by Kotori316** [comment]
I forgot the logic, but it seems the configuration is used only for suppress the message.
You need to change FTB chunk config to allow quarry to work, but I don't know the detail of FTB Chunk. Quarry uses a fake player with name = `[QuarryPlus]` and uuid = `ce6c3b8d-11ba-4b32-90d5-e5d30167fca7`, that's the only thing I know.

Or, just you can stop using claimed area. That's the most simple way. Does claimed area in single player mode do anything?

**Comment by fengyuan213** [comment]
The version of FTB chunk is ftb-chunks-forge-2001.3.1.

I need to use it's chunk loader function, in order to use it it need to be claimed first. The QuarryPlus does not seems to be built in with chunk loaders. (Mining in different world than player resides in)

**Comment by Kotori316** [comment]
The quarry has chunk loading system. I don't know whether it works or not in the modpack, as the pack might contain a mod which conflicts with quarry system.
Anyway, the quarry never works in claimed area, as it's intended. FTB chunk bothers quarry work. This is why I set warning message when player places a mining machine. You need to change the config of FTB chunk to allow quarry to remove blocks.
