### ISSUE TITLE
Request: Redstone Signal Control

### ISSUE THREAD

**Issue by WardenCommander** [Kotori316/QuarryPlus#65]
Hello,
first of all love this mode, played with it in 1.7.10

nice feature would be if you could add Redstone SIgnal Control, like in Energy Cell from ThermalExpansion had/has...
example... that quarry output redstone signal when it finish work, all area is mined and internal inventory is empty, (this could be configurated ingame perhapse)
What you think?

**Comment by Kotori316** [comment]
I'm sorry I'm not maintaining QuarryPlus for 1.7.10
No one is working on 1.7.10 version according to [this page](https://github.com/yogpstop/QuarryPlus/network) and I'm NOT planning to work.

The idea is good, but why you want to stop the machine?

**Comment by WardenCommander** [comment]
I use to play mod on 1.7.10

now i play it on 1.12.2

> The idea is good, but why you want to stop the machine?<

i dont want to stop machine, but i want signal when machine is finish with work, and I would like to use that signal.

**Comment by Kotori316** [comment]
Use comparator.
The block outputs RS signal when working but the internal inventory won't be considered.

### Stopped
![2019-10-09_20 12 34](https://user-images.githubusercontent.com/28705167/66476710-3f258a00-ead1-11e9-8a90-3a699cfac93b.png)

### Working
![2019-10-09_20 12 40](https://user-images.githubusercontent.com/28705167/66476781-667c5700-ead1-11e9-91b4-65320134324e.png)
