### ISSUE TITLE
Suggestion GUI

### ISSUE THREAD

**Issue by WardenCommander** [Kotori316/QuarryPlus#69]
Hello,

could you add in Quarry plus GUI list and level of enchantment
and energy requirement.
maybe internal storage?

**Comment by Kotori316** [comment]
I added GUI opened by right clicking with "Status Checker".
It shows Enchantment and Required energy per tick.
Edit: Version 14.1.0

**Comment by WardenCommander** [comment]
Could you make update for 1.12.2 version please?
when storage next to quarry is full quarry store resource internally.
would it be possible to get info if quarry is not empty of ore/liquid in GUI?

**Comment by Kotori316** [comment]
Uploaded new version.
https://www.curseforge.com/minecraft/mc-mods/additional-enchanted-miner/files/2812381
