### ISSUE TITLE
Pump module makes quarry stop working if quarry is too big

### ISSUE THREAD

**Issue by Irator1** [Kotori316/QuarryPlus#72]
Hey

When i use pump module in quarry, it stops mining when the quarry size is bigger than roughly 100x100
Have tried multiple different sizes, but as long as i keep quarry smaller than that, it works fine.
If i remove pump module from a big quarry, it starts mining again - and stops if i place it in again....

The same also happens with OldQuarry and it's "old pump module".

Using version 12.2.8 with latest forge

Edit: seems like it stops if there is too much water to remove in 1 layer

**Comment by Kotori316** [comment]
Does quarry work when `NoEnergy` in config is true? If yes, your problem is a shortage of energy. Also, it may be solved by just reloading world.

**Comment by Irator1** [comment]
Works with NoEnergy enabled.
Disabled it again just to check if it stopped working, and it stopped.

**Comment by Irator1** [comment]
Used the latest version - 12.2.9. Works now :)
Energy consumption seems to be much more dynamic/fluctuating, which is fine.

thanks !
