### ISSUE TITLE
[1.21.1 Neoforge] Flexible Marker allows permanent server crash 

### ISSUE THREAD

**Issue by FronkMau** [Kotori316/QuarryPlus#722]
## Description

After accidentally setting only the left value for the quarry to 32 using a flexible marker and having all the rest at 0 the quarry generated the frame but quickly thereafter created a StackOverflow causing the server to crash and the world to become unusable. A bit harsh of a punishment for a user error.

## To Reproduce

1. Set down a flexible marker
2. Only set the left/right value of the marker to something other than 0 (or leave them at 0 as well)
3. Set down the quarry next to the marker and power it on
4. Crash should happen right after finishing the frame

## Versions

* Minecraft version: 1.21.1
* Single Player or Multi Player?: Both
* Neoforge version: 21.1.74
* QuarryPlus version: 21.1.112
* Other mods: in log

## Crash report or logs

https://pastebin.com/EeeHK2Y2

**Comment by Kotori316** [comment]
I'll take a look

**Comment by Kotori316** [comment]
I found there is a bug for some edge cases when area doesn't have enough room for work. I'll work to fix.

**Comment by Kotori316** [comment]
Fixed in the latest release for 1.21.1
