### ISSUE TITLE
Unable to Enchant

### ISSUE THREAD

**Issue by WolfTM** [Kotori316/QuarryPlus#733]
Minecraft: 1.21.1
Fabric: 0.16.9
QuarryPlus: AdditionalEnchantedMiner-1.21.1-fabric-21.1.115

The issue has re-appeared in 1.21.1 Fabric.
Works in creative, but in survival mode the anvil gives nothing.

Previous post of the same issue that was fixed: https://github.com/Kotori316/QuarryPlus/issues/162

**Comment by Kotori316** [comment]
Fixed and released for 1.21.1
