### ISSUE TITLE
[1.14.4] Crash on server

### ISSUE THREAD

**Issue by Gbergz** [Kotori316/QuarryPlus#75]
One of my user playing my pack [TNP: Limitless](https://www.curseforge.com/minecraft/modpacks/tnp-limitless) just reported a crash while using an "XP item??" with the Quarry, he had to start all over again because if he re-entered the same crash would occurr.

I don't have any more information, hope the crash report below helps.

MC-Version: 1.14.4
Mod-Version: 14.1.2
Forge-Version: 28.1.107

Crash-report: [https://hastebin.com/cedotosoye.rb](https://hastebin.com/cedotosoye.rb)  - [https://paste.ee/p/4wCH9](https://paste.ee/p/4wCH9) same link two different pastes sites.

**Comment by Kotori316** [comment]
I'll upload fixed version to curseforge.
Client crashed when attachments (ExpPump, PumpPlus, Replacer) was placed next to quarry. The fixed version doesn't cause this crash.

**Comment by Kotori316** [comment]
Updated [v14.1.4](https://www.curseforge.com/minecraft/mc-mods/additional-enchanted-miner/files/2848855).
