### ISSUE TITLE
[1.15.2] Unable to mine mod ore

### ISSUE THREAD

**Issue by FiveEYZ** [Kotori316/QuarryPlus#78]
I have had a Quarry Plus running for a while and went to check how much EXP the "Quarry Exp Collect Module" has gathered and noticed it was over 190k EXP (climbing fast), but the drill was only 6-7 layers down.
 
the drill standing still even with power going in, so i went to the location the drill was at and it was hovering above a "Inferium Ore" from the mod Mystical Agriculture

OS: Windows Server 2012 R2
Java Version: 1.8.0_241
forge-1.15.2-31.1.0

AdditionalEnchantedMiner-1.15.1-15.2.0
MysticalAgriculture-1.15.2-3.0.0

EDIT:
after further checking i see it was able to mine a few ores both inferium and prosperity ore (both from same mod) so its odd that it was standing still and mass generating EXP above a Inferium Ore.

**Comment by Kotori316** [comment]
What kind of energy supplier were you using? How much amount of energy can it provide?

It seems that quarry used energy for gather exp from ore and there aren't enough energy to break the ore, then quarry tries to collect exp but can't break ore due to lack of energy and ...(loop)
I came up this idea so I want to know how much FE/t you provided to quarry.

**Comment by FiveEYZ** [comment]
My current power gen setup maxes out at 222 FE/T (2x Advanced solar panels from Mekanism) 
and is transferred with Dimensional cell from RFTools over 750 blocks, so the theory with not enough power sounds about right.

If I let the Dimensional cell fill up a bit then it will power thru and mine the ores only to use up the buffer and stop above a Inferium Ore again.

**Comment by Kotori316** [comment]
Try v15.2.1

Edit: File link
https://www.curseforge.com/minecraft/mc-mods/additional-enchanted-miner/files/2884180
