### ISSUE TITLE
Solid Fuel Quarry Not Running

### ISSUE THREAD

**Issue by gagestinsonOSU** [Kotori316/QuarryPlus#81]
I have placed markers and thrown coal blocks in and chests and the quarry does not run. Am i missing a step?

**Comment by Kotori316** [comment]
See https://github.com/Kotori316/QuarryPlus/wiki/SolidQuarry
I added picture.

~If machine doesn't start working, reopen this issue and tell me more info. (Version and etc.)~

**Comment by Kotori316** [comment]
I found some bugs in 1.15.2 version.
I'll release fixed version later.

**Comment by gagestinsonOSU** [comment]
It actually seems to be working now. I had to dig out some area around the caution lines and then break the quarry and replace it to update the block i guess.

**Comment by gagestinsonOSU** [comment]
I am actually getting a different issue now. The quarry just stopped. It has fuel and everything but the laser just stopped moving.

**Comment by Kotori316** [comment]
Uploaded [v15.2.5](https://www.curseforge.com/minecraft/mc-mods/additional-enchanted-miner/files/2906834) for Minecraft 1.15.2
I'll update 1.14.4 version later.
