### ISSUE TITLE
No fluid tanks in 1.15.2?

### ISSUE THREAD

**Issue by Marmarbear0820** [Kotori316/QuarryPlus#82]
**Describe the bug**
there's blocks that don't have any use and i'm not sure how to use the "mining well plus" because there's no description on your website link for it

**To Reproduce**
1. Go to your forge page 
2. Click on the link to see what everything does
3. cant find mining well plus block or dummy block on the list
![2020-03-26_23 47 19](https://user-images.githubusercontent.com/62736766/77730354-db7b1480-6fbd-11ea-9155-9959ac5eca12.png)
![2020-03-26_23 58 47](https://user-images.githubusercontent.com/62736766/77730356-dcac4180-6fbd-11ea-88ac-114ac5eaab41.png)

4. 

**Version**
* Minecraft: 1.15.2
* Forge: 1.15.2
* This mod: 1.15.2
* Other mods: 1.15.2

**Comment by Kotori316** [comment]
See https://github.com/Kotori316/QuarryPlus/wiki/MiningWellPlus
`Dummy Block` is placed by `Quarry Replacer`. See last picture in [this page](https://github.com/Kotori316/QuarryPlus/wiki/Replacer).
