### ISSUE TITLE
Solid Fuel Quarry places weird

### ISSUE THREAD

**Issue by RoyalReject** [Kotori316/QuarryPlus#83]
**Describe the bug**
_What happened to you?_
Solid Fuel Quarry Places backwards

**To Reproduce**
1. Place Solid Fuel Quarry
2. 
3. 

**Version**
* Minecraft: [1.15.2]
* Forge: []
* This mod (QuarryPlus): [
v15.2.5
]
* Other mods: []

**Comment by Kotori316** [comment]
Fixed in [v15.2.6](https://www.curseforge.com/minecraft/mc-mods/additional-enchanted-miner/files/2916284).
