### ISSUE TITLE
Server crashed while trying to start it.

### ISSUE THREAD

**Issue by ChaseJM6** [Kotori316/QuarryPlus#84]
**Describe the bug**
_What happened to you?_
I was trying to start my minecraft server with a few mods and the server crashed with the AdditionalEnchantedMiner and it said it was missing something and told me I was missing this [main/ERROR] [net.minecraftforge.fml.loading.LanguageLoadingProvider/]: Missing language kotori_scala version [2.13.1,2.14.0) wanted by AdditionalEnchantedMiner-1.15.2-15.2.6.jar in my log in the server hosting thing and my minecraft. **To Reproduce**
1.
2. 
3. 

**Version**
* Minecraft: [1.15.2]
* Forge: [1.15.2-31.1.44-installer.jar]
* This mod (QuarryPlus): [AdditionalEnchantedMiner]
* Other mods: []

**Comment by Kotori316** [comment]
Quarry Plus needs library mod. Download [this file](https://www.curseforge.com/minecraft/mc-mods/scalable-cats-force/files/2871351) and put it into mods folder.
