### ISSUE TITLE
[1.12.2] Ender IO Zoo mod interaction

### ISSUE THREAD

**Issue by joselitosn** [Kotori316/QuarryPlus#86]
**Describe the bug**
When the drill from a Quarry stops over a dirty block, it keeps spawning the Khndrel Keght mob from Ender IO Zoo.

Ender IO Zoo has a mob called Khndrel Keght (a kind of slime like mob), which there is a chance to spawn when you break a dirt block with the incorrect tool.

The problem is that when there is not enough power and the drill from the Quarry stops over a dirt block without breaking it, it keeps spawning the mob endlessly.

**To Reproduce**
1. Put a quarry (any).
2. Produce enough power to build the structure.
3. Remove power so the drill bit stops over a dirt block.

**Version**
* Minecraft: [1.12.2]
* Forge: [14.23.5.2847]
* This mod (QuarryPlus): [12.3.8]
* Other mods: [Ender IO Zoo 5.1.55]

Edit: Just decided to test the MiningWell Plus and just placing it over dirt causes the same effect.

**Comment by Kotori316** [comment]
Fixed issue of endless spawning dirt slime. (Wait for new version, see below.)

Quarry breaks all blocks with Diamond Pickaxe now, and you may have seen the slime even if you supplies enough energy to quarry, Should I change it? (Do you think the slime should spawn during quarry mining?)

**Comment by joselitosn** [comment]
My assumption would be that the drill is considered the correct tool for any kind of ground block (which in the code might mean a shovel for sand, gravel and dirt, and pickaxe for everything else).

My concern now is that using the diamond level tool might break compatibilty with mods which require higher level tools.

But just fixing the endless spawning is fine, I consider the normal spawning an expected mod interaction.

**Comment by Kotori316** [comment]
Uploaded [v12.3.9](https://www.curseforge.com/minecraft/mc-mods/additional-enchanted-miner/files/2944214).

Quarries now use effective tool which is treated as pickaxe, axe and shovel, so dirt slime will never be spawned. The slime doesn't take fall damage so you need to kill them. It's not automatic process.
