### ISSUE TITLE
Add range option in config for Advanced Pump

### ISSUE THREAD

**Issue by henrydatei** [Kotori316/QuarryPlus#87]
Currently the range for the Advanced Pump is 64 blocks. It would be nice if I could increase this in a config file.

**Comment by Kotori316** [comment]
Move fortune to the pump, and range will be expanded.

| Fortune | Range(r) |
| :--: | :--: |
| Zero | 32|
| I | 64 |
| II | 96|
| III | 128 |

See [this page](https://github.com/Kotori316/QuarryPlus/wiki/EnchantMover) to get how to move enchantment.
