### ISSUE TITLE
Server crash when Status Checker is used on QuarryPlus. 1.15.2

### ISSUE THREAD

**Issue by WhitePhant0m** [Kotori316/QuarryPlus#88]
When I used the Status Checker on QuarryPlus it crashed my server.
Here is the [crash report](https://pastebin.com/Wr8UrNZM).

**Comment by Quu1337** [comment]
https://github.com/yogpstop/QuarryPlus/issues/41

**Comment by Kotori316** [comment]
I fixed the crash but I found some bug in tracking integer. So don't believe text of item number and fluid amount.
https://www.curseforge.com/minecraft/mc-mods/additional-enchanted-miner/files/2951201
I leave this issue open until I fix the bug of item number.

**Comment by Kotori316** [comment]
Fixed all in [v15.2.8](https://www.curseforge.com/minecraft/mc-mods/additional-enchanted-miner/files/2951511)
