### ISSUE TITLE
1.12.2-0.7.2 Filler doesn't work

### ISSUE THREAD

**Issue by kreezxil** [Kotori316/QuarryPlus#9]
It takes blocks from the inventory but the quarry doesn't place them

**Comment by NickelodeonKing** [comment]
Items like cobble, andesite, diorite and dirt have been placed into separate quarries to test the filler function, but none of the quarries even started to place blocks.

**Comment by Kotori316** [comment]
QuarryPlus doesn't have function to place blocks. The filler mode means quarry breaks only blocks inside the frame as below picture shows
![2017-12-30_11 03 14](https://user-images.githubusercontent.com/28705167/34450681-5c53664c-ed53-11e7-9bbf-d10ef591035f.png)
.

**Comment by Kotori316** [comment]
I'll fix the issue that quarry takes items from inventory like hopper in next release.

**Comment by kreezxil** [comment]
Huh, can you add a filler mode that works as we described?

Based on your description I would change the current filler mode to frame
mode.

Also a wiki or some pages on CurseForge describing in detail everything
your mod does would be most helpful.

Also we love your mod.

**Comment by Kotori316** [comment]
1. **I won't add filler to this mod.** Please use BC's filler or builders wand.

2.  **I may change the mode name in future.** I confused how the filler mode works on the first time to play QuarryPlus for 1.7.10. When I ported to 1.12.2, I left it as is to respect original behavior.

3. **I will add description of this mod in next year.** I added new plus machines, "Chunk Destroyer" and "Advanced Pump", but I didn't describe how to use them.

**Comment by kreezxil** [comment]
Thanks for the update.

**Comment by NickelodeonKing** [comment]
AWWW... dang i like quarrying but i like refilling the holes with the slag materials... this sucks.. other than this issue the mod is amazing.
