### ISSUE TITLE
Server crash on startup 1.15.2

### ISSUE THREAD

**Issue by ghost** [Kotori316/QuarryPlus#91]
**Describe the bug**
Crash on server startup
https://pastebin.com/Th5CsS4J

**Version**
* [1.15.2]
* [MP]
* Forge: [31.2.8]
* This mod (QuarryPlus): [15.3.0]
* Other mods: [+++++++++++++++++++++++++++++++++]

**Comment by Kotori316** [comment]
Fixed in [v15.3.1](https://www.curseforge.com/minecraft/mc-mods/additional-enchanted-miner/files/2975187).
Thank you for reporting.
