### ISSUE TITLE
Workbench Plus Incompatibility With Forge Energy

### ISSUE THREAD

**Issue by gagestinsonOSU** [Kotori316/QuarryPlus#93]
I cannot seem to get Workbench Plus powered. I have Solar Flux Reborn and Flux Network but Forge Energy will not power the workbench. I checked and it does power the Quarry Plus so I would assume it powers the others as well, just not the workbench.

**Comment by Kotori316** [comment]
Which version of Minecraft are you playing?

Workbench will start receiving energy after you selected recipe on machine GUI.
So place solar panel or adopter **after** selecting recipe.
