### ISSUE TITLE
Cannot specify custom range with Marker Plus and Quarry Plus

### ISSUE THREAD

**Issue by ClaudiusMinimus** [Kotori316/QuarryPlus#96]
The Marker Plus does not seem to connect with the Quarry Plus as shown in the screenshot. Or else I am doing something wrong. I used your [tutorial](https://github.com/Kotori316/QuarryPlus/wiki/QuarryPlus-Tutorials) as a reference

**Version**
* Minecraft: 1.16.1
* Single Player or Multi Player?: Both. I first discovered this playing ATM6 on our server, then decided to test in a local SP world.
* Forge: 1.16.1-32.0.75
* This mod (QuarryPlus): v16.0.5
* Other mods: JEI for testing only

![2020-07-21_23 05 37](https://user-images.githubusercontent.com/17887664/88136739-250ff080-cba7-11ea-94bd-a272a21afb41.png)

**Comment by Kotori316** [comment]
See https://github.com/Kotori316/QuarryPlus/wiki/MarkerPlus
Also, place machine next to marker block. In your picture, it seems you placed machine at the edge of area with no marker block.

**Comment by ClaudiusMinimus** [comment]
That worked! Thanks! Might I suggest you add a screenshot showing the machine in the proper location. 
![2020-07-22_10 35 33](https://user-images.githubusercontent.com/17887664/88203602-50c2c300-cc07-11ea-86be-88f1b0d95170.png)
