### ISSUE TITLE
Client error as soon as delivered improved workbench 1.12.2

### ISSUE THREAD

**Issue by xxxLEOPARDxxx** [Kotori316/QuarryPlus#98]
https://gist.github.com/xxxLEOPARDxxx/6dfa66dbfd35e071daef047ecc68d098
https://i.gyazo.com/8bffe67164e890d9908d2fa65b9cf1f2.png

**Comment by Kotori316** [comment]
I don't know what you did so I tried actions I can do, but your problem didn't happen.

**Comment by xxxLEOPARDxxx** [comment]
I have a separate server 1.12.2
I play it via client + server.
When it comes to an improved workbench, this is the problem. So far, it is the workbench itself that creates such a bug.
It may not be right away. and after a while, but this problem is guaranteed to happen.
I beg you to understand this, otherwise I have to store the workbench in a chest or in a backpack.

**Comment by Kotori316** [comment]
Do you mean the crash happened after you have added WorkbenchPlus into player's inventory or placed it into the world?

Does the crash happen even in new world?

If you don't mind, give me a list of mods, please.

**Comment by xxxLEOPARDxxx** [comment]
Yes, this happens when I put the workbench on the ground.
Failure may not happen immediately, but after a while. Or even after restarting the server or rebooting to the server itself. but it certainly happens.
Mod_list - https://gist.github.com/xxxLEOPARDxxx/bcc4c3e384020359bc384d6d717b09aa

**Comment by Kotori316** [comment]
Umm...

Your log tells the crash was caused by a class(`SPacketUpdateTileEntity`) so I added code in WorkbenchPlus not to use the class.
The crash may happen only in dedicated server(multi players server) because the class(`SPacketUpdateTileEntity`) is not called in the single player world.
In my dev server with a few mods, of course, a crash didn't happen. (I have no time to collect your 150+ mods.)

[v12.4.2](https://www.curseforge.com/minecraft/mc-mods/additional-enchanted-miner/files/3020641)

**Comment by xxxLEOPARDxxx** [comment]
Thanks for the quick fix, I'll check everything and be sure to let you know if something goes wrong! ;)

**Comment by xxxLEOPARDxxx** [comment]
Unfortunately. the same NBT error keeps recurring when I place the upgraded workbench on the ground.

Your quarry is the best, but I can't use the workbench. I have to collect resources and throw them away, and through the server console add the things I need that I could do on this workbench.

**Comment by xxxLEOPARDxxx** [comment]
I can download all my mods for you to check for yourself.

**Comment by Kotori316** [comment]
Umm...
[v12.4.3](https://www.curseforge.com/minecraft/mc-mods/additional-enchanted-miner/files/3023017)

It may cause the same problem. If you catch it, please give me the new log, both `debug.log` and `latest.log`.

Also, please try it on new server world.

**Comment by xxxLEOPARDxxx** [comment]
Thanks again for your promptness!
The NBT error seems to have disappeared)
