### ISSUE TITLE
Infinite Crafting Bug

### ISSUE THREAD

**Issue by CapitanCJ** [Kotori316/QuarryPlus#99]
**Describe the bug**
I'm running AllTheMods6 Modpack on a server and I am able to make an infinite amount of MiningWell Pluses and Marker Pluses by keeping the recipe selected yellow.

**To Reproduce**
1. Place items in Workbench Plus.
2. Select Item with Yellow selection mode

**Version**
* Minecraft: 1.16.1
* Single Player or Multi Player?: Multi Player (untested on SP)
* Forge: 32.0.88
* This mod (QuarryPlus): Additional Enchanted Miner-1.16.1-16.0.7
* Other mods: AllTheMods6 - 0.23 (Modpack)

**Comment by Kotori316** [comment]
Fixed in 16.0.8.
Thank you for reporting.
